/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

#ifndef _HAL_PMU_PLATFORM_H_
#define _HAL_PMU_PLATFORM_H_

#define PMU_REG_BASE (0x0000)

#define PMU_CON0                     (PMU_REG_BASE+0x0000)
#define PMU_CON1                     (PMU_REG_BASE+0x0002)
#define PMU_CON2                     (PMU_REG_BASE+0x0004)
#define PMU_CON3                     (PMU_REG_BASE+0x0006)
#define PMU_STATE0                   (PMU_REG_BASE+0x0008)
#define PMU_STATE1                   (PMU_REG_BASE+0x000A)
#define PMU_IVGEN0                   (PMU_REG_BASE+0x000C)
#define PMU_IVGEN1                   (PMU_REG_BASE+0x000E)
#define PMU_PG0                      (PMU_REG_BASE+0x0010)
#define IO_CFG0                      (PMU_REG_BASE+0x0012)
#define IO_CFG1                      (PMU_REG_BASE+0x0014)
#define IO_CFG2                      (PMU_REG_BASE+0x0016)
#define IO_CFG3                      (PMU_REG_BASE+0x0018)
#define IO_CFG4                      (PMU_REG_BASE+0x001A)
#define IO_CFG5                      (PMU_REG_BASE+0x001C)
#define CFG_RESERVE                  (PMU_REG_BASE+0x001E)
#define PMU_PROT                     (PMU_REG_BASE+0x0020)
#define PMU_RESET0                   (PMU_REG_BASE+0x0024)

#define BUCK_CON0                    (PMU_REG_BASE+0x0100)
#define BUCK_CON1                    (PMU_REG_BASE+0x0102)
#define BUCK_CON2                    (PMU_REG_BASE+0x0104)
#define BUCK_CON3                    (PMU_REG_BASE+0x0106)
#define BUCK_CON4                    (PMU_REG_BASE+0x0108)
#define BUCK_CON5                    (PMU_REG_BASE+0x010A)
#define BUCK_CON6                    (PMU_REG_BASE+0x010C)
#define BUCK_CON7                    (PMU_REG_BASE+0x010E)
#define BUCK_CON8                    (PMU_REG_BASE+0x0110)
#define BUCK_CON9                    (PMU_REG_BASE+0x0112)
#define BUCK_CON10                   (PMU_REG_BASE+0x0114)

#define LDO_CON0                     (PMU_REG_BASE+0x0200)
#define LDO_CON1                     (PMU_REG_BASE+0x0202)
#define LDO_CON2                     (PMU_REG_BASE+0x0204)
#define LDO_CON3                     (PMU_REG_BASE+0x0206)
#define LDO_CON4                     (PMU_REG_BASE+0x0208)
#define LDO_CON5                     (PMU_REG_BASE+0x020A)
#define LDO_CON6                     (PMU_REG_BASE+0x020C)
#define LDO_CON7                     (PMU_REG_BASE+0x020E)

#define CHARGER_TH0                  (PMU_REG_BASE+0x0300)
#define CHARGER_TH1                  (PMU_REG_BASE+0x0302)
#define CHARGER_TH2                  (PMU_REG_BASE+0x0304)
#define CHARGER_TH3                  (PMU_REG_BASE+0x0306)
#define CHARGER_TH4                  (PMU_REG_BASE+0x0308)
#define CHARGER_TH5                  (PMU_REG_BASE+0x030A)
#define CHARGER_TH6                  (PMU_REG_BASE+0x030C)
#define CHARGER_DAC0                 (PMU_REG_BASE+0x030E)
#define CHARGER_DAC1                 (PMU_REG_BASE+0x0310)
#define CHARGER_DAC2                 (PMU_REG_BASE+0x0312)
#define CHARGER_DAC3                 (PMU_REG_BASE+0x0314)
#define CHARGER_RSEL0                (PMU_REG_BASE+0x0316)
#define CHARGER_RSEL1                (PMU_REG_BASE+0x0318)
#define CHARGER_RSEL2                (PMU_REG_BASE+0x031A)
#define CHARGER_RSEL3                (PMU_REG_BASE+0x031C)
#define CHARGER_CON0                 (PMU_REG_BASE+0x031E)
#define CHARGER_CON1                 (PMU_REG_BASE+0x0320)
#define CHARGER_CON2                 (PMU_REG_BASE+0x0322)
#define CHARGER_CON3                 (PMU_REG_BASE+0x0324)
#define CHARGER_CON4                 (PMU_REG_BASE+0x0328)
#define CHARGER_CON5                 (PMU_REG_BASE+0x032A)

#define ADC_CON0                     (PMU_REG_BASE+0x0400)
#define ADC_CON1                     (PMU_REG_BASE+0x0402)
#define ADC_CON2                     (PMU_REG_BASE+0x0404)
#define ADC_CON3                     (PMU_REG_BASE+0x0406)
#define ADC_CON4                     (PMU_REG_BASE+0x0408)
#define ADC_CON5                     (PMU_REG_BASE+0x040A)
#define ADC_DATA0                    (PMU_REG_BASE+0x040C)
#define ADC_DATA1                    (PMU_REG_BASE+0x040E)
#define ADC_DATA2                    (PMU_REG_BASE+0x0410)
#define ADC_DATA3                    (PMU_REG_BASE+0x0412)
#define ADC_DATA4                    (PMU_REG_BASE+0x0414)
#define ADC_DATA5                    (PMU_REG_BASE+0x0416)
#define ADC_STATE0                   (PMU_REG_BASE+0x0418)


#define LED_EN_CTRL                  (PMU_REG_BASE+0x0500)
#define LED0_CON0                    (PMU_REG_BASE+0x0502)
#define LED0_UNIT                    (PMU_REG_BASE+0x0504)
#define LED0_PERIOD0                 (PMU_REG_BASE+0x0506)
#define LED0_PERIOD1                 (PMU_REG_BASE+0x0508)
#define LED0_PWM0                    (PMU_REG_BASE+0x050A)
#define LED0_PWM1                    (PMU_REG_BASE+0x050C)
#define LED0_PWM2                    (PMU_REG_BASE+0x050E)
#define LED1_CON0                    (PMU_REG_BASE+0x0510)
#define LED1_UNIT                    (PMU_REG_BASE+0x0512)
#define LED1_PERIOD0                 (PMU_REG_BASE+0x0514)
#define LED1_PERIOD1                 (PMU_REG_BASE+0x0516)
#define LED1_PWM0                    (PMU_REG_BASE+0x0518)
#define LED1_PWM1                    (PMU_REG_BASE+0x051A)
#define LED1_PWM2                    (PMU_REG_BASE+0x051C)

#define PMU_TEST0                    (PMU_REG_BASE+0x0600)
#define PMU_TEST1                    (PMU_REG_BASE+0x0602)
#define PMU_TEST2                    (PMU_REG_BASE+0x0604)
#define PMU_TEST3                    (PMU_REG_BASE+0x0606)
#define PMU_TEST4                    (PMU_REG_BASE+0x0608)
#define PMU_TEST5                    (PMU_REG_BASE+0x060A)


//mask is HEX;  shift is Integer

#define CLK32K_OUT_TEST_EN_ADDR              PMU_CON0//0x000
#define CLK32K_OUT_TEST_EN_MASK              0x1
#define CLK32K_OUT_TEST_EN_SHIFT             15
#define I2C_DRV_SEL_ADDR                     PMU_CON0
#define I2C_DRV_SEL_MASK                     0x1
#define I2C_DRV_SEL_SHIFT                    14
#define STRONGPULL_EN_ADDR                   PMU_CON0
#define STRONGPULL_EN_MASK                   0x1
#define STRONGPULL_EN_SHIFT                  13
#define SEVER_REGEN_ADDR                     PMU_CON0
#define SEVER_REGEN_MASK                     0x1
#define SEVER_REGEN_SHIFT                    12
#define KEY_RST_SW_MODE_ADDR                 PMU_CON0
#define KEY_RST_SW_MODE_MASK                 0x1
#define KEY_RST_SW_MODE_SHIFT                11
#define KEY_RST_ADDR                         PMU_CON0
#define KEY_RST_MASK                         0x1
#define KEY_RST_SHIFT                        10
#define PMU_LDO_EN_SW_MODE_ADDR              PMU_CON0
#define PMU_LDO_EN_SW_MODE_MASK              0x1
#define PMU_LDO_EN_SW_MODE_SHIFT             9
#define PMU_LDO_EN_ADDR                      PMU_CON0
#define PMU_LDO_EN_MASK                      0x1
#define PMU_LDO_EN_SHIFT                     8
#define CLK_REG_LP_EN_ADDR                   PMU_CON0
#define CLK_REG_LP_EN_MASK                   0x1
#define CLK_REG_LP_EN_SHIFT                  7
#define CLK_LED_LP_EN_ADDR                   PMU_CON0
#define CLK_LED_LP_EN_MASK                   0x1
#define CLK_LED_LP_EN_SHIFT                  6
#define CLK_CHG_LP_EN_ADDR                   PMU_CON0
#define CLK_CHG_LP_EN_MASK                   0x1
#define CLK_CHG_LP_EN_SHIFT                  5
#define CLK_ADC_LP_EN_ADDR                   PMU_CON0
#define CLK_ADC_LP_EN_MASK                   0x1
#define CLK_ADC_LP_EN_SHIFT                  4
#define OSC_EN_RTC_ADDR                      PMU_CON0
#define OSC_EN_RTC_MASK                      0x1
#define OSC_EN_RTC_SHIFT                     2
#define OSC_EN_SLEEP_ADDR                    PMU_CON0
#define OSC_EN_SLEEP_MASK                    0x1
#define OSC_EN_SLEEP_SHIFT                   1
#define OSC_EN_NORM_ADDR                     PMU_CON0
#define OSC_EN_NORM_MASK                     0x1
#define OSC_EN_NORM_SHIFT                    0
#define UART_LVSH_S2VDIG18_FORCE_ADDR        PMU_CON1//0x002
#define UART_LVSH_S2VDIG18_FORCE_MASK        0x1
#define UART_LVSH_S2VDIG18_FORCE_SHIFT       5
#define UART_LVSH_G2VDIG18_FORCE_ADDR        PMU_CON1
#define UART_LVSH_G2VDIG18_FORCE_MASK        0x1
#define UART_LVSH_G2VDIG18_FORCE_SHIFT       4
#define UART_LVSH_FORCEDIS_ADDR              PMU_CON1
#define UART_LVSH_FORCEDIS_MASK              0x1
#define UART_LVSH_FORCEDIS_SHIFT             3
#define UART_PSWMAIN_CL_ENB_ADDR             PMU_CON1
#define UART_PSWMAIN_CL_ENB_MASK             0x1
#define UART_PSWMAIN_CL_ENB_SHIFT            2
#define UART_PSWAUX_ENB_ADDR                 PMU_CON1
#define UART_PSWAUX_ENB_MASK                 0x1
#define UART_PSWAUX_ENB_SHIFT                1
#define UART_PSWMAIN_ENB_ADDR                PMU_CON1
#define UART_PSWMAIN_ENB_MASK                0x1
#define UART_PSWMAIN_ENB_SHIFT               0
#define OFF2IDLE_FLAG_ADDR                   PMU_CON2//0x004
#define OFF2IDLE_FLAG_MASK                   0x1
#define OFF2IDLE_FLAG_SHIFT                  15
#define UVSD_VCORE_FLAG_ADDR                 PMU_CON2
#define UVSD_VCORE_FLAG_MASK                 0x1
#define UVSD_VCORE_FLAG_SHIFT                14
#define UVSD_VIO_FLAG_ADDR                   PMU_CON2
#define UVSD_VIO_FLAG_MASK                   0x1
#define UVSD_VIO_FLAG_SHIFT                  13
#define OC_FLAG_ADDR                         PMU_CON2
#define OC_FLAG_MASK                         0x1
#define OC_FLAG_SHIFT                        12
#define UVSD_VCORE_EN_ADDR                   PMU_CON2
#define UVSD_VCORE_EN_MASK                   0x1
#define UVSD_VCORE_EN_SHIFT                  11
#define UVSD_VIO_EN_ADDR                     PMU_CON2
#define UVSD_VIO_EN_MASK                     0x1
#define UVSD_VIO_EN_SHIFT                    10
#define OC_PROT_EN_ADDR                      PMU_CON2
#define OC_PROT_EN_MASK                      0x1
#define OC_PROT_EN_SHIFT                     9
#define WD_RST_EN_ADDR                       PMU_CON2
#define WD_RST_EN_MASK                       0x1
#define WD_RST_EN_SHIFT                      8
#define SYS_RST_EN_ADDR                      PMU_CON2
#define SYS_RST_EN_MASK                      0x1
#define SYS_RST_EN_SHIFT                     7
#define REGEN_LPSD_EN_ADDR                   PMU_CON2
#define REGEN_LPSD_EN_MASK                   0x1
#define REGEN_LPSD_EN_SHIFT                  6
#define CAP_LPSD_EN_ADDR                     PMU_CON2
#define CAP_LPSD_EN_MASK                     0x1
#define CAP_LPSD_EN_SHIFT                    5
#define REGEN_ALARM_EN_ADDR                  PMU_CON2
#define REGEN_ALARM_EN_MASK                  0x1
#define REGEN_ALARM_EN_SHIFT                 4
#define RTC_ALARM_EN_ADDR                    PMU_CON2
#define RTC_ALARM_EN_MASK                    0x1
#define RTC_ALARM_EN_SHIFT                   3
#define CHG_ALARM_EN_ADDR                    PMU_CON2
#define CHG_ALARM_EN_MASK                    0x1
#define CHG_ALARM_EN_SHIFT                   2
#define RTC_MODE_ADDR                        PMU_CON2
#define RTC_MODE_MASK                        0x1
#define RTC_MODE_SHIFT                       1
#define PWR_OFF_ADDR                         PMU_CON2
#define PWR_OFF_MASK                         0x1
#define PWR_OFF_SHIFT                        0
#define WD_RST_FLAG_ADDR                     PMU_CON3//0x006
#define WD_RST_FLAG_MASK                     0x1
#define WD_RST_FLAG_SHIFT                    15
#define SYS_RST_FLAG_ADDR                    PMU_CON3
#define SYS_RST_FLAG_MASK                    0x1
#define SYS_RST_FLAG_SHIFT                   14
#define REGEN_LPSD_FLAG_ADDR                 PMU_CON3
#define REGEN_LPSD_FLAG_MASK                 0x1
#define REGEN_LPSD_FLAG_SHIFT                13
#define CAP_LPSD_FLAG_ADDR                   PMU_CON3
#define CAP_LPSD_FLAG_MASK                   0x1
#define CAP_LPSD_FLAG_SHIFT                  12
#define RTC_MODE_FLAG_ADDR                   PMU_CON3
#define RTC_MODE_FLAG_MASK                   0x1
#define RTC_MODE_FLAG_SHIFT                  11
#define REGEN_ALARM_FLAG_ADDR                PMU_CON3
#define REGEN_ALARM_FLAG_MASK                0x1
#define REGEN_ALARM_FLAG_SHIFT               10
#define CHG_ALARM_FLAG_ADDR                  PMU_CON3
#define CHG_ALARM_FLAG_MASK                  0x1
#define CHG_ALARM_FLAG_SHIFT                 9
#define RTC_ALARM_FLAG_ADDR                  PMU_CON3
#define RTC_ALARM_FLAG_MASK                  0x1
#define RTC_ALARM_FLAG_SHIFT                 8
#define REGEN_PON_FLAG_ADDR                  PMU_CON3
#define REGEN_PON_FLAG_MASK                  0x1
#define REGEN_PON_FLAG_SHIFT                 7
#define CHG_PON_FLAG_ADDR                    PMU_CON3
#define CHG_PON_FLAG_MASK                    0x1
#define CHG_PON_FLAG_SHIFT                   6
#define REGEN_IRQ_TIME_SEL_ADDR              PMU_CON3
#define REGEN_IRQ_TIME_SEL_MASK              0x3
#define REGEN_IRQ_TIME_SEL_SHIFT             4
#define REGEN_IRQ_FALL_EN_ADDR               PMU_CON3
#define REGEN_IRQ_FALL_EN_MASK               0x1
#define REGEN_IRQ_FALL_EN_SHIFT              3
#define REGEN_IRQ_FALL_FLAG_ADDR             PMU_CON3
#define REGEN_IRQ_FALL_FLAG_MASK             0x1
#define REGEN_IRQ_FALL_FLAG_SHIFT            2
#define REGEN_IRQ_RISE_EN_ADDR               PMU_CON3
#define REGEN_IRQ_RISE_EN_MASK               0x1
#define REGEN_IRQ_RISE_EN_SHIFT              1
#define REGEN_IRQ_RISE_FLAG_ADDR             PMU_CON3
#define REGEN_IRQ_RISE_FLAG_MASK             0x1
#define REGEN_IRQ_RISE_FLAG_SHIFT            0
#define PWR_STATE_ADDR                       PMU_STATE0//0x008
#define PWR_STATE_MASK                       0x1F
#define PWR_STATE_SHIFT                      0
#define PWR_SEQ_STATE_ADDR                   PMU_STATE1//0x00A
#define PWR_SEQ_STATE_MASK                   0x3FF
#define PWR_SEQ_STATE_SHIFT                  6
#define SLEEP_SEQ_STATE_ADDR                 PMU_STATE1
#define SLEEP_SEQ_STATE_MASK                 0x3F
#define SLEEP_SEQ_STATE_SHIFT                0
#define BGHP_MODE_EN_OFF_ADDR                PMU_IVGEN0//0x00C
#define BGHP_MODE_EN_OFF_MASK                0x1
#define BGHP_MODE_EN_OFF_SHIFT               15
#define BGHP_MODE_EN_RTC_ADDR                PMU_IVGEN0
#define BGHP_MODE_EN_RTC_MASK                0x1
#define BGHP_MODE_EN_RTC_SHIFT               14
#define BGHP_MODE_EN_SLEEP_ADDR              PMU_IVGEN0
#define BGHP_MODE_EN_SLEEP_MASK              0x1
#define BGHP_MODE_EN_SLEEP_SHIFT             13
#define BGHP_MODE_EN_NORM_ADDR               PMU_IVGEN0
#define BGHP_MODE_EN_NORM_MASK               0x1
#define BGHP_MODE_EN_NORM_SHIFT              12
#define BGHP_SEL_ADDR                        PMU_IVGEN0
#define BGHP_SEL_MASK                        0xF
#define BGHP_SEL_SHIFT                       1
#define BGHP_ENB_ADDR                        PMU_IVGEN0
#define BGHP_ENB_MASK                        0x1
#define BGHP_ENB_SHIFT                       0
#define BGR_TRIM_ADDR                        PMU_IVGEN1//0x00E
#define BGR_TRIM_MASK                        0x1F
#define BGR_TRIM_SHIFT                       9
#define BGR_TRIM_ENB_ADDR                    PMU_IVGEN1
#define BGR_TRIM_ENB_MASK                    0x1
#define BGR_TRIM_ENB_SHIFT                   8
#define RETLDO_IBIAS_ADDR                    PMU_IVGEN1
#define RETLDO_IBIAS_MASK                    0x7
#define RETLDO_IBIAS_SHIFT                   5
#define BGLP_SEL_ADDR                        PMU_IVGEN1
#define BGLP_SEL_MASK                        0x3
#define BGLP_SEL_SHIFT                       3
#define FAST_BUFFER_ENB_ADDR                 PMU_IVGEN1
#define FAST_BUFFER_ENB_MASK                 0x1
#define FAST_BUFFER_ENB_SHIFT                2
#define BYPASS_R_EN_ADDR                     PMU_IVGEN1
#define BYPASS_R_EN_MASK                     0x1
#define BYPASS_R_EN_SHIFT                    1
#define BGSW_ADDR                            PMU_IVGEN1
#define BGSW_MASK                            0x1
#define BGSW_SHIFT                           0
#define BUCK_VCORE_POR_EN_OFF_ADDR           PMU_PG0//0x010
#define BUCK_VCORE_POR_EN_OFF_MASK           0x1
#define BUCK_VCORE_POR_EN_OFF_SHIFT          15
#define BUCK_VCORE_POR_EN_RTC_ADDR           PMU_PG0
#define BUCK_VCORE_POR_EN_RTC_MASK           0x1
#define BUCK_VCORE_POR_EN_RTC_SHIFT          14
#define BUCK_VCORE_POR_EN_SLEEP_ADDR         PMU_PG0
#define BUCK_VCORE_POR_EN_SLEEP_MASK         0x1
#define BUCK_VCORE_POR_EN_SLEEP_SHIFT        13
#define BUCK_VCORE_POR_EN_NORM_ADDR          PMU_PG0
#define BUCK_VCORE_POR_EN_NORM_MASK          0x1
#define BUCK_VCORE_POR_EN_NORM_SHIFT         12
#define BUCK_VIO_POR_EN_OFF_ADDR             PMU_PG0
#define BUCK_VIO_POR_EN_OFF_MASK             0x1
#define BUCK_VIO_POR_EN_OFF_SHIFT            11
#define BUCK_VIO_POR_EN_RTC_ADDR             PMU_PG0
#define BUCK_VIO_POR_EN_RTC_MASK             0x1
#define BUCK_VIO_POR_EN_RTC_SHIFT            10
#define BUCK_VIO_POR_EN_SLEEP_ADDR           PMU_PG0
#define BUCK_VIO_POR_EN_SLEEP_MASK           0x1
#define BUCK_VIO_POR_EN_SLEEP_SHIFT          9
#define BUCK_VIO_POR_EN_NORM_ADDR            PMU_PG0
#define BUCK_VIO_POR_EN_NORM_MASK            0x1
#define BUCK_VIO_POR_EN_NORM_SHIFT           8
#define COMP_BIAS_SEL_OFF_ADDR               PMU_PG0
#define COMP_BIAS_SEL_OFF_MASK               0x1
#define COMP_BIAS_SEL_OFF_SHIFT              7
#define COMP_BIAS_SEL_RTC_ADDR               PMU_PG0
#define COMP_BIAS_SEL_RTC_MASK               0x1
#define COMP_BIAS_SEL_RTC_SHIFT              6
#define COMP_BIAS_SEL_SLEEP_ADDR             PMU_PG0
#define COMP_BIAS_SEL_SLEEP_MASK             0x1
#define COMP_BIAS_SEL_SLEEP_SHIFT            5
#define COMP_BIAS_SEL_NORM_ADDR              PMU_PG0
#define COMP_BIAS_SEL_NORM_MASK              0x1
#define COMP_BIAS_SEL_NORM_SHIFT             4
#define COMP_CHG_ENB_FORCE_ADDR              PMU_PG0
#define COMP_CHG_ENB_FORCE_MASK              0x1
#define COMP_CHG_ENB_FORCE_SHIFT             0
#define VIO18_TDSEL_ADDR                     IO_CFG0//0x012
#define VIO18_TDSEL_MASK                     0x1
#define VIO18_TDSEL_SHIFT                    3
#define VIO18_RDSEL_ADDR                     IO_CFG0
#define VIO18_RDSEL_MASK                     0x1
#define VIO18_RDSEL_SHIFT                    2
#define VDIG18_TDSEL_ADDR                    IO_CFG0
#define VDIG18_TDSEL_MASK                    0x1
#define VDIG18_TDSEL_SHIFT                   1
#define VDIG18_RDSEL_ADDR                    IO_CFG0
#define VDIG18_RDSEL_MASK                    0x1
#define VDIG18_RDSEL_SHIFT                   0
#define I2C_DATA_OC_ADDR                     IO_CFG1//0x014
#define I2C_DATA_OC_MASK                     0x7
#define I2C_DATA_OC_SHIFT                    0
#define SRCLK_EN_IC_ADDR                     IO_CFG2//0x016
#define SRCLK_EN_IC_MASK                     0x7
#define SRCLK_EN_IC_SHIFT                    12
#define WDT_RSTB_IC_ADDR                     IO_CFG2
#define WDT_RSTB_IC_MASK                     0x7
#define WDT_RSTB_IC_SHIFT                    8
#define I2C_CLK_IC_ADDR                      IO_CFG2
#define I2C_CLK_IC_MASK                      0x7
#define I2C_CLK_IC_SHIFT                     4
#define I2C_DATA_IC_ADDR                     IO_CFG2
#define I2C_DATA_IC_MASK                     0x7
#define I2C_DATA_IC_SHIFT                    0
#define CAP_LPSD_IC_ADDR                     IO_CFG3//0x018
#define CAP_LPSD_IC_MASK                     0x7
#define CAP_LPSD_IC_SHIFT                    4
#define RTC_ALARM_IC_ADDR                    IO_CFG3
#define RTC_ALARM_IC_MASK                    0x7
#define RTC_ALARM_IC_SHIFT                   0
#define CAP_LPSD_FILTER_ADDR                 IO_CFG4//0x01A
#define CAP_LPSD_FILTER_MASK                 0x1
#define CAP_LPSD_FILTER_SHIFT                5
#define RTC_ALARM_FILTER_ADDR                IO_CFG4
#define RTC_ALARM_FILTER_MASK                0x1
#define RTC_ALARM_FILTER_SHIFT               4
#define SRCLK_EN_FILTER_ADDR                 IO_CFG4
#define SRCLK_EN_FILTER_MASK                 0x1
#define SRCLK_EN_FILTER_SHIFT                3
#define WDT_RSTB_FILTER_ADDR                 IO_CFG4
#define WDT_RSTB_FILTER_MASK                 0x1
#define WDT_RSTB_FILTER_SHIFT                2
#define I2C_CLK_FILTER_ADDR                  IO_CFG4
#define I2C_CLK_FILTER_MASK                  0x1
#define I2C_CLK_FILTER_SHIFT                 1
#define I2C_DATA_FILTER_ADDR                 IO_CFG4
#define I2C_DATA_FILTER_MASK                 0x1
#define I2C_DATA_FILTER_SHIFT                0
#define CAP_LPSD_RCSEL_ADDR                  IO_CFG5//0x01C
#define CAP_LPSD_RCSEL_MASK                  0x1
#define CAP_LPSD_RCSEL_SHIFT                 5
#define RTC_ALARM_RCSEL_ADDR                 IO_CFG5
#define RTC_ALARM_RCSEL_MASK                 0x1
#define RTC_ALARM_RCSEL_SHIFT                4
#define SRCLK_EN_RCSEL_ADDR                  IO_CFG5
#define SRCLK_EN_RCSEL_MASK                  0x1
#define SRCLK_EN_RCSEL_SHIFT                 3
#define WDT_RSTB_RCSEL_ADDR                  IO_CFG5
#define WDT_RSTB_RCSEL_MASK                  0x1
#define WDT_RSTB_RCSEL_SHIFT                 2
#define I2C_CLK_RCSEL_ADDR                   IO_CFG5
#define I2C_CLK_RCSEL_MASK                   0x1
#define I2C_CLK_RCSEL_SHIFT                  1
#define I2C_DATA_RCSEL_ADDR                  IO_CFG5
#define I2C_DATA_RCSEL_MASK                  0x1
#define I2C_DATA_RCSEL_SHIFT                 0
#define RESERVE_ADDR                         CFG_RESERVE//0x01E
#define RESERVE_MASK                         0xFF
#define RESERVE_SHIFT                        0
#define VRF_STATE_RST2NORM_ADDR              PMU_PROT
#define VRF_STATE_RST2NORM_MASK              0x1
#define VRF_STATE_RST2NORM_SHIFT             15
#define VDD33_STATE_RST2NORM_ADDR            PMU_PROT
#define VDD33_STATE_RST2NORM_MASK            0x1
#define VDD33_STATE_RST2NORM_SHIFT           14
#define VIO18_STATE_RST2NORM_ADDR            PMU_PROT
#define VIO18_STATE_RST2NORM_MASK            0x1
#define VIO18_STATE_RST2NORM_SHIFT           13
#define VCORE_STATE_RST2NORM_ADDR            PMU_PROT
#define VCORE_STATE_RST2NORM_MASK            0x1
#define VCORE_STATE_RST2NORM_SHIFT           12
#define SLEEP_SEQ_STATE_RST2NORM_ADDR        PMU_PROT
#define SLEEP_SEQ_STATE_RST2NORM_MASK        0x1
#define SLEEP_SEQ_STATE_RST2NORM_SHIFT       11
#define PWR_SEQ_STATE_RST2NORM_ADDR          PMU_PROT
#define PWR_SEQ_STATE_RST2NORM_MASK          0x1
#define PWR_SEQ_STATE_RST2NORM_SHIFT         10
#define PWR_STATE_RST2NORM_ADDR              PMU_PROT
#define PWR_STATE_RST2NORM_MASK              0x1
#define PWR_STATE_RST2NORM_SHIFT             9
#define OC_PROT_DEB_TIME_ADDR                PMU_PROT
#define OC_PROT_DEB_TIME_MASK                0x1F
#define OC_PROT_DEB_TIME_SHIFT               4
#define OFF2IDLE_RG_RESET_EN_ADDR            PMU_PROT
#define OFF2IDLE_RG_RESET_EN_MASK            0x1
#define OFF2IDLE_RG_RESET_EN_SHIFT           2
#define OFF_PROT_EN_CHGFLO_B_ADDR            PMU_PROT
#define OFF_PROT_EN_CHGFLO_B_MASK            0x1
#define OFF_PROT_EN_CHGFLO_B_SHIFT           1
#define OFF_PROT_EN_CHG_PLUG_ADDR            PMU_PROT
#define OFF_PROT_EN_CHG_PLUG_MASK            0x1
#define OFF_PROT_EN_CHG_PLUG_SHIFT           0
#define ALL_PWR_STATE_RST2NORM_ADDR          PMU_RESET0
#define ALL_PWR_STATE_RST2NORM_MASK          0x1
#define ALL_PWR_STATE_RST2NORM_SHIFT         1
#define PMU_RG_RST_ADDR                      PMU_RESET0
#define PMU_RG_RST_MASK                      0x1
#define PMU_RG_RST_SHIFT                     0


#define INTCLK_BUCK_EN_LV_ADDR               BUCK_CON0//0x100
#define INTCLK_BUCK_EN_LV_MASK               0x1
#define INTCLK_BUCK_EN_LV_SHIFT              15
#define BUCK_FREQ_LV_ADDR                    BUCK_CON0
#define BUCK_FREQ_LV_MASK                    0x3
#define BUCK_FREQ_LV_SHIFT                   13
#define OSC_FREQK_LV_ADDR                    BUCK_CON0
#define OSC_FREQK_LV_MASK                    0x7
#define OSC_FREQK_LV_SHIFT                   10
#define BUCK_MODE_LV_ADDR                    BUCK_CON0
#define BUCK_MODE_LV_MASK                    0x1
#define BUCK_MODE_LV_SHIFT                   9
#define ZC_DIS_LV_ADDR                       BUCK_CON0
#define ZC_DIS_LV_MASK                       0x1
#define ZC_DIS_LV_SHIFT                      8
#define PFM_ICT_SHORT_LV_ADDR                BUCK_CON0
#define PFM_ICT_SHORT_LV_MASK                0x1
#define PFM_ICT_SHORT_LV_SHIFT               7
#define PFM_DECI_ICT_LV_ADDR                 BUCK_CON0
#define PFM_DECI_ICT_LV_MASK                 0x3
#define PFM_DECI_ICT_LV_SHIFT                4
#define LV_PFM_SLEEP_EN_ADDR                 BUCK_CON0
#define LV_PFM_SLEEP_EN_MASK                 0x1
#define LV_PFM_SLEEP_EN_SHIFT                3
#define BUCKLV_INT_IB_EN_ADDR                BUCK_CON0
#define BUCKLV_INT_IB_EN_MASK                0x1
#define BUCKLV_INT_IB_EN_SHIFT               2
#define BUCK_DISQ_RSEL_LV_ADDR               BUCK_CON0
#define BUCK_DISQ_RSEL_LV_MASK               0x1
#define BUCK_DISQ_RSEL_LV_SHIFT              0
#define BGSEL_LV_ADDR                        BUCK_CON1//0x102
#define BGSEL_LV_MASK                        0x3
#define BGSEL_LV_SHIFT                       14
#define BYPASS_BUCK_LV_ADDR                  BUCK_CON1
#define BYPASS_BUCK_LV_MASK                  0x1
#define BYPASS_BUCK_LV_SHIFT                 13
#define LOWVREF_EN_LV_ADDR                   BUCK_CON1
#define LOWVREF_EN_LV_MASK                   0x1
#define LOWVREF_EN_LV_SHIFT                  12
#define INTBG_SEL_LV_ADDR                    BUCK_CON1
#define INTBG_SEL_LV_MASK                    0x1
#define INTBG_SEL_LV_SHIFT                   11
#define RAMP_TUNE_LV_ADDR                    BUCK_CON1
#define RAMP_TUNE_LV_MASK                    0x3
#define RAMP_TUNE_LV_SHIFT                   9
#define COUT_LV_SEL_ADDR                     BUCK_CON1
#define COUT_LV_SEL_MASK                     0x7
#define COUT_LV_SEL_SHIFT                    6
#define RAMP_TUNE_I_LV_ADDR                  BUCK_CON1
#define RAMP_TUNE_I_LV_MASK                  0x7
#define RAMP_TUNE_I_LV_SHIFT                 3
#define IFB_CTRL_LV_ADDR                     BUCK_CON1
#define IFB_CTRL_LV_MASK                     0x7
#define IFB_CTRL_LV_SHIFT                    0
#define BUCK_VSEL_LV_ADDR                    BUCK_CON2//0x104
#define BUCK_VSEL_LV_MASK                    0x7F
#define BUCK_VSEL_LV_SHIFT                   0
#define INTCLK_BUCK_EN_MV_ADDR               BUCK_CON3//0x106
#define INTCLK_BUCK_EN_MV_MASK               0x1
#define INTCLK_BUCK_EN_MV_SHIFT              15
#define BUCK_FREQ_MV_ADDR                    BUCK_CON3
#define BUCK_FREQ_MV_MASK                    0x3
#define BUCK_FREQ_MV_SHIFT                   13
#define OSC_FREQK_MV_ADDR                    BUCK_CON3
#define OSC_FREQK_MV_MASK                    0x7
#define OSC_FREQK_MV_SHIFT                   10
#define BUCK_MODE_MV_ADDR                    BUCK_CON3
#define BUCK_MODE_MV_MASK                    0x1
#define BUCK_MODE_MV_SHIFT                   9
#define ZC_DIS_MV_ADDR                       BUCK_CON3
#define ZC_DIS_MV_MASK                       0x1
#define ZC_DIS_MV_SHIFT                      8
#define PFM_ICT_SHORT_MV_ADDR                BUCK_CON3
#define PFM_ICT_SHORT_MV_MASK                0x1
#define PFM_ICT_SHORT_MV_SHIFT               7
#define PFM_DECI_ICT_MV_ADDR                 BUCK_CON3
#define PFM_DECI_ICT_MV_MASK                 0x3
#define PFM_DECI_ICT_MV_SHIFT                4
#define MV_PFM_SLEEP_EN_ADDR                 BUCK_CON3
#define MV_PFM_SLEEP_EN_MASK                 0x1
#define MV_PFM_SLEEP_EN_SHIFT                3
#define BUCKMV_INT_IB_EN_ADDR                BUCK_CON3
#define BUCKMV_INT_IB_EN_MASK                0x1
#define BUCKMV_INT_IB_EN_SHIFT               2
#define BUCK_DISQ_RSEL_MV_ADDR               BUCK_CON3
#define BUCK_DISQ_RSEL_MV_MASK               0x1
#define BUCK_DISQ_RSEL_MV_SHIFT              0
#define BGSEL_MV_ADDR                        BUCK_CON4//0x108
#define BGSEL_MV_MASK                        0x3
#define BGSEL_MV_SHIFT                       14
#define BYPASS_BUCK_MV_ADDR                  BUCK_CON4
#define BYPASS_BUCK_MV_MASK                  0x1
#define BYPASS_BUCK_MV_SHIFT                 13
#define LOWVREF_EN_MV_ADDR                   BUCK_CON4
#define LOWVREF_EN_MV_MASK                   0x1
#define LOWVREF_EN_MV_SHIFT                  12
#define INTBG_SEL_MV_ADDR                    BUCK_CON4
#define INTBG_SEL_MV_MASK                    0x1
#define INTBG_SEL_MV_SHIFT                   11
#define RAMP_TUNE_MV_ADDR                    BUCK_CON4
#define RAMP_TUNE_MV_MASK                    0x3
#define RAMP_TUNE_MV_SHIFT                   9
#define COUT_MV_SEL_ADDR                     BUCK_CON4
#define COUT_MV_SEL_MASK                     0x7
#define COUT_MV_SEL_SHIFT                    6
#define RAMP_TUNE_I_MV_ADDR                  BUCK_CON4
#define RAMP_TUNE_I_MV_MASK                  0x7
#define RAMP_TUNE_I_MV_SHIFT                 3
#define IFB_CTRL_MV_ADDR                     BUCK_CON4
#define IFB_CTRL_MV_MASK                     0x7
#define IFB_CTRL_MV_SHIFT                    0
#define MV_STB_SEL_ADDR                      BUCK_CON5//0x10A
#define MV_STB_SEL_MASK                      0x1F
#define MV_STB_SEL_SHIFT                     8
#define BUCK_VSEL_MV_ADDR                    BUCK_CON5
#define BUCK_VSEL_MV_MASK                    0xFF
#define BUCK_VSEL_MV_SHIFT                   0
#define BUCK_LV_RVD_ADDR                     BUCK_CON6//0x10C
#define BUCK_LV_RVD_MASK                     0xFF
#define BUCK_LV_RVD_SHIFT                    8
#define BUCK_MV_RVD_ADDR                     BUCK_CON6
#define BUCK_MV_RVD_MASK                     0xFF
#define BUCK_MV_RVD_SHIFT                    0
#define BUCK_LV_NORM_FORCE_ON_ADDR           BUCK_CON7//0x10E
#define BUCK_LV_NORM_FORCE_ON_MASK           0x1
#define BUCK_LV_NORM_FORCE_ON_SHIFT          15
#define BUCK_LV_NORM_FORCE_OFF_ADDR          BUCK_CON7
#define BUCK_LV_NORM_FORCE_OFF_MASK          0x1
#define BUCK_LV_NORM_FORCE_OFF_SHIFT         14
#define BUCK_LV_RET_FORCE_ON_ADDR            BUCK_CON7
#define BUCK_LV_RET_FORCE_ON_MASK            0x1
#define BUCK_LV_RET_FORCE_ON_SHIFT           13
#define BUCK_LV_RET_FORCE_OFF_ADDR           BUCK_CON7
#define BUCK_LV_RET_FORCE_OFF_MASK           0x1
#define BUCK_LV_RET_FORCE_OFF_SHIFT          12
#define BUCK_LVOUTSEL_LV_OFF_ADDR            BUCK_CON7
#define BUCK_LVOUTSEL_LV_OFF_MASK            0x1
#define BUCK_LVOUTSEL_LV_OFF_SHIFT           10
#define BUCK_LVOUTSEL_LV_RET_ADDR            BUCK_CON7
#define BUCK_LVOUTSEL_LV_RET_MASK            0x1
#define BUCK_LVOUTSEL_LV_RET_SHIFT           9
#define BUCK_LVOUTSEL_LV_NORM_ADDR           BUCK_CON7
#define BUCK_LVOUTSEL_LV_NORM_MASK           0x1
#define BUCK_LVOUTSEL_LV_NORM_SHIFT          8

#define BUCK_DISQ_LV_OFF_E2_ADDR             BUCK_CON7
#define BUCK_DISQ_LV_OFF_E2_MASK             0x1
#define BUCK_DISQ_LV_OFF_E2_SHIFT            6
#define BUCK_DISQ_LV_RET_E2_ADDR             BUCK_CON7
#define BUCK_DISQ_LV_RET_E2_MASK             0x1
#define BUCK_DISQ_LV_RET_E2_SHIFT            5
#define BUCK_DISQ_LV_NORM_E2_ADDR            BUCK_CON7
#define BUCK_DISQ_LV_NORM_E2_MASK            0x1
#define BUCK_DISQ_LV_NORM_E2_SHIFT           4

#define BUCK_LPM_EN_LV_OFF_ADDR              BUCK_CON7
#define BUCK_LPM_EN_LV_OFF_MASK              0x1
#define BUCK_LPM_EN_LV_OFF_SHIFT             2
#define BUCK_LPM_EN_LV_RET_ADDR              BUCK_CON7
#define BUCK_LPM_EN_LV_RET_MASK              0x1
#define BUCK_LPM_EN_LV_RET_SHIFT             1
#define BUCK_LPM_EN_LV_NORM_ADDR             BUCK_CON7
#define BUCK_LPM_EN_LV_NORM_MASK             0x1
#define BUCK_LPM_EN_LV_NORM_SHIFT            0
#define BUCK_MV_NORM_FORCE_ON_ADDR           BUCK_CON8//0x110
#define BUCK_MV_NORM_FORCE_ON_MASK           0x1
#define BUCK_MV_NORM_FORCE_ON_SHIFT          15
#define BUCK_MV_NORM_FORCE_OFF_ADDR          BUCK_CON8
#define BUCK_MV_NORM_FORCE_OFF_MASK          0x1
#define BUCK_MV_NORM_FORCE_OFF_SHIFT         14
#define BUCK_MV_RET_FORCE_ON_ADDR            BUCK_CON8
#define BUCK_MV_RET_FORCE_ON_MASK            0x1
#define BUCK_MV_RET_FORCE_ON_SHIFT           13
#define BUCK_MV_RET_FORCE_OFF_ADDR           BUCK_CON8
#define BUCK_MV_RET_FORCE_OFF_MASK           0x1
#define BUCK_MV_RET_FORCE_OFF_SHIFT          12
#define BUCK_MV_NM2RET_TIME_SEL_ADDR         BUCK_CON8
#define BUCK_MV_NM2RET_TIME_SEL_MASK         0x3
#define BUCK_MV_NM2RET_TIME_SEL_SHIFT        11
#define BUCK_MV_RET2NM_TIME_SEL_ADDR         BUCK_CON8
#define BUCK_MV_RET2NM_TIME_SEL_MASK         0x3
#define BUCK_MV_RET2NM_TIME_SEL_SHIFT        8

#define BUCK_DISQ_MV_OFF_E2_ADDR             BUCK_CON8
#define BUCK_DISQ_MV_OFF_E2_MASK             0x1
#define BUCK_DISQ_MV_OFF_E2_SHIFT            6
#define BUCK_DISQ_MV_RET_E2_ADDR             BUCK_CON8
#define BUCK_DISQ_MV_RET_E2_MASK             0x1
#define BUCK_DISQ_MV_RET_E2_SHIFT            5
#define BUCK_DISQ_MV_NORM_E2_ADDR            BUCK_CON8
#define BUCK_DISQ_MV_NORM_E2_MASK            0x1
#define BUCK_DISQ_MV_NORM_E2_SHIFT           4

#define BUCK_LPM_EN_MV_OFF_ADDR              BUCK_CON8
#define BUCK_LPM_EN_MV_OFF_MASK              0x1
#define BUCK_LPM_EN_MV_OFF_SHIFT             2
#define BUCK_LPM_EN_MV_RET_ADDR              BUCK_CON8
#define BUCK_LPM_EN_MV_RET_MASK              0x1
#define BUCK_LPM_EN_MV_RET_SHIFT             1
#define BUCK_LPM_EN_MV_NORM_ADDR             BUCK_CON8
#define BUCK_LPM_EN_MV_NORM_MASK             0x1
#define BUCK_LPM_EN_MV_NORM_SHIFT            0
#define VCORE_STATE_ADDR                     BUCK_CON9//0x112
#define VCORE_STATE_MASK                     0x1F
#define VCORE_STATE_SHIFT                    8
#define VIO_STATE_ADDR                       BUCK_CON9
#define VIO_STATE_MASK                       0x1F
#define VIO_STATE_SHIFT                      0
#define BUCK_DISQ_DELAY_SEL_LV_ADDR          BUCK_CON10//0x114
#define BUCK_DISQ_DELAY_SEL_LV_MASK          0x3
#define BUCK_DISQ_DELAY_SEL_LV_SHIFT         12
#define BUCK_DISQ_LV_OFF_ADDR                BUCK_CON10
#define BUCK_DISQ_LV_OFF_MASK                0x1
#define BUCK_DISQ_LV_OFF_SHIFT               10
#define BUCK_DISQ_LV_RET_ADDR                BUCK_CON10
#define BUCK_DISQ_LV_RET_MASK                0x1
#define BUCK_DISQ_LV_RET_SHIFT               9
#define BUCK_DISQ_LV_NORM_ADDR               BUCK_CON10
#define BUCK_DISQ_LV_NORM_MASK               0x1
#define BUCK_DISQ_LV_NORM_SHIFT              8
#define BUCK_DISQ_DELAY_SEL_MV_ADDR          BUCK_CON10
#define BUCK_DISQ_DELAY_SEL_MV_MASK          0x3
#define BUCK_DISQ_DELAY_SEL_MV_SHIFT         4
#define BUCK_DISQ_MV_OFF_ADDR                BUCK_CON10
#define BUCK_DISQ_MV_OFF_MASK                0x1
#define BUCK_DISQ_MV_OFF_SHIFT               2
#define BUCK_DISQ_MV_RET_ADDR                BUCK_CON10
#define BUCK_DISQ_MV_RET_MASK                0x1
#define BUCK_DISQ_MV_RET_SHIFT               1
#define BUCK_DISQ_MV_NORM_ADDR               BUCK_CON10
#define BUCK_DISQ_MV_NORM_MASK               0x1
#define BUCK_DISQ_MV_NORM_SHIFT              0

#define VDD33_NORM_FORCE_ON_ADDR             LDO_CON0//0x200
#define VDD33_NORM_FORCE_ON_MASK             0x1
#define VDD33_NORM_FORCE_ON_SHIFT            15
#define VDD33_NORM_FORCE_OFF_ADDR            LDO_CON0
#define VDD33_NORM_FORCE_OFF_MASK            0x1
#define VDD33_NORM_FORCE_OFF_SHIFT           14
#define HV_LOWI_ADDR                         LDO_CON0
#define HV_LOWI_MASK                         0x1
#define HV_LOWI_SHIFT                        13
#define VLDO33_NDIS_ENB_OFF_ADDR             LDO_CON0
#define VLDO33_NDIS_ENB_OFF_MASK             0x1
#define VLDO33_NDIS_ENB_OFF_SHIFT            12
#define VLDO33_NDIS_ENB_RET_ADDR             LDO_CON0
#define VLDO33_NDIS_ENB_RET_MASK             0x1
#define VLDO33_NDIS_ENB_RET_SHIFT            11
#define VLDO33_NDIS_ENB_NORM_ADDR            LDO_CON0
#define VLDO33_NDIS_ENB_NORM_MASK            0x1
#define VLDO33_NDIS_ENB_NORM_SHIFT           10

#define VLDO33_CLAMP_EN_E2_ADDR              LDO_CON0
#define VLDO33_CLAMP_EN_E2_MASK              0x1
#define VLDO33_CLAMP_EN_E2_SHIFT             9

#define REGHV_SEL_NM_ADDR                    LDO_CON0
#define REGHV_SEL_NM_MASK                    0xFF
#define REGHV_SEL_NM_SHIFT                   0
#define VLDO33_CLAMP_EN_ADDR                 LDO_CON1//0x202
#define VLDO33_CLAMP_EN_MASK                 0x1
#define VLDO33_CLAMP_EN_SHIFT                15
#define VDD33_RAMP_PERIOD_ADDR               LDO_CON1
#define VDD33_RAMP_PERIOD_MASK               0x3
#define VDD33_RAMP_PERIOD_SHIFT              13
#define VDD33_RAMP_UNIT_ADDR                 LDO_CON1
#define VDD33_RAMP_UNIT_MASK                 0x7
#define VDD33_RAMP_UNIT_SHIFT                10
#define VDD33_RAMP_UP_DIS_ADDR               LDO_CON1
#define VDD33_RAMP_UP_DIS_MASK               0x1
#define VDD33_RAMP_UP_DIS_SHIFT              9
#define VDD33_RAMP_DOWN_DIS_ADDR             LDO_CON1
#define VDD33_RAMP_DOWN_DIS_MASK             0x1
#define VDD33_RAMP_DOWN_DIS_SHIFT            8
#define REGHV_SEL_RET_ADDR                   LDO_CON1
#define REGHV_SEL_RET_MASK                   0xFF
#define REGHV_SEL_RET_SHIFT                  0
#define VDD33_RET_FORCE_ON_ADDR              LDO_CON2//0x204
#define VDD33_RET_FORCE_ON_MASK              0x1
#define VDD33_RET_FORCE_ON_SHIFT             15
#define VDD33_RET_FORCE_OFF_ADDR             LDO_CON2
#define VDD33_RET_FORCE_OFF_MASK             0x1
#define VDD33_RET_FORCE_OFF_SHIFT            14
#define VDD33_RET_SLEEP_OFF_ADDR             LDO_CON2
#define VDD33_RET_SLEEP_OFF_MASK             0x1
#define VDD33_RET_SLEEP_OFF_SHIFT            13
#define HVSTBSEL_ADDR                        LDO_CON2
#define HVSTBSEL_MASK                        0x3F
#define HVSTBSEL_SHIFT                       0
#define VRF_NORM_FORCE_ON_ADDR               LDO_CON3//0x206
#define VRF_NORM_FORCE_ON_MASK               0x1
#define VRF_NORM_FORCE_ON_SHIFT              15
#define VRF_NORM_FORCE_OFF_ADDR              LDO_CON3
#define VRF_NORM_FORCE_OFF_MASK              0x1
#define VRF_NORM_FORCE_OFF_SHIFT             14
#define LV2_LOWI_ADDR                        LDO_CON3
#define LV2_LOWI_MASK                        0x1
#define LV2_LOWI_SHIFT                       13
#define VRF11_NDIS_ENB_OFF_ADDR              LDO_CON3
#define VRF11_NDIS_ENB_OFF_MASK              0x1
#define VRF11_NDIS_ENB_OFF_SHIFT             12
#define VRF11_NDIS_ENB_RET_ADDR              LDO_CON3
#define VRF11_NDIS_ENB_RET_MASK              0x1
#define VRF11_NDIS_ENB_RET_SHIFT             11
#define VRF11_NDIS_ENB_NORM_ADDR             LDO_CON3
#define VRF11_NDIS_ENB_NORM_MASK             0x1
#define VRF11_NDIS_ENB_NORM_SHIFT            10
#define REGLV2_SEL_NM_ADDR                   LDO_CON3
#define REGLV2_SEL_NM_MASK                   0x7F
#define REGLV2_SEL_NM_SHIFT                  0
#define VRF_RAMP_PERIOD_ADDR                 LDO_CON4//0x208
#define VRF_RAMP_PERIOD_MASK                 0x3
#define VRF_RAMP_PERIOD_SHIFT                13
#define VRF_RAMP_UNIT_ADDR                   LDO_CON4
#define VRF_RAMP_UNIT_MASK                   0x7
#define VRF_RAMP_UNIT_SHIFT                  10
#define VRF_RAMP_UP_DIS_ADDR                 LDO_CON4
#define VRF_RAMP_UP_DIS_MASK                 0x1
#define VRF_RAMP_UP_DIS_SHIFT                9
#define VRF_RAMP_DOWN_DIS_ADDR               LDO_CON4
#define VRF_RAMP_DOWN_DIS_MASK               0x1
#define VRF_RAMP_DOWN_DIS_SHIFT              8
#define REGLV2_SEL_RET_ADDR                  LDO_CON4
#define REGLV2_SEL_RET_MASK                  0x7F
#define REGLV2_SEL_RET_SHIFT                 0
#define VRF_RET_FORCE_ON_ADDR                LDO_CON5//0x20A
#define VRF_RET_FORCE_ON_MASK                0x1
#define VRF_RET_FORCE_ON_SHIFT               15
#define VRF_RET_FORCE_OFF_ADDR               LDO_CON5
#define VRF_RET_FORCE_OFF_MASK               0x1
#define VRF_RET_FORCE_OFF_SHIFT              14
#define VRF_RET_SLEEP_OFF_ADDR               LDO_CON5
#define VRF_RET_SLEEP_OFF_MASK               0x1
#define VRF_RET_SLEEP_OFF_SHIFT              13
#define LV3_STB_REGSEL_ADDR                  LDO_CON5
#define LV3_STB_REGSEL_MASK                  0x1F
#define LV3_STB_REGSEL_SHIFT                 0
#define VDIG18_NDIS_ENB_ADDR                 LDO_CON6//0x20C
#define VDIG18_NDIS_ENB_MASK                 0x1
#define VDIG18_NDIS_ENB_SHIFT                14
#define VDIG18_SEL_ADDR                      LDO_CON6
#define VDIG18_SEL_MASK                      0x1F
#define VDIG18_SEL_SHIFT                     0
#define VDD33_STATE_ADDR                     LDO_CON7//0x20E
#define VDD33_STATE_MASK                     0x1F
#define VDD33_STATE_SHIFT                    8
#define VRF_STATE_ADDR                       LDO_CON7
#define VRF_STATE_MASK                       0x1F
#define VRF_STATE_SHIFT                      0


#define TRICKLE_ERR_EN_ADDR                  CHARGER_TH0//0x300
#define TRICKLE_ERR_EN_MASK                  0x1
#define TRICKLE_ERR_EN_SHIFT                 15
#define TRICKLE_CL_EN_ADDR                   CHARGER_TH0
#define TRICKLE_CL_EN_MASK                   0x1
#define TRICKLE_CL_EN_SHIFT                  14
#define TRICKLE_CV_EN_ADDR                   CHARGER_TH0
#define TRICKLE_CV_EN_MASK                   0x1
#define TRICKLE_CV_EN_SHIFT                  13
#define FULL_BAT_THRESHOLD2_ADDR             CHARGER_TH0
#define FULL_BAT_THRESHOLD2_MASK             0x3FF
#define FULL_BAT_THRESHOLD2_SHIFT            0
#define CC1_ERR_EN_ADDR                      CHARGER_TH1//0x302
#define CC1_ERR_EN_MASK                      0x1
#define CC1_ERR_EN_SHIFT                     15
#define CC1_CL_EN_ADDR                       CHARGER_TH1
#define CC1_CL_EN_MASK                       0x1
#define CC1_CL_EN_SHIFT                      14
#define CC1_CV_EN_ADDR                       CHARGER_TH1
#define CC1_CV_EN_MASK                       0x1
#define CC1_CV_EN_SHIFT                      13
#define CC1_THRESHOLD_ADDR                   CHARGER_TH1
#define CC1_THRESHOLD_MASK                   0x3FF
#define CC1_THRESHOLD_SHIFT                  0
#define CC2_ERR_EN_ADDR                      CHARGER_TH2//0x304
#define CC2_ERR_EN_MASK                      0x1
#define CC2_ERR_EN_SHIFT                     15
#define CC2_CL_EN_ADDR                       CHARGER_TH2
#define CC2_CL_EN_MASK                       0x1
#define CC2_CL_EN_SHIFT                      14
#define CC2_CV_EN_ADDR                       CHARGER_TH2
#define CC2_CV_EN_MASK                       0x1
#define CC2_CV_EN_SHIFT                      13
#define CC2_THRESHOLD_ADDR                   CHARGER_TH2
#define CC2_THRESHOLD_MASK                   0x3FF
#define CC2_THRESHOLD_SHIFT                  0
#define CV_INIT_ERR_EN_ADDR                  CHARGER_TH3//0x306
#define CV_INIT_ERR_EN_MASK                  0x1
#define CV_INIT_ERR_EN_SHIFT                 15
#define CV_INIT_CL_EN_ADDR                   CHARGER_TH3
#define CV_INIT_CL_EN_MASK                   0x1
#define CV_INIT_CL_EN_SHIFT                  14
#define CV_INIT_CV_EN_ADDR                   CHARGER_TH3
#define CV_INIT_CV_EN_MASK                   0x1
#define CV_INIT_CV_EN_SHIFT                  13
#define CV_STOP_CURRENT_ADDR                 CHARGER_TH3
#define CV_STOP_CURRENT_MASK                 0x3FF
#define CV_STOP_CURRENT_SHIFT                0
#define CV_ERR_EN_ADDR                       CHARGER_TH4//0x308
#define CV_ERR_EN_MASK                       0x1
#define CV_ERR_EN_SHIFT                      15
#define CV_CL_EN_ADDR                        CHARGER_TH4
#define CV_CL_EN_MASK                        0x1
#define CV_CL_EN_SHIFT                       14
#define CV_CV_EN_ADDR                        CHARGER_TH4
#define CV_CV_EN_MASK                        0x1
#define CV_CV_EN_SHIFT                       13
#define CV_THRESHOLD_ADDR                    CHARGER_TH4
#define CV_THRESHOLD_MASK                    0x3FF
#define CV_THRESHOLD_SHIFT                   0
#define FULL_ERR_EN_ADDR                     CHARGER_TH5//0x30A
#define FULL_ERR_EN_MASK                     0x1
#define FULL_ERR_EN_SHIFT                    15
#define FULL_CL_EN_ADDR                      CHARGER_TH5
#define FULL_CL_EN_MASK                      0x1
#define FULL_CL_EN_SHIFT                     14
#define FULL_CV_EN_ADDR                      CHARGER_TH5
#define FULL_CV_EN_MASK                      0x1
#define FULL_CV_EN_SHIFT                     13
#define FULL_BAT_THRESHOLD1_ADDR             CHARGER_TH5
#define FULL_BAT_THRESHOLD1_MASK             0x3FF
#define FULL_BAT_THRESHOLD1_SHIFT            0
#define RECHARGE_ERR_EN_ADDR                 CHARGER_TH6//0x30C
#define RECHARGE_ERR_EN_MASK                 0x1
#define RECHARGE_ERR_EN_SHIFT                15
#define RECHARGE_CL_EN_ADDR                  CHARGER_TH6
#define RECHARGE_CL_EN_MASK                  0x1
#define RECHARGE_CL_EN_SHIFT                 14
#define RECHARGE_CV_EN_ADDR                  CHARGER_TH6
#define RECHARGE_CV_EN_MASK                  0x1
#define RECHARGE_CV_EN_SHIFT                 13
#define RECHARGE_THRESHOLD_ADDR              CHARGER_TH6
#define RECHARGE_THRESHOLD_MASK              0x3FF
#define RECHARGE_THRESHOLD_SHIFT             0
#define TRICKLE_DAC_OUT_UPDATE_ADDR          CHARGER_DAC0//0x30E
#define TRICKLE_DAC_OUT_UPDATE_MASK          0x1
#define TRICKLE_DAC_OUT_UPDATE_SHIFT         15
#define TRICKLE_DAC_VALUE_ADDR               CHARGER_DAC0
#define TRICKLE_DAC_VALUE_MASK               0x3FF
#define TRICKLE_DAC_VALUE_SHIFT              0
#define CC1_DAC_OUT_UPDATE_ADDR              CHARGER_DAC1//0x310
#define CC1_DAC_OUT_UPDATE_MASK              0x1
#define CC1_DAC_OUT_UPDATE_SHIFT             15
#define CC1_DAC_RAMP_UP_WAIT_RSEL_ADDR       CHARGER_DAC1
#define CC1_DAC_RAMP_UP_WAIT_RSEL_MASK       0x1
#define CC1_DAC_RAMP_UP_WAIT_RSEL_SHIFT      14
#define CC1_DAC_RAMP_DOWN_WAIT_RSEL_ADDR     CHARGER_DAC1
#define CC1_DAC_RAMP_DOWN_WAIT_RSEL_MASK     0x1
#define CC1_DAC_RAMP_DOWN_WAIT_RSEL_SHIFT    13
#define CC1_DAC_RAMP_STEP_ADDR               CHARGER_DAC1
#define CC1_DAC_RAMP_STEP_MASK               0x7
#define CC1_DAC_RAMP_STEP_SHIFT              10
#define CC1_DAC_VALUE_ADDR                   CHARGER_DAC1
#define CC1_DAC_VALUE_MASK                   0x3FF
#define CC1_DAC_VALUE_SHIFT                  0
#define CC2_DAC_OUT_UPDATE_ADDR              CHARGER_DAC2//0x312
#define CC2_DAC_OUT_UPDATE_MASK              0x1
#define CC2_DAC_OUT_UPDATE_SHIFT             15
#define CC2_DAC_RAMP_UP_WAIT_RSEL_ADDR       CHARGER_DAC2
#define CC2_DAC_RAMP_UP_WAIT_RSEL_MASK       0x1
#define CC2_DAC_RAMP_UP_WAIT_RSEL_SHIFT      14
#define CC2_DAC_RAMP_DOWN_WAIT_RSEL_ADDR     CHARGER_DAC2
#define CC2_DAC_RAMP_DOWN_WAIT_RSEL_MASK     0x1
#define CC2_DAC_RAMP_DOWN_WAIT_RSEL_SHIFT    13
#define CC2_DAC_RAMP_STEP_ADDR               CHARGER_DAC2
#define CC2_DAC_RAMP_STEP_MASK               0x7
#define CC2_DAC_RAMP_STEP_SHIFT              10
#define CC2_DAC_VALUE_ADDR                   CHARGER_DAC2
#define CC2_DAC_VALUE_MASK                   0x3FF
#define CC2_DAC_VALUE_SHIFT                  0
#define CV_DAC_OUT_UPDATE_ADDR               CHARGER_DAC3//0x314
#define CV_DAC_OUT_UPDATE_MASK               0x1
#define CV_DAC_OUT_UPDATE_SHIFT              15
#define CV_DAC_RAMP_UP_WAIT_RSEL_ADDR        CHARGER_DAC3
#define CV_DAC_RAMP_UP_WAIT_RSEL_MASK        0x1
#define CV_DAC_RAMP_UP_WAIT_RSEL_SHIFT       14
#define CV_DAC_RAMP_DOWN_WAIT_RSEL_ADDR      CHARGER_DAC3
#define CV_DAC_RAMP_DOWN_WAIT_RSEL_MASK      0x1
#define CV_DAC_RAMP_DOWN_WAIT_RSEL_SHIFT     13
#define CV_DAC_RAMP_STEP_ADDR                CHARGER_DAC3
#define CV_DAC_RAMP_STEP_MASK                0x7
#define CV_DAC_RAMP_STEP_SHIFT               10
#define CV_DAC_VALUE_ADDR                    CHARGER_DAC3
#define CV_DAC_VALUE_MASK                    0x3FF
#define CV_DAC_VALUE_SHIFT                   0
#define TRICKLE_RCHG_SEL_UPDATE_ADDR         CHARGER_RSEL0//0x316
#define TRICKLE_RCHG_SEL_UPDATE_MASK         0x1
#define TRICKLE_RCHG_SEL_UPDATE_SHIFT        15
#define TRICKLE_RCHG_SEL_ADDR                CHARGER_RSEL0
#define TRICKLE_RCHG_SEL_MASK                0x3FF
#define TRICKLE_RCHG_SEL_SHIFT               0
#define CC1_RCHG_SEL_UPDATE_ADDR             CHARGER_RSEL1//0x318
#define CC1_RCHG_SEL_UPDATE_MASK             0x1
#define CC1_RCHG_SEL_UPDATE_SHIFT            15
#define CC1_RCHG_RAMP_UP_WAIT_DAC_ADDR       CHARGER_RSEL1
#define CC1_RCHG_RAMP_UP_WAIT_DAC_MASK       0x1
#define CC1_RCHG_RAMP_UP_WAIT_DAC_SHIFT      14
#define CC1_RCHG_RAMP_DOWN_WAIT_DAC_ADDR     CHARGER_RSEL1
#define CC1_RCHG_RAMP_DOWN_WAIT_DAC_MASK     0x1
#define CC1_RCHG_RAMP_DOWN_WAIT_DAC_SHIFT    13
#define CC1_RCHG_SEL_RAMP_STEP_ADDR          CHARGER_RSEL1
#define CC1_RCHG_SEL_RAMP_STEP_MASK          0x7
#define CC1_RCHG_SEL_RAMP_STEP_SHIFT         10
#define CC1_RCHG_SEL_ADDR                    CHARGER_RSEL1
#define CC1_RCHG_SEL_MASK                    0x3FF
#define CC1_RCHG_SEL_SHIFT                   0
#define CC2_RCHG_SEL_UPDATE_ADDR             CHARGER_RSEL2//0x31A
#define CC2_RCHG_SEL_UPDATE_MASK             0x1
#define CC2_RCHG_SEL_UPDATE_SHIFT            15
#define CC2_RCHG_RAMP_UP_WAIT_DAC_ADDR       CHARGER_RSEL2
#define CC2_RCHG_RAMP_UP_WAIT_DAC_MASK       0x1
#define CC2_RCHG_RAMP_UP_WAIT_DAC_SHIFT      14
#define CC2_RCHG_RAMP_DOWN_WAIT_DAC_ADDR     CHARGER_RSEL2
#define CC2_RCHG_RAMP_DOWN_WAIT_DAC_MASK     0x1
#define CC2_RCHG_RAMP_DOWN_WAIT_DAC_SHIFT    13
#define CC2_RCHG_SEL_RAMP_STEP_ADDR          CHARGER_RSEL2
#define CC2_RCHG_SEL_RAMP_STEP_MASK          0x7
#define CC2_RCHG_SEL_RAMP_STEP_SHIFT         10
#define CC2_RCHG_SEL_ADDR                    CHARGER_RSEL2
#define CC2_RCHG_SEL_MASK                    0x3FF
#define CC2_RCHG_SEL_SHIFT                   0
#define CV_RCHG_SEL_UPDATE_ADDR              CHARGER_RSEL3//0x31C
#define CV_RCHG_SEL_UPDATE_MASK              0x1
#define CV_RCHG_SEL_UPDATE_SHIFT             15
#define CV_RCHG_RAMP_UP_WAIT_DAC_ADDR        CHARGER_RSEL3
#define CV_RCHG_RAMP_UP_WAIT_DAC_MASK        0x1
#define CV_RCHG_RAMP_UP_WAIT_DAC_SHIFT       14
#define CV_RCHG_RAMP_DOWN_WAIT_DAC_ADDR      CHARGER_RSEL3
#define CV_RCHG_RAMP_DOWN_WAIT_DAC_MASK      0x1
#define CV_RCHG_RAMP_DOWN_WAIT_DAC_SHIFT     13
#define CV_RCHG_SEL_RAMP_STEP_ADDR           CHARGER_RSEL3
#define CV_RCHG_SEL_RAMP_STEP_MASK           0x7
#define CV_RCHG_SEL_RAMP_STEP_SHIFT          10
#define CV_RCHG_SEL_ADDR                     CHARGER_RSEL3
#define CV_RCHG_SEL_MASK                     0x3FF
#define CV_RCHG_SEL_SHIFT                    0
#define CC2_EN_ADDR                          CHARGER_CON0//0x31E
#define CC2_EN_MASK                          0x1
#define CC2_EN_SHIFT                         15
#define RECHARGE_CC2_SEL_ADDR                CHARGER_CON0
#define RECHARGE_CC2_SEL_MASK                0x1
#define RECHARGE_CC2_SEL_SHIFT               14
#define CV_INIT_TIME_SEL_ADDR                CHARGER_CON0
#define CV_INIT_TIME_SEL_MASK                0x3
#define CV_INIT_TIME_SEL_SHIFT               12
#define CHG_COMPLETE_CHK_NUM2_ADDR           CHARGER_CON0
#define CHG_COMPLETE_CHK_NUM2_MASK           0xF
#define CHG_COMPLETE_CHK_NUM2_SHIFT          8
#define BYP_CV_CHK_ICHG_ADDR                 CHARGER_CON0
#define BYP_CV_CHK_ICHG_MASK                 0x1
#define BYP_CV_CHK_ICHG_SHIFT                7
#define BYP_CV_CHK_VBAT_ADDR                 CHARGER_CON0
#define BYP_CV_CHK_VBAT_MASK                 0x1
#define BYP_CV_CHK_VBAT_SHIFT                6
#define CHG_COMPLETE_CHK_NUM_ADDR            CHARGER_CON0
#define CHG_COMPLETE_CHK_NUM_MASK            0x3F
#define CHG_COMPLETE_CHK_NUM_SHIFT           0
#define END_OF_CHG_EN_ADDR                   CHARGER_CON1//0x320
#define END_OF_CHG_EN_MASK                   0x1
#define END_OF_CHG_EN_SHIFT                  12
#define CHG_OUT_DEB_SEL_ADDR                 CHARGER_CON1
#define CHG_OUT_DEB_SEL_MASK                 0x3
#define CHG_OUT_DEB_SEL_SHIFT                10
#define CHG_IN_DEB_SEL_ADDR                  CHARGER_CON1
#define CHG_IN_DEB_SEL_MASK                  0x3
#define CHG_IN_DEB_SEL_SHIFT                 8
#define CHG_RECHG_INT_EN_ADDR                CHARGER_CON1
#define CHG_RECHG_INT_EN_MASK                0x1
#define CHG_RECHG_INT_EN_SHIFT               7
#define CHG_RECHG_INT_FLAG_ADDR              CHARGER_CON1
#define CHG_RECHG_INT_FLAG_MASK              0x1
#define CHG_RECHG_INT_FLAG_SHIFT             6
#define CHG_COMPLETE_INT_EN_ADDR             CHARGER_CON1
#define CHG_COMPLETE_INT_EN_MASK             0x1
#define CHG_COMPLETE_INT_EN_SHIFT            5
#define CHG_COMPLETE_INT_FLAG_ADDR           CHARGER_CON1
#define CHG_COMPLETE_INT_FLAG_MASK           0x1
#define CHG_COMPLETE_INT_FLAG_SHIFT          4
#define CHG_OUT_INT_EN_ADDR                  CHARGER_CON1
#define CHG_OUT_INT_EN_MASK                  0x1
#define CHG_OUT_INT_EN_SHIFT                 3
#define CHG_OUT_INT_FLAG_ADDR                CHARGER_CON1
#define CHG_OUT_INT_FLAG_MASK                0x1
#define CHG_OUT_INT_FLAG_SHIFT               2
#define CHG_IN_INT_EN_ADDR                   CHARGER_CON1
#define CHG_IN_INT_EN_MASK                   0x1
#define CHG_IN_INT_EN_SHIFT                  1
#define CHG_IN_INT_FLAG_ADDR                 CHARGER_CON1
#define CHG_IN_INT_FLAG_MASK                 0x1
#define CHG_IN_INT_FLAG_SHIFT                0
#define RSEL_READY_ADDR                      CHARGER_CON2//0x322
#define RSEL_READY_MASK                      0x1
#define RSEL_READY_SHIFT                     15
#define DAC_READY_ADDR                       CHARGER_CON2
#define DAC_READY_MASK                       0x1
#define DAC_READY_SHIFT                      14
#define CHG_STATE_ADDR                       CHARGER_CON2
#define CHG_STATE_MASK                       0x7
#define CHG_STATE_SHIFT                      11
#define CHG_LPM_SW_FORCE_ADDR                CHARGER_CON2
#define CHG_LPM_SW_FORCE_MASK                0x1
#define CHG_LPM_SW_FORCE_SHIFT               10
#define CHG_LPM_FORCE_ADDR                   CHARGER_CON2
#define CHG_LPM_FORCE_MASK                   0x1
#define CHG_LPM_FORCE_SHIFT                  9
#define CHG_FORCE_MODE_ADDR                  CHARGER_CON2
#define CHG_FORCE_MODE_MASK                  0x1
#define CHG_FORCE_MODE_SHIFT                 8
#define CHG_FORCE_RECHARGE_ADDR              CHARGER_CON2
#define CHG_FORCE_RECHARGE_MASK              0x1
#define CHG_FORCE_RECHARGE_SHIFT             7
#define CHG_FORCE_COMPLETE_ADDR              CHARGER_CON2
#define CHG_FORCE_COMPLETE_MASK              0x1
#define CHG_FORCE_COMPLETE_SHIFT             6
#define CHG_FORCE_CV_ADDR                    CHARGER_CON2
#define CHG_FORCE_CV_MASK                    0x1
#define CHG_FORCE_CV_SHIFT                   5
#define CHG_FORCE_CC2_ADDR                   CHARGER_CON2
#define CHG_FORCE_CC2_MASK                   0x1
#define CHG_FORCE_CC2_SHIFT                  4
#define CHG_FORCE_CC1_ADDR                   CHARGER_CON2
#define CHG_FORCE_CC1_MASK                   0x1
#define CHG_FORCE_CC1_SHIFT                  3
#define CHG_FORCE_TRICKLE_ADDR               CHARGER_CON2
#define CHG_FORCE_TRICKLE_MASK               0x1
#define CHG_FORCE_TRICKLE_SHIFT              2
#define CHG_FORCE_ON_ADDR                    CHARGER_CON2
#define CHG_FORCE_ON_MASK                    0x1
#define CHG_FORCE_ON_SHIFT                   1
#define CHG_FORCE_OFF_ADDR                   CHARGER_CON2
#define CHG_FORCE_OFF_MASK                   0x1
#define CHG_FORCE_OFF_SHIFT                  0
#define CL_SEL_ADDR                          CHARGER_CON3//0x324
#define CL_SEL_MASK                          0x1
#define CL_SEL_SHIFT                         15
#define CHG_LDO_SEL_ADDR                     CHARGER_CON3
#define CHG_LDO_SEL_MASK                     0x7
#define CHG_LDO_SEL_SHIFT                    12
#define VCL_SEL_ADDR                         CHARGER_CON3
#define VCL_SEL_MASK                         0x3
#define VCL_SEL_SHIFT                        10
#define BG_CHG_SEL_ADDR                      CHARGER_CON3
#define BG_CHG_SEL_MASK                      0x3
#define BG_CHG_SEL_SHIFT                     8
#define I_LIM_TRIM_ADDR                      CHARGER_CON3
#define I_LIM_TRIM_MASK                      0x7
#define I_LIM_TRIM_SHIFT                     4
#define BG_TRIM_LPM_ADDR                     CHARGER_CON3
#define BG_TRIM_LPM_MASK                     0x7
#define BG_TRIM_LPM_SHIFT                    0
#define CHG_DAC_BGSEL_ADDR                   CHARGER_CON4//0x328
#define CHG_DAC_BGSEL_MASK                   0x1
#define CHG_DAC_BGSEL_SHIFT                  15
#define CHG_I_LIM_ENB_ADDR                   CHARGER_CON4
#define CHG_I_LIM_ENB_MASK                   0x1
#define CHG_I_LIM_ENB_SHIFT                  14
#define REVIVING_EN_ADDR                     CHARGER_CON4
#define REVIVING_EN_MASK                     0x1
#define REVIVING_EN_SHIFT                    13
#define SAT_EN_ADDR                          CHARGER_CON4
#define SAT_EN_MASK                          0x1
#define SAT_EN_SHIFT                         12
#define SW_OC_LMT_ADDR                       CHARGER_CON4
#define SW_OC_LMT_MASK                       0xF
#define SW_OC_LMT_SHIFT                      8
#define SW_OCP_ENB_ADDR                      CHARGER_CON4
#define SW_OCP_ENB_MASK                      0x1
#define SW_OCP_ENB_SHIFT                     7
#define CHGDET_BAT_SYS_LPMT_1V8_ADDR         CHARGER_CON4
#define CHGDET_BAT_SYS_LPMT_1V8_MASK         0x7
#define CHGDET_BAT_SYS_LPMT_1V8_SHIFT        4
#define CHGDET_BAT_SYS_OFFSET_1V8_ADDR       CHARGER_CON4
#define CHGDET_BAT_SYS_OFFSET_1V8_MASK       0xF
#define CHGDET_BAT_SYS_OFFSET_1V8_SHIFT      0
#define VREF_BUFFER_EN_1V8_ADDR              CHARGER_CON5//0x32A
#define VREF_BUFFER_EN_1V8_MASK              0x1
#define VREF_BUFFER_EN_1V8_SHIFT             15
#define MCOMP_EN_1V8_ADDR                    CHARGER_CON5
#define MCOMP_EN_1V8_MASK                    0x1
#define MCOMP_EN_1V8_SHIFT                   14
#define MD_SEL_1V8_ADDR                      CHARGER_CON5
#define MD_SEL_1V8_MASK                      0x1
#define MD_SEL_1V8_SHIFT                     13
#define OCP_STRP_1V8_ADDR                    CHARGER_CON5
#define OCP_STRP_1V8_MASK                    0x1
#define OCP_STRP_1V8_SHIFT                   12
#define VCHG_5V_ADJ_1V8_ADDR                 CHARGER_CON5
#define VCHG_5V_ADJ_1V8_MASK                 0x1
#define VCHG_5V_ADJ_1V8_SHIFT                11
#define CC_LOOP_TUNE_1V8_ADDR                CHARGER_CON5
#define CC_LOOP_TUNE_1V8_MASK                0x7
#define CC_LOOP_TUNE_1V8_SHIFT               8
#define CHGDET_BAT_SYS_FORCE_EN_1V8_ADDR     CHARGER_CON5
#define CHGDET_BAT_SYS_FORCE_EN_1V8_MASK     0x1
#define CHGDET_BAT_SYS_FORCE_EN_1V8_SHIFT    7
#define CHGDET_CHG_SYS_LPMT_1V8_ADDR         CHARGER_CON5
#define CHGDET_CHG_SYS_LPMT_1V8_MASK         0x7
#define CHGDET_CHG_SYS_LPMT_1V8_SHIFT        4
#define CHGDET_BAT_SYS_LPM_EN_1V8_ADDR       CHARGER_CON5
#define CHGDET_BAT_SYS_LPM_EN_1V8_MASK       0x1
#define CHGDET_BAT_SYS_LPM_EN_1V8_SHIFT      3
#define CHGDET_CHG_BAT_LPMT_1V8_ADDR         CHARGER_CON5
#define CHGDET_CHG_BAT_LPMT_1V8_MASK         0x7
#define CHGDET_CHG_BAT_LPMT_1V8_SHIFT        0


#define ADC_INBUF_BYPASS_ADDR                ADC_CON0//0x400
#define ADC_INBUF_BYPASS_MASK                0x1
#define ADC_INBUF_BYPASS_SHIFT               15
#define ADC_CT_ADDR                          ADC_CON0
#define ADC_CT_MASK                          0x3
#define ADC_CT_SHIFT                         12
#define REGPMUTSEL_ADDR                      ADC_CON0
#define REGPMUTSEL_MASK                      0x3
#define REGPMUTSEL_SHIFT                     8
#define VCAL_CTRL_ADDR                       ADC_CON0
#define VCAL_CTRL_MASK                       0x7
#define VCAL_CTRL_SHIFT                      4
#define VDIV_CTRL_ADDR                       ADC_CON0
#define VDIV_CTRL_MASK                       0x3
#define VDIV_CTRL_SHIFT                      0
#define ADC_AVG5_ADDR                        ADC_CON1//0x402
#define ADC_AVG5_MASK                        0x3
#define ADC_AVG5_SHIFT                       10
#define ADC_AVG4_ADDR                        ADC_CON1
#define ADC_AVG4_MASK                        0x3
#define ADC_AVG4_SHIFT                       8
#define ADC_AVG3_ADDR                        ADC_CON1
#define ADC_AVG3_MASK                        0x3
#define ADC_AVG3_SHIFT                       6
#define ADC_AVG2_ADDR                        ADC_CON1
#define ADC_AVG2_MASK                        0x3
#define ADC_AVG2_SHIFT                       4
#define ADC_AVG1_ADDR                        ADC_CON1
#define ADC_AVG1_MASK                        0x3
#define ADC_AVG1_SHIFT                       2
#define ADC_AVG0_ADDR                        ADC_CON1
#define ADC_AVG0_MASK                        0x3
#define ADC_AVG0_SHIFT                       0
#define ADC_EN_ADDR                          ADC_CON2//0x404
#define ADC_EN_MASK                          0x1
#define ADC_EN_SHIFT                         15
#define ADC_CH_EN_SW_MODE_ADDR               ADC_CON2
#define ADC_CH_EN_SW_MODE_MASK               0x1
#define ADC_CH_EN_SW_MODE_SHIFT              14
#define ADC_COMP_INVERT_ADDR                 ADC_CON2
#define ADC_COMP_INVERT_MASK                 0x1
#define ADC_COMP_INVERT_SHIFT                13
#define ADC_VALUE_INVERT_ADDR                ADC_CON2
#define ADC_VALUE_INVERT_MASK                0x1
#define ADC_VALUE_INVERT_SHIFT               12
#define ADC_ON_DLY_ADDR                      ADC_CON2
#define ADC_ON_DLY_MASK                      0x3
#define ADC_ON_DLY_SHIFT                     10
#define ADC_SH_DLY_ADDR                      ADC_CON2
#define ADC_SH_DLY_MASK                      0x3
#define ADC_SH_DLY_SHIFT                     8
#define ADC_TIMER_ADDR                       ADC_CON2
#define ADC_TIMER_MASK                       0xFF
#define ADC_TIMER_SHIFT                      0
#define ADC_CH_EN_ADDR                       ADC_CON3//0x406
#define ADC_CH_EN_MASK                       0x3F
#define ADC_CH_EN_SHIFT                      5
#define ADC_HW_IRQ_EN_ADDR                   ADC_CON3
#define ADC_HW_IRQ_EN_MASK                   0x1
#define ADC_HW_IRQ_EN_SHIFT                  4
#define ADC_HW_TRIG_FLAG_ADDR                ADC_CON3
#define ADC_HW_TRIG_FLAG_MASK                0x1
#define ADC_HW_TRIG_FLAG_SHIFT               3
#define ADC_SW_IRQ_EN_ADDR                   ADC_CON3
#define ADC_SW_IRQ_EN_MASK                   0x1
#define ADC_SW_IRQ_EN_SHIFT                  2
#define ADC_SW_TRIG_FLAG_ADDR                ADC_CON3
#define ADC_SW_TRIG_FLAG_MASK                0x1
#define ADC_SW_TRIG_FLAG_SHIFT               1
#define ADC_ONE_SHOT_START_ADDR              ADC_CON3
#define ADC_ONE_SHOT_START_MASK              0x1
#define ADC_ONE_SHOT_START_SHIFT             0
#define ADC_FORCE_MODE_ADDR                  ADC_CON4//0x408
#define ADC_FORCE_MODE_MASK                  0x1
#define ADC_FORCE_MODE_SHIFT                 15
#define ADC_ANALOG_EN_FORCE_ADDR             ADC_CON4
#define ADC_ANALOG_EN_FORCE_MASK             0x1
#define ADC_ANALOG_EN_FORCE_SHIFT            14
#define ADC_VBAT_SCAL_EN_FORCE_ADDR          ADC_CON4
#define ADC_VBAT_SCAL_EN_FORCE_MASK          0x1
#define ADC_VBAT_SCAL_EN_FORCE_SHIFT         13
#define ADC_VIN_SCAL_EN_FORCE_ADDR           ADC_CON4
#define ADC_VIN_SCAL_EN_FORCE_MASK           0x1
#define ADC_VIN_SCAL_EN_FORCE_SHIFT          12
#define ADC_AUTOZERO_FORCE_ADDR              ADC_CON4
#define ADC_AUTOZERO_FORCE_MASK              0x1
#define ADC_AUTOZERO_FORCE_SHIFT             11
#define ADC_CH_SEL_FORCE_ADDR                ADC_CON4
#define ADC_CH_SEL_FORCE_MASK                0x3F
#define ADC_CH_SEL_FORCE_SHIFT               0
#define ADC_SAR_OUT_FORCE_ADDR               ADC_CON5//0x40A
#define ADC_SAR_OUT_FORCE_MASK               0x3FF
#define ADC_SAR_OUT_FORCE_SHIFT              0
#define ADC_RDY_STS0_ADDR                    ADC_DATA0//0x40
#define ADC_RDY_STS0_MASK                    0x1
#define ADC_RDY_STS0_SHIFT                   15
#define ADC_VALUE0_ADDR                      ADC_DATA0
#define ADC_VALUE0_MASK                      0x3FF
#define ADC_VALUE0_SHIFT                     0
#define ADC_RDY_STS1_ADDR                    ADC_DATA1//0x40E
#define ADC_RDY_STS1_MASK                    0x1
#define ADC_RDY_STS1_SHIFT                   15
#define ADC_VALUE1_ADDR                      ADC_DATA1
#define ADC_VALUE1_MASK                      0x3FF
#define ADC_VALUE1_SHIFT                     0
#define ADC_RDY_STS2_ADDR                    ADC_DATA2//0x410
#define ADC_RDY_STS2_MASK                    0x1
#define ADC_RDY_STS2_SHIFT                   15
#define ADC_VALUE2_ADDR                      ADC_DATA2
#define ADC_VALUE2_MASK                      0x3FF
#define ADC_VALUE2_SHIFT                     0
#define ADC_RDY_STS3_ADDR                    ADC_DATA3//0x412
#define ADC_RDY_STS3_MASK                    0x1
#define ADC_RDY_STS3_SHIFT                   15
#define ADC_VALUE3_ADDR                      ADC_DATA3
#define ADC_VALUE3_MASK                      0x3FF
#define ADC_VALUE3_SHIFT                     0
#define ADC_RDY_STS4_ADDR                    ADC_DATA4//0x414
#define ADC_RDY_STS4_MASK                    0x1
#define ADC_RDY_STS4_SHIFT                   15
#define ADC_VALUE4_ADDR                      ADC_DATA4
#define ADC_VALUE4_MASK                      0x3FF
#define ADC_VALUE4_SHIFT                     0
#define ADC_RDY_STS5_ADDR                    ADC_DATA5//0x416
#define ADC_RDY_STS5_MASK                    0x1
#define ADC_RDY_STS5_SHIFT                   15
#define ADC_VALUE5_ADDR                      ADC_DATA5
#define ADC_VALUE5_MASK                      0x3FF
#define ADC_VALUE5_SHIFT                     0
#define ADC_STATE_ADDR                       ADC_STATE0//0x418
#define ADC_STATE_MASK                       0xF
#define ADC_STATE_SHIFT                      2
#define SAR_STATE_ADDR                       ADC_STATE0
#define SAR_STATE_MASK                       0x3
#define SAR_STATE_SHIFT                      0


#define LED1_EN_SYS_SW_ADDR                  LED_EN_CTRL//0x500
#define LED1_EN_SYS_SW_MASK                  0x1
#define LED1_EN_SYS_SW_SHIFT                 9
#define LED0_EN_SYS_SW_ADDR                  LED_EN_CTRL
#define LED0_EN_SYS_SW_MASK                  0x1
#define LED0_EN_SYS_SW_SHIFT                 8
#define LED1_EN_ADDR                         LED_EN_CTRL
#define LED1_EN_MASK                         0x1
#define LED1_EN_SHIFT                        1
#define LED0_EN_ADDR                         LED_EN_CTRL
#define LED0_EN_MASK                         0x1
#define LED0_EN_SHIFT                        0
#define LED0_RES_SEL_ADDR                    LED0_CON0//0x502
#define LED0_RES_SEL_MASK                    0x3
#define LED0_RES_SEL_SHIFT                   8
#define LED0_INVERT_ADDR                     LED0_CON0
#define LED0_INVERT_MASK                     0x1
#define LED0_INVERT_SHIFT                    5
#define LED0_REPEAT_ADDR                     LED0_CON0
#define LED0_REPEAT_MASK                     0x1
#define LED0_REPEAT_SHIFT                    4
#define LED0_T1T2_REPEAT_ADDR                LED0_CON0
#define LED0_T1T2_REPEAT_MASK                0xF
#define LED0_T1T2_REPEAT_SHIFT               0
#define LED0_XN_ADDR                         LED0_UNIT//0x504
#define LED0_XN_MASK                         0x3
#define LED0_XN_SHIFT                        8
#define LED0_UNIT_ADDR                       LED0_UNIT
#define LED0_UNIT_MASK                       0xFF
#define LED0_UNIT_SHIFT                      0
#define LED0_T0_ADDR                         LED0_PERIOD0//0x506
#define LED0_T0_MASK                         0xFF
#define LED0_T0_SHIFT                        8
#define LED0_T1_ADDR                         LED0_PERIOD0
#define LED0_T1_MASK                         0xFF
#define LED0_T1_SHIFT                        0
#define LED0_T2_ADDR                         LED0_PERIOD1//0x508
#define LED0_T2_MASK                         0xFF
#define LED0_T2_SHIFT                        8
#define LED0_T3_ADDR                         LED0_PERIOD1
#define LED0_T3_MASK                         0xFF
#define LED0_T3_SHIFT                        0
#define LED0_PWM_LOAD_EN_ADDR                LED0_PWM0//0x50A
#define LED0_PWM_LOAD_EN_MASK                0x1
#define LED0_PWM_LOAD_EN_SHIFT               0
#define LED0_PWM_PERIOD_ADDR                 LED0_PWM1//0x50C
#define LED0_PWM_PERIOD_MASK                 0xFF
#define LED0_PWM_PERIOD_SHIFT                8
#define LED0_PWM_DURATION_ADDR               LED0_PWM1
#define LED0_PWM_DURATION_MASK               0xFF
#define LED0_PWM_DURATION_SHIFT              0
#define LED0_PWM_OFFSTEP_ADDR                LED0_PWM2//0x50E
#define LED0_PWM_OFFSTEP_MASK                0xFF
#define LED0_PWM_OFFSTEP_SHIFT               8
#define LED0_PWM_ONSTEP_ADDR                 LED0_PWM2
#define LED0_PWM_ONSTEP_MASK                 0xFF
#define LED0_PWM_ONSTEP_SHIFT                0
#define LED1_RES_SEL_ADDR                    LED1_CON0//0x510
#define LED1_RES_SEL_MASK                    0x3
#define LED1_RES_SEL_SHIFT                   8
#define LED1_INVERT_ADDR                     LED1_CON0
#define LED1_INVERT_MASK                     0x1
#define LED1_INVERT_SHIFT                    5
#define LED1_REPEAT_ADDR                     LED1_CON0
#define LED1_REPEAT_MASK                     0x1
#define LED1_REPEAT_SHIFT                    4
#define LED1_T1T2_REPEAT_ADDR                LED1_CON0
#define LED1_T1T2_REPEAT_MASK                0xF
#define LED1_T1T2_REPEAT_SHIFT               0
#define LED1_XN_ADDR                         LED1_UNIT//0x512
#define LED1_XN_MASK                         0x3
#define LED1_XN_SHIFT                        8
#define LED1_UNIT_ADDR                       LED1_UNIT
#define LED1_UNIT_MASK                       0xFF
#define LED1_UNIT_SHIFT                      0
#define LED1_T0_ADDR                         LED1_PERIOD0//0x514
#define LED1_T0_MASK                         0xFF
#define LED1_T0_SHIFT                        8
#define LED1_T1_ADDR                         LED1_PERIOD0
#define LED1_T1_MASK                         0xFF
#define LED1_T1_SHIFT                        0
#define LED1_T2_ADDR                         LED1_PERIOD1//0x516
#define LED1_T2_MASK                         0xFF
#define LED1_T2_SHIFT                        8
#define LED1_T3_ADDR                         LED1_PERIOD1
#define LED1_T3_MASK                         0xFF
#define LED1_T3_SHIFT                        0
#define LED1_PWM_LOAD_EN_ADDR                LED1_PWM0//0x518
#define LED1_PWM_LOAD_EN_MASK                0x1
#define LED1_PWM_LOAD_EN_SHIFT               0
#define LED1_PWM_PERIOD_ADDR                 LED1_PWM1//0x51A
#define LED1_PWM_PERIOD_MASK                 0xFF
#define LED1_PWM_PERIOD_SHIFT                8
#define LED1_PWM_DURATION_ADDR               LED1_PWM1
#define LED1_PWM_DURATION_MASK               0xFF
#define LED1_PWM_DURATION_SHIFT              0
#define LED1_PWM_OFFSTEP_ADDR                LED1_PWM2//0x51C
#define LED1_PWM_OFFSTEP_MASK                0xFF
#define LED1_PWM_OFFSTEP_SHIFT               8
#define LED1_PWM_ONSTEP_ADDR                 LED1_PWM2
#define LED1_PWM_ONSTEP_MASK                 0xFF
#define LED1_PWM_ONSTEP_SHIFT                0


#define PMU_REG_AUTOREST_DIS_ADDR            PMU_TEST0//0x600
#define PMU_REG_AUTOREST_DIS_MASK            0x1
#define PMU_REG_AUTOREST_DIS_SHIFT           12
#define VIO_ISO_FORCE_DISABLE_ADDR           PMU_TEST0
#define VIO_ISO_FORCE_DISABLE_MASK           0x1
#define VIO_ISO_FORCE_DISABLE_SHIFT          11
#define VIO_ISO_FORCE_CLEAR_ADDR             PMU_TEST0
#define VIO_ISO_FORCE_CLEAR_MASK             0x1
#define VIO_ISO_FORCE_CLEAR_SHIFT            10
#define VDIG_ISO_FORCE_DISABLE_ADDR          PMU_TEST0
#define VDIG_ISO_FORCE_DISABLE_MASK          0x1
#define VDIG_ISO_FORCE_DISABLE_SHIFT         9
#define VDIG_ISO_FORCE_CLEAR_ADDR            PMU_TEST0
#define VDIG_ISO_FORCE_CLEAR_MASK            0x1
#define VDIG_ISO_FORCE_CLEAR_SHIFT           8
#define AD_WDT_RSTB_SW_MODE_ADDR             PMU_TEST0
#define AD_WDT_RSTB_SW_MODE_MASK             0x1
#define AD_WDT_RSTB_SW_MODE_SHIFT            7
#define AD_WDT_RSTB_ADDR                     PMU_TEST0
#define AD_WDT_RSTB_MASK                     0x1
#define AD_WDT_RSTB_SHIFT                    6
#define AD_SRCLK_EN_SW_MODE_ADDR             PMU_TEST0
#define AD_SRCLK_EN_SW_MODE_MASK             0x1
#define AD_SRCLK_EN_SW_MODE_SHIFT            5
#define AD_SRCLK_EN_ADDR                     PMU_TEST0
#define AD_SRCLK_EN_MASK                     0x1
#define AD_SRCLK_EN_SHIFT                    4
#define AD_CAP_LPSD_SW_MODE_ADDR             PMU_TEST0
#define AD_CAP_LPSD_SW_MODE_MASK             0x1
#define AD_CAP_LPSD_SW_MODE_SHIFT            3
#define AD_CAP_LPSD_ADDR                     PMU_TEST0
#define AD_CAP_LPSD_MASK                     0x1
#define AD_CAP_LPSD_SHIFT                    2
#define AD_RTC_ALARM_SW_MODE_ADDR            PMU_TEST0
#define AD_RTC_ALARM_SW_MODE_MASK            0x1
#define AD_RTC_ALARM_SW_MODE_SHIFT           1
#define AD_RTC_ALARM_ADDR                    PMU_TEST0
#define AD_RTC_ALARM_MASK                    0x1
#define AD_RTC_ALARM_SHIFT                   0
#define LED1_DBG_OUT_SEL_ADDR                PMU_TEST1
#define LED1_DBG_OUT_SEL_MASK                0x1F
#define LED1_DBG_OUT_SEL_SHIFT               9
#define LED1_DBG_OUT_EN_ADDR                 PMU_TEST1
#define LED1_DBG_OUT_EN_MASK                 0x1
#define LED1_DBG_OUT_EN_SHIFT                8
#define LED0_DBG_OUT_SEL_ADDR                PMU_TEST1
#define LED0_DBG_OUT_SEL_MASK                0x1F
#define LED0_DBG_OUT_SEL_SHIFT               1
#define LED0_DBG_OUT_EN_ADDR                 PMU_TEST1
#define LED0_DBG_OUT_EN_MASK                 0x1
#define LED0_DBG_OUT_EN_SHIFT                0
#define DA_VCORE_NM_EN_ADDR                  PMU_TEST2
#define DA_VCORE_NM_EN_MASK                  0x1
#define DA_VCORE_NM_EN_SHIFT                 15
#define DA_VCORE_DISQ_ADDR                   PMU_TEST2
#define DA_VCORE_DISQ_MASK                   0x1
#define DA_VCORE_DISQ_SHIFT                  14
#define DA_VCORE_LPM_EN_ADDR                 PMU_TEST2
#define DA_VCORE_LPM_EN_MASK                 0x1
#define DA_VCORE_LPM_EN_SHIFT                13
#define DA_VCORE_OUTSEL_ADDR                 PMU_TEST2
#define DA_VCORE_OUTSEL_MASK                 0x1
#define DA_VCORE_OUTSEL_SHIFT                12
#define DA_VIO18_RET_EN_ADDR                 PMU_TEST2
#define DA_VIO18_RET_EN_MASK                 0x1
#define DA_VIO18_RET_EN_SHIFT                11
#define DA_VIO18_NM_EN_ADDR                  PMU_TEST2
#define DA_VIO18_NM_EN_MASK                  0x1
#define DA_VIO18_NM_EN_SHIFT                 10
#define DA_VIO18_DISQ_ADDR                   PMU_TEST2
#define DA_VIO18_DISQ_MASK                   0x1
#define DA_VIO18_DISQ_SHIFT                  9
#define DA_VIO18_LPM_EN_ADDR                 PMU_TEST2
#define DA_VIO18_LPM_EN_MASK                 0x1
#define DA_VIO18_LPM_EN_SHIFT                8
#define DA_VIO18_RDY_ADDR                    PMU_TEST2
#define DA_VIO18_RDY_MASK                    0x1
#define DA_VIO18_RDY_SHIFT                   7
#define DA_VDD33_RET_EN_ADDR                 PMU_TEST2
#define DA_VDD33_RET_EN_MASK                 0x1
#define DA_VDD33_RET_EN_SHIFT                6
#define DA_VDD33_NM_EN_ADDR                  PMU_TEST2
#define DA_VDD33_NM_EN_MASK                  0x1
#define DA_VDD33_NM_EN_SHIFT                 5
#define DA_VDD33_NDIS_ENB_ADDR               PMU_TEST2
#define DA_VDD33_NDIS_ENB_MASK               0x1
#define DA_VDD33_NDIS_ENB_SHIFT              4
#define DA_VRF_RET_EN_ADDR                   PMU_TEST2
#define DA_VRF_RET_EN_MASK                   0x1
#define DA_VRF_RET_EN_SHIFT                  3
#define DA_VRF_NM_EN_ADDR                    PMU_TEST2
#define DA_VRF_NM_EN_MASK                    0x1
#define DA_VRF_NM_EN_SHIFT                   2
#define DA_VRF_NDIS_ENB_ADDR                 PMU_TEST2
#define DA_VRF_NDIS_ENB_MASK                 0x1
#define DA_VRF_NDIS_ENB_SHIFT                1
#define DA_PORNDIG_DELAY_ADDR                PMU_TEST2
#define DA_PORNDIG_DELAY_MASK                0x1
#define DA_PORNDIG_DELAY_SHIFT               0
#define DA_OSC_EN_ADDR                       PMU_TEST3
#define DA_OSC_EN_MASK                       0x1
#define DA_OSC_EN_SHIFT                      15
#define DA_POR_N_ADDR                        PMU_TEST3
#define DA_POR_N_MASK                        0x1
#define DA_POR_N_SHIFT                       14
#define DA_PMIC_INT_ADDR                     PMU_TEST3
#define DA_PMIC_INT_MASK                     0x1
#define DA_PMIC_INT_SHIFT                    13
#define DA_PMU_LDO_EN_ADDR                   PMU_TEST3
#define DA_PMU_LDO_EN_MASK                   0x1
#define DA_PMU_LDO_EN_SHIFT                  12
#define DA_KEY_RST_ADDR                      PMU_TEST3
#define DA_KEY_RST_MASK                      0x1
#define DA_KEY_RST_SHIFT                     11
#define DA_PMU_NORMAL_MODE_ADDR              PMU_TEST3
#define DA_PMU_NORMAL_MODE_MASK              0x1
#define DA_PMU_NORMAL_MODE_SHIFT             10
#define AD_RTCALARM_SYNC_ADDR                PMU_TEST3
#define AD_RTCALARM_SYNC_MASK                0x1
#define AD_RTCALARM_SYNC_SHIFT               9
#define AD_RTCALARM_ADDR                     PMU_TEST3
#define AD_RTCALARM_MASK                     0x1
#define AD_RTCALARM_SHIFT                    8
#define AD_CAPLPSD_SYNC_ADDR                 PMU_TEST3
#define AD_CAPLPSD_SYNC_MASK                 0x1
#define AD_CAPLPSD_SYNC_SHIFT                7
#define AD_CAPLPSD_ADDR                      PMU_TEST3
#define AD_CAPLPSD_MASK                      0x1
#define AD_CAPLPSD_SHIFT                     6
#define AD_WDTRSTB_DEB_ADDR                  PMU_TEST3
#define AD_WDTRSTB_DEB_MASK                  0x1
#define AD_WDTRSTB_DEB_SHIFT                 5
#define AD_WDTRSTB_ADDR                      PMU_TEST3
#define AD_WDTRSTB_MASK                      0x1
#define AD_WDTRSTB_SHIFT                     4
#define AD_SYSRSTB_DEB_ADDR                  PMU_TEST3
#define AD_SYSRSTB_DEB_MASK                  0x1
#define AD_SYSRSTB_DEB_SHIFT                 3
#define AD_SYSRSTB_ADDR                      PMU_TEST3
#define AD_SYSRSTB_MASK                      0x1
#define AD_SYSRSTB_SHIFT                     2
#define AD_REGEN_DEB_ADDR                    PMU_TEST3
#define AD_REGEN_DEB_MASK                    0x1
#define AD_REGEN_DEB_SHIFT                   1
#define AD_REGEN_ADDR                        PMU_TEST3
#define AD_REGEN_MASK                        0x1
#define AD_REGEN_SHIFT                       0
#define AD_PMU_OC_STATUS_DEB_ADDR            PMU_TEST4
#define AD_PMU_OC_STATUS_DEB_MASK            0x1
#define AD_PMU_OC_STATUS_DEB_SHIFT           14
#define AD_PMU_OC_STATUS_ADDR                PMU_TEST4
#define AD_PMU_OC_STATUS_MASK                0x1
#define AD_PMU_OC_STATUS_SHIFT               13
#define AD_POR_N_VCORE_ADDR                  PMU_TEST4
#define AD_POR_N_VCORE_MASK                  0x1
#define AD_POR_N_VCORE_SHIFT                 12
#define AD_POR_N_VIO_ADDR                    PMU_TEST4
#define AD_POR_N_VIO_MASK                    0x1
#define AD_POR_N_VIO_SHIFT                   11
#define AD_UVLO_N_VSYS_ADDR                  PMU_TEST4
#define AD_UVLO_N_VSYS_MASK                  0x1
#define AD_UVLO_N_VSYS_SHIFT                 10
#define DA_CHG_DAC_OUT_ADDR                  PMU_TEST4
#define DA_CHG_DAC_OUT_MASK                  0x3FF
#define DA_CHG_DAC_OUT_SHIFT                 0
#define AD_ADC_COMP_OUT_ADDR                 PMU_TEST5
#define AD_ADC_COMP_OUT_MASK                 0x1
#define AD_ADC_COMP_OUT_SHIFT                14
#define AD_CHGFLO_B_DEB_ADDR                 PMU_TEST5
#define AD_CHGFLO_B_DEB_MASK                 0x1
#define AD_CHGFLO_B_DEB_SHIFT                13
#define AD_CHGFLO_B_ADDR                     PMU_TEST5
#define AD_CHGFLO_B_MASK                     0x1
#define AD_CHGFLO_B_SHIFT                    12
#define AD_CHG_PLUG_DEB_ADDR                 PMU_TEST5
#define AD_CHG_PLUG_DEB_MASK                 0x1
#define AD_CHG_PLUG_DEB_SHIFT                11
#define AD_CHG_PLUG_ADDR                     PMU_TEST5
#define AD_CHG_PLUG_MASK                     0x1
#define AD_CHG_PLUG_SHIFT                    10
#define DA_RCHG_SEL_ADDR                     PMU_TEST5
#define DA_RCHG_SEL_MASK                     0x3FF
#define DA_RCHG_SEL_SHIFT                    0

#define DA_VCORE_NM_EN_E2_ADDR               PMU_TEST1//0x602
#define DA_VCORE_NM_EN_E2_MASK               0x1
#define DA_VCORE_NM_EN_E2_SHIFT              14
#define DA_VIO18_RET_EN_E2_ADDR              PMU_TEST1
#define DA_VIO18_RET_EN_E2_MASK              0x1
#define DA_VIO18_RET_EN_E2_SHIFT             13
#define DA_VIO18_NM_EN_E2_ADDR               PMU_TEST1
#define DA_VIO18_NM_EN_E2_MASK               0x1
#define DA_VIO18_NM_EN_E2_SHIFT              12
#define DA_VDD33_RET_EN_E2_ADDR              PMU_TEST1
#define DA_VDD33_RET_EN_E2_MASK              0x1
#define DA_VDD33_RET_EN_E2_SHIFT             11
#define DA_VDD33_NM_EN_E2_ADDR               PMU_TEST1
#define DA_VDD33_NM_EN_E2_MASK               0x1
#define DA_VDD33_NM_EN_E2_SHIFT              10
#define DA_VRF_RET_EN_E2_ADDR                PMU_TEST1
#define DA_VRF_RET_EN_E2_MASK                0x1
#define DA_VRF_RET_EN_E2_SHIFT               9
#define DA_VRF_NM_EN_E2_ADDR                 PMU_TEST1
#define DA_VRF_NM_EN_E2_MASK                 0x1
#define DA_VRF_NM_EN_E2_SHIFT                8
#define DA_POR_N_E2_ADDR                     PMU_TEST1
#define DA_POR_N_E2_MASK                     0x1
#define DA_POR_N_E2_SHIFT                    7
#define DA_PMIC_INT_E2_ADDR                  PMU_TEST1
#define DA_PMIC_INT_E2_MASK                  0x1
#define DA_PMIC_INT_E2_SHIFT                 6
#define AD_PMU_OC_STATUS_E2_ADDR             PMU_TEST1
#define AD_PMU_OC_STATUS_E2_MASK             0x1
#define AD_PMU_OC_STATUS_E2_SHIFT            5
#define AD_POR_N_VCORE_E2_ADDR               PMU_TEST1
#define AD_POR_N_VCORE_E2_MASK               0x1
#define AD_POR_N_VCORE_E2_SHIFT              4
#define AD_POR_N_VIO_E2_ADDR                 PMU_TEST1
#define AD_POR_N_VIO_E2_MASK                 0x1
#define AD_POR_N_VIO_E2_SHIFT                3
#define AD_SYSRSTB_E2_ADDR                   PMU_TEST1
#define AD_SYSRSTB_E2_MASK                   0x1
#define AD_SYSRSTB_E2_SHIFT                  2
#define AD_REGEN_E2_ADDR                     PMU_TEST1
#define AD_REGEN_E2_MASK                     0x1
#define AD_REGEN_E2_SHIFT                    1
#define DA_OSC_EN_E2_ADDR                    PMU_TEST1
#define DA_OSC_EN_E2_MASK                    0x1
#define DA_OSC_EN_E2_SHIFT                   0
#define DA_PMU_LDO_EN_E2_ADDR                PMU_TEST2//0x604
#define DA_PMU_LDO_EN_E2_MASK                0x1
#define DA_PMU_LDO_EN_E2_SHIFT               8
#define DA_KEY_RST_E2_ADDR                   PMU_TEST2
#define DA_KEY_RST_E2_MASK                   0x1
#define DA_KEY_RST_E2_SHIFT                  7
#define DA_PMU_NORMAL_MODE_E2_ADDR           PMU_TEST2
#define DA_PMU_NORMAL_MODE_E2_MASK           0x1
#define DA_PMU_NORMAL_MODE_E2_SHIFT          6
#define DA_VIO18_RDY_E2_ADDR                 PMU_TEST2
#define DA_VIO18_RDY_E2_MASK                 0x1
#define DA_VIO18_RDY_E2_SHIFT                5
#define DA_PORNDIG_DELAY_E2_ADDR             PMU_TEST2
#define DA_PORNDIG_DELAY_E2_MASK             0x1
#define DA_PORNDIG_DELAY_E2_SHIFT            4
#define AD_UVLO_N_VSYS_E2_ADDR               PMU_TEST2
#define AD_UVLO_N_VSYS_E2_MASK               0x1
#define AD_UVLO_N_VSYS_E2_SHIFT              3
#define AD_ADC_COMP_OUT_E2_ADDR              PMU_TEST2
#define AD_ADC_COMP_OUT_E2_MASK              0x1
#define AD_ADC_COMP_OUT_E2_SHIFT             2
#define AD_CHGFLO_B_E2_ADDR                  PMU_TEST2
#define AD_CHGFLO_B_E2_MASK                  0x1
#define AD_CHGFLO_B_E2_SHIFT                 1
#define AD_CHG_PLUG_E2_ADDR                  PMU_TEST2
#define AD_CHG_PLUG_E2_MASK                  0x1
#define AD_CHG_PLUG_E2_SHIFT                 0
#endif /* _HAL_PMU_PLATFORM_H_ */

