/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */
 
 
VP_EVT_DEFINE( ZERO )						//0x00
VP_EVT_DEFINE( ONE )
VP_EVT_DEFINE( TWO )
VP_EVT_DEFINE( THREE )
VP_EVT_DEFINE( FOUR )
VP_EVT_DEFINE( FIVE )
VP_EVT_DEFINE( SIX )
VP_EVT_DEFINE( SEVEN )
VP_EVT_DEFINE( EIGHT )
VP_EVT_DEFINE( NINE )
VP_EVT_DEFINE( VOICE_PROMPT_LANG_CHANGE )
VP_EVT_DEFINE( VOICE_PROMPT_ON )
VP_EVT_DEFINE( VOICE_PROMPT_OFF )
VP_EVT_DEFINE( MULTI_POINT_MODE_ON )
VP_EVT_DEFINE( MULTI_POINT_MODE_OFF )
VP_EVT_DEFINE( MUTE_ON )
VP_EVT_DEFINE( MUTE_OFF )					//0x10
VP_EVT_DEFINE( POWER_ON )
VP_EVT_DEFINE( POWER_OFF )
VP_EVT_DEFINE( PAIRING )
VP_EVT_DEFINE( PAIRING_SUCCESSFUL )
VP_EVT_DEFINE( CONNECTED )
VP_EVT_DEFINE( SECOND_DEVICE_CONNECTED )
VP_EVT_DEFINE( DEVICE_DISCONNECTED )
VP_EVT_DEFINE( INCOMING_CALL )
VP_EVT_DEFINE( CALL_REJECTED )
VP_EVT_DEFINE( CALL_CANCELLED )
VP_EVT_DEFINE( CALL_ENDED )
VP_EVT_DEFINE( RE_DIALING )
VP_EVT_DEFINE( LOW_BATTERY )
VP_EVT_DEFINE( BATTERY_IS_HIGH )
VP_EVT_DEFINE( BATTERY_IS_MEDIAN )
VP_EVT_DEFINE( BATTERY_IS_LOW )				//0x20
VP_EVT_DEFINE( VOLUME_MAXIMUM )
VP_EVT_DEFINE( PAUSE )
VP_EVT_DEFINE( LINE_IN_MODE )
VP_EVT_DEFINE( BLUETOOTH_MODE )
VP_EVT_DEFINE( FM_MODE )
VP_EVT_DEFINE( SEEK_UP )
VP_EVT_DEFINE( SEEK_DOWN )
VP_EVT_DEFINE( LEFT_CHANNEL )
VP_EVT_DEFINE( RIGHT_CHANNEL )
VP_EVT_DEFINE( WHAT_CAN_I_SAY )
VP_EVT_DEFINE( CONNECTION_STATUS )
VP_EVT_DEFINE( CHECK_BATTERY )
VP_EVT_DEFINE( CANCEL )
VP_EVT_DEFINE( VOICE_PROMPT_EXAMPLE )
VP_EVT_DEFINE( TAKE_THE_CALL )
VP_EVT_DEFINE( REJECT )						//0x30
VP_EVT_DEFINE( REJECT_PHONE_CALL )
VP_EVT_DEFINE( PAIRING_FOR_VC )
VP_EVT_DEFINE( LAST_CALL_OUT )
VP_EVT_DEFINE( VOICE_DIAL_FOR_VC )
VP_EVT_DEFINE( VOICE_COMMAND_EXAMPE_SET0 )
VP_EVT_DEFINE( VOICE_COMMAND_EXAMPE_SET1 )
VP_EVT_DEFINE( VOICE_COMMAND_EXAMPE_SET2 )
VP_EVT_DEFINE( MAKE_A_CALL )
VP_EVT_DEFINE( CHECK_STATUS )
VP_EVT_DEFINE( RING_BACK )
VP_EVT_DEFINE( BEEP )
VP_EVT_DEFINE( INCOMING_CALL_ENDED )
VP_EVT_DEFINE( CALLER_ID )
VP_EVT_DEFINE( NUMBER )
VP_EVT_DEFINE( CALLER_ID_PREFIX )
VP_EVT_DEFINE( CALLER_ID_SUFFIX )			//0x40
VP_EVT_DEFINE( VOLUME_MINIMUM )
VP_EVT_DEFINE( PRESSURE_SENSOR)				//0x42
VP_EVT_DEFINE( FORCE_TOUCH_PRESS)			//0x43
VP_EVT_DEFINE( FORCE_TOUCH_RELEASE)			//0x44

