/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */


#include "bt.h"
#include "App_CheckKeyValid.h"
#include "App_EventOpcode.h"
#include "App_ResourceManager.h"
#include "App_ChargeBattery.h"
#include "App_SystemKey.h"
#include "App_AvrcpKey.h"
#include "App_HFPKey.h"
#include "App_Mp3Key.h"
#include "App_PowerOff.h"
#include "App_MCSyncKey.h"
#ifdef LINEIN_ENABLE
#include "APP_LineIn.h"
#endif
#ifdef PROFILE_AMA_ENABLE
#include "App_AMAKey.h"
#endif
#include "App_System.h"

/**************************************************************************************************
* Variable
**************************************************************************************************/
static KEY_EVT_MAP_TYPE_STRU const gKeyEventMapTable[KEY_TOTAL_NO] = //keyEventMap
{
	{NOT_KEY_EVENT, 	0},																//KEY_INVALID,
	{SYSTEM_KEY_EVENT,	SYSTEM_KEY_EVENT_KEY_RECONNECT_USER_INIT},						//KEY_RECONNECT_USER_INIT
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_DISCOVERABLE},								//KEY_DISCOVERABLE,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_NONDISCOVERABLE},							//KEY_NONDISCOVERABLE,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_CONNECTED_TO_DISCOVERABLE},				//KEY_CONNECTED_TO_DISCOVERABLE,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_CONNECTED_TO_CONNECTABLE},					//KEY_CONNECTED_TO_CONNECTABLE,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_NFC_DISCOVREABLE},							//KEY_NFC_DISCOVREABLE,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_CONFIRMATION_ACCEPT},						//KEY_CONFIRMATION_ACCEPT,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_CONFIRMATION_REJECT},						//KEY_CONFIRMATION_REJECT,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_DEBUG_KEY_TOGGLE},							//KEY_DEBUG_KEY_TOGGLE,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_VOICEUP},									//KEY_VOICEUP,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_VOICEDN},									//KEY_VOICEDN,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_BUZZER_MUTE_TOGGLE},						//KEY_BUZZER_MUTE_TOGGLE,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_TOGGLE_VOLUME},							//KEY_TOGGLE_VOLUME,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_VOLUME_ORIENTATION_NORMAL},				//KEY_VOLUME_ORIENTATION_NORMAL,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_VOLUME_ORIENTATION_INVERT},				//KEY_VOLUME_ORIENTATION_INVERT,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_TOGGLE_LED},								//KEY_TOGGLE_LED,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_ENABLE_LED},								//KEY_ENABLE_LED,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_DISABLE_LED},								//KEY_DISABLE_LED,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_CANCEL_LED_INDICATION},					//KEY_CANCEL_LED_INDICATION,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_MEDIA_TRIGGER_1},							//KEY_MEDIA_TRIGGER_1,
	{SYSTEM_KEY_EVENT, 	SYSTEM_KEY_EVENT_KEY_MEDIA_TRIGGER_2},							//KEY_MEDIA_TRIGGER_2,

	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_POWER_ON_THEN_ENTERDISCOVERABLE},			//KEY_POWER_ON_THEN_ENTERDISCOVERABLE,	// For NFC
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_POWER_ON},									//KEY_POWER_ON,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_POWER_OFF},								//KEY_POWER_OFF,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_RESET},									//KEY_RESET,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_RESET_PAIRED_DEVICES},						//KEY_RESET_PAIRED_DEVICES,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_MAX_DEVICE_ALLOWED_UP},					//KEY_MAX_DEVICE_ALLOWED_UP,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_MAX_DEVICE_ALLOWED_DOWN},					//KEY_MAX_DEVICE_ALLOWED_DOWN,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_MAX_DEVICE_ALLOWED_TOGGLE},				//KEY_MAX_DEVICE_ALLOWED_TOGGLE,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_RECONNECT_AFTER_POWER_ON},					//KEY_RECONNECT_AFTER_POWER_ON,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_VOICE_PROMPT_TOGGLE},						//KEY_VOICE_PROMPT_TOGGLE,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_VOICE_PROMPT_ENABLE},						//KEY_VOICE_PROMPT_ENABLE,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_VOICE_PROMPT_DISABLE},						//KEY_VOICE_PROMPT_DISABLE,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_VOICE_PROMPT_LANG_CHANGE},					//KEY_VOICE_PROMPT_LANG_CHANGE,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_VOICE_PROMPT_LANG_SELECT},					//KEY_VOICE_PROMPT_LANG_SELECT,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_VOICE_PROMPT_LANG_CONFIRM},				//KEY_VOICE_PROMPT_LANG_CONFIRM,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_TEST_VOICE_PROMPT_PLAY},					//KEY_TEST_VOICE_PROMPT_PLAY,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_TEST_VOICE_PROMPT_NEXT},					//KEY_TEST_VOICE_PROMPT_NEXT,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_BUTTONLOCKON},								//KEY_BUTTONLOCKON,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_BUTTONLOCKOFF},							//KEY_BUTTONLOCKOFF,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_BUTTONLOCKTOGGLE},							//KEY_BUTTONLOCKTOGGLE,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_VOICE_COMMAND_ENABLE},						//KEY_VOICE_COMMAND_ENABLE,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_MICUP},									//KEY_MICUP,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_MICDN},									//KEY_MICDN,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_MIC_MUTE_TOGGLE},							//KEY_MIC_MUTE_TOGGLE,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_MIC_MUTE_ON},								//KEY_MIC_MUTE_ON,
	{SYSTEM_KEY_EVENT,  SYSTEM_KEY_EVENT_KEY_MIC_MUTE_OFF},								//KEY_MIC_MUTE_OFF,

	{AWSMCE_KEY_EVENT,  AIR_KEY_EVENT_KEY_AIR_ENTER_AIR_PAIRING},						//KEY_AIR_ENTER_AIR_PAIRING,
	{AWSMCE_KEY_EVENT,  AIR_KEY_EVENT_KEY_AIR_EXIT_AIR_PAIRING},						//KEY_AIR_EXIT_AIR_PAIRING,

	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_AUDIO_TRANSFER},								//KEY_AUDIO_TRANSFER,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_SET_VOICE_RECOGNITION},						//KEY_SET_VOICE_RECOGNITION,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_RDIAL},										//KEY_RDIAL,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_DIALMEM},										//KEY_DIALMEM,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_DIALNUM},										//KEY_DIALNUM,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_CNLOUTGOING},									//KEY_CNLOUTGOING,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_REJCALL},										//KEY_REJCALL,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_REJCALL_SECOND_PHONE},						//KEY_REJCALL_SECOND_PHONE,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_ONHOLD_CALL},									//KEY_ONHOLD_CALL,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_ACPCALL},										//KEY_ACPCALL,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_ENDCALL},										//KEY_ENDCALL,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_3WAYRELNUDUB},								//KEY_3WAYRELNUDUB,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_3WAYRELNACP},									//KEY_3WAYRELNACP,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_3WAYRELNACP_X},								//KEY_3WAYRELNACP_X,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_3WAYHOLDNACP},								//KEY_3WAYHOLDNACP,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_3WAYHOLDNACP_X},								//KEY_3WAYHOLDNACP_X,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_3WAYADD},										//KEY_3WAYADD,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_3WAYCALLTRANSFER},							//KEY_3WAYCALLTRANSFER,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_HSP_BUTTON_PRESSED},							//KEY_HSP_BUTTON_PRESSED,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_DISABLE_NREC},								//KEY_DISABLE_NREC,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_GETCALLNUM},									//KEY_GETCALLNUM,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_QUERY_CALL_LIST},								//KEY_QUERY_CALL_LIST,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_SEND_DTMF},									//KEY_SEND_DTMF,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_ATTACH_LAST_VOICE_TAG_RECORDED},				//KEY_ATTACH_LAST_VOICE_TAG_RECORDED,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_SEND_CLIP},									//KEY_SEND_CLIP,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_RESERVED1},									//KEY_RESERVED1,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_RESERVED2},									//KEY_RESERVED2,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_SET_VOICE_RECOGNITION_CANCEL},				//KEY_SET_VOICE_RECOGNITION_CANCEL,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_RESERVED3},									//KEY_RESERVED3,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_SIRI_START_OR_CONTINUE},						//KEY_SIRI_START_OR_CONTINUE,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_SIRI_END},									//KEY_SIRI_END,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_RESERVED4},									//KEY_RESERVED4,
	{HFP_KEY_EVENT,  	HFP_KEY_EVENT_KEY_RESERVED5},									//KEY_RESERVED5,

	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_PLAY},								//KEY_AVRCP_PLAY,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_STOP},								//KEY_AVRCP_STOP,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_PAUSE},								//KEY_AVRCP_PAUSE,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_RECORD},								//KEY_AVRCP_RECORD,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_REWIND_PUSH},							//KEY_AVRCP_REWIND_PUSH,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_FAST_FORWARD_PUSH},					//KEY_AVRCP_FAST_FORWARD_PUSH,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_EJECT},								//KEY_AVRCP_EJECT,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_FORWARD},								//KEY_AVRCP_FORWARD,							//0x5B
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_BACKWARD},							//KEY_AVRCP_BACKWARD,							//0x5C
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_REWIND_RELEASE},						//KEY_AVRCP_REWIND_RELEASE,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_FAST_FORWARD_RELEASE},				//KEY_AVRCP_FAST_FORWARD_RELEASE,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_REPEAT_MODE_CHANGE},					//KEY_AVRCP_REPEAT_MODE_CHANGE,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_SHUFFLE_MODE_CHANGE},					//KEY_AVRCP_SHUFFLE_MODE_CHANGE,
	{AVRCP_KEY_EVENT,  	AVRCP_KEY_EVENT_KEY_AVRCP_ACTIVE_TOGGLE},						//KEY_AVRCP_ACTIVE_TOGGLE,

	{SYSTEM_KEY_EVENT,	SYSTEM_KEY_EVENT_KEY_PEQ_GROUP_CHANGE},							//KEY_PEQ_GROUP_CHANGE,

	{FM_KEY_EVENT,  	FM_KEY_EVENT_KEY_FM_POWERON},									//KEY_FM_POWERON,
	{FM_KEY_EVENT,  	FM_KEY_EVENT_KEY_FM_POWEROFF},									//KEY_FM_POWEROFF,
	{FM_KEY_EVENT,  	FM_KEY_EVENT_KEY_SEEKUP},										//KEY_SEEKUP,
	{FM_KEY_EVENT,  	FM_KEY_EVENT_KEY_SEEKDOWN},										//KEY_SEEKDOWN,								//0x66
	{FM_KEY_EVENT,  	FM_KEY_EVENT_KEY_TUNEUP},										//KEY_TUNEUP,
	{FM_KEY_EVENT,  	FM_KEY_EVENT_KEY_TUNEDN},										//KEY_TUNEDN,
	{FM_KEY_EVENT,  	FM_KEY_EVENT_KEY_FM_MUTETOGGLE},								//KEY_FM_MUTETOGGLE,

	{LINE_IN_KEY_EVENT,  	LINE_IN_KEY_EVENT_KEY_ENTER_LINEIN_MODE},					//KEY_ENTER_LINEIN_MODE,
	{LINE_IN_KEY_EVENT,  	LINE_IN_KEY_EVENT_KEY_EXIT_LINEIN_MODE},					//KEY_EXIT_LINEIN_MODE,
	{LINE_IN_KEY_EVENT,  	LINE_IN_KEY_EVENT_KEY_LINEIN_MUTE_TOGGLE},					//KEY_LINEIN_MUTE_TOGGLE,

	{TESTMODE_KEY_EVENT,  	TESTMODE_KEY_EVENT_KEY_ENTER_TESTMODE},						//KEY_ENTER_TESTMODE,
	{TESTMODE_KEY_EVENT,  	TESTMODE_KEY_EVENT_KEY_SWITCH_TEST_MODE_CHANNEL},			//KEY_SWITCH_TEST_MODE_CHANNEL,
	{TESTMODE_KEY_EVENT,  	TESTMODE_KEY_EVENT_KEY_SWITCH_TEST_MODE_POWER},				//KEY_SWITCH_TEST_MODE_POWER,
	{TESTMODE_KEY_EVENT,  	TESTMODE_KEY_EVENT_KEY_SWITCH_TEST_MODE_STATE},				//KEY_SWITCH_TEST_MODE_STATE,
	{TESTMODE_KEY_EVENT,  	TESTMODE_KEY_EVENT_KEY_SWITCH_TEST_MODE_TX_PACKET_TYPE},	//KEY_SWITCH_TEST_MODE_TX_PACKET_TYPE,

	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_SCO_SWITCH},							//KEY_SCO_SWITCH,

	{AWSMCE_KEY_EVENT,		AIR_KEY_EVENT_KEY_AIR_ENTER_AIR_SECURE_PAIRING},			//KEY_AIR_ENTER_AIR_SECURE_PAIRING,

	{SYSTEM_KEY_EVENT,  	SYSTEM_KEY_EVENT_KEY_MULTI_A2DP_PLAY_MODE_TOGGLE},			//KEY_MULTI_A2DP_PLAY_MODE_TOGGLE,
	{SYSTEM_KEY_EVENT,  	SYSTEM_KEY_EVENT_KEY_CHECK_STATUS_OF_CONNECTION},			//KEY_CHECK_STATUS_OF_CONNECTION
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_WHAT_CAN_I_SAY},						//KEY_WHAT_CAN_I_SAY

	{AVRCP_KEY_EVENT,		AVRCP_KEY_EVENT_KEY_KEY_LEFT_CHANNEL},						//KEY_LEFT_CHANNEL
	{AVRCP_KEY_EVENT,		AVRCP_KEY_EVENT_KEY_KEY_RIGHT_CHANNEL},						//KEY_RIGHT_CHANNEL
	{AVRCP_KEY_EVENT,		AVRCP_KEY_EVENT_KEY_KEY_STEREO_CHANNEL},					//KEY_STEREO_CHANNEL

	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_VOICE_COMMAND_CANCEL},					//KEY_VOICE_COMMAND_CANCEL
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_VOICE_MAKE_A_CALL},					//KEY_VOICE_MAKE_A_CALL
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_CHECK_STATUS},							//KEY_CHECK_STATUS
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_CHANGE_SOUND_EFFECT},					//KEY_CHANGE_SOUND_EFFECT
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_CONTROL_DBB_ON_OFF},					//KEY_CONTROL_DBB_ON_OFF
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_CONTROL_MIC_A2DP_MODE},							//KEY_CONTROL_MIC_A2DP_MODE

	{HID_KEY_EVENT,			HID_KEY_EVENT_KEY_SELFIE},									//KEY_EVENT_KEY_SELFIE //0x80

	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_ENABLE_DUT_MODE_COMMAND},						//KEY_ENABLE_DUT_MODE_COMMAND
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MIC_L_ENABLE},							//KEY_MIC_L_ENABLE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MIC_R_ENABLE},							//KEY_MIC_R_ENABLE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MIC_TO_SPK_ENABLE},					//KEY_MIC_TO_SPK_ENABLE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MIC_TO_SPK_DISABLE},					//KEY_MIC_TO_SPK_DISABLE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_ENABLE_EC_NR},							//KEY_ENABLE_EC_NR
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_DISABLE_EC_NR},						//KEY_DISABLE_EC_NR
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_2K_TONE_ENABLE},						//KEY_2K_TONE_ENABLE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_2K_TONE_DISABLE},						//KEY_2K_TONE_DISABLE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_SWITCH_STEREO_MONO},					//KEY_SWITCH_STEREO_MONO

	{HID_KEY_EVENT,			HID_KEY_EVENT_SWITCH_SELFIE},								//KEY_SWITCH_SELFIE

	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_AIROTHRU},								//KEY_AIROTHRU
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_ROLE_CHANGE},							//KEY_ROLE_CHANGE
	{MP3_KEY_EVENT,		    MP3_KEY_EVENT_KEY_MP3_POWERON},							//KEY_MP3_POWERON
	{MP3_KEY_EVENT,		    MP3_KEY_EVENT_KEY_MP3_POWEROFF},							//KEY_MP3_POWEROFF
	{MP3_KEY_EVENT,		    MP3_KEY_EVENT_KEY_MP3_PLAY},								//KEY_MP3_PLAY
	{MP3_KEY_EVENT,		    MP3_KEY_EVENT_KEY_MP3_STOP},								//KEY_MP3_STOP
	{MP3_KEY_EVENT,		    MP3_KEY_EVENT_KEY_MP3_PAUSE},							//KEY_MP3_PAUSE
	{MP3_KEY_EVENT,		    MP3_KEY_EVENT_KEY_MP3_FORWARD},							//KEY_MP3_FORWARD
	{MP3_KEY_EVENT,		    MP3_KEY_EVENT_KEY_MP3_BACKWARD},							//KEY_MP3_BACKWARD
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_ANC_SWITCH},							//KEY_ANC_SWITCH

	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_RESET_TO_FACTORY},						//KEY_RESET_TO_FACTORY
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_ANC_ON},								//KEY_ANC_ON
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_ANC_OFF},								//KEY_ANC_OFF

	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_DSP_RESET},							//KEY_DSP_RESET

	{AWSMCE_KEY_EVENT,		AWSMCE_KEY_EVENT_KEY_CONNECT},								//KEY_AWSMCE_CONNECT
	{AWSMCE_KEY_EVENT,		AWSMCE_KEY_EVENT_KEY_DISCONNECT},							//KEY_AWSMCE_DISCONNECT
	{AWSMCE_KEY_EVENT,		AWSMCE_KEY_EVENT_KEY_ENABLEDISCOVERABLE},					//KEY_AWSMCE_ENABLEDISCOVERABLE
	{AWSMCE_KEY_EVENT,		AWSMCE_KEY_EVENT_KEY_DISABLEDISCOVERABLE},					//KEY_AWSMCE_DISABLEDISCOVERABLE
	{AWSMCE_KEY_EVENT,		AWSMCE_KEY_EVENT_KEY_RHO},									//KEY_AWSMCE_RHO

	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_REPORT_BATTERY_STATUS},				//KEY_CHECK_BATTERY_STATUS

	{AMA_KEY_EVENT,			AMA_KEY_EVENT_KEY_SPEECH_TOGGLE},							//KEY_SPEECH_TOGGLE
	{AMA_KEY_EVENT,			AMA_KEY_EVENT_KEY_SPEECH_START},							//KEY_SPEECH_START
	{AMA_KEY_EVENT,			AMA_KEY_EVENT_KEY_SPEECH_STOP},								//KEY_SPEECH_STOP

	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_VAD_ON},								//KEY_VAD_ON
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_VAD_OFF},								//KEY_VAD_OFF
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_GAME_MODE_ON},							//KEY_GAME_MODE_ON
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_GAME_MODE_OFF},						//KEY_GAME_MODE_OFF
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_GAME_MODE_TOGGLE},						//KEY_GAME_MODE_TOGGLE

	{GVA_KEY_EVENT,			GVA_KEY_EVENT_PRESS},										//KEY_GVA_PRESS
	{GVA_KEY_EVENT,			GVA_KEY_EVENT_VOICE_QUERY},									//KEY_GVA_VOICE_QUERY
	{GVA_KEY_EVENT,			GVA_KEY_EVENT_NOTIFY},										//KEY_GVA_NOTIFY
	{GVA_KEY_EVENT,			GVA_KEY_EVENT_CANCEL}, 										//KEY_GVA_CANCEL
	{GVA_KEY_EVENT,			GVA_KEY_EVENT_RELEASE}, 									//KEY_GVA_RELEASE

	{XIAOAI_KEY_EVENT,		XIAOAI_KEY_EVENT_KEY_FUNC_2},								//KEY_XIAOAI_FUNC_2
	{XIAOAI_KEY_EVENT,		XIAOAI_KEY_EVENT_KEY_SPEECH_START},							//KEY_XIAOAI_SPEECH_START
	{XIAOAI_KEY_EVENT,		XIAOAI_KEY_EVENT_KEY_FUNC_1},								//KEY_XIAOAI_FUNC_1

	{AWSMCE_KEY_EVENT,		AWSMCE_KEY_EVENT_KEY_EARBUDS_MODE_AIR_PAIRING_START},		//KEY_EARBUDS_PAIRING_START
	{AWSMCE_KEY_EVENT,		AWSMCE_KEY_EVENT_KEY_EARBUDS_MODE_AIR_PAIRING_STOP},		//KEY_EARBUDS_PAIRING_STOP

<<<<<<< HEAD
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_AGENT_STARTS_SHARE_MODE}, 				//KEY_AGENT_STARTS_SHARE_MODE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_AGENT_STOPS_SHARE_MODE}, 				//KEY_AGENT_STOPS_SHARE_MODE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_FOLLOWER_STARTS_SHARE_MODE}, 			//KEY_FOLLOWER_STARTS_SHARE_MODE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_FOLLOWER_STOPS_SHARE_MODE}, 				//KEY_FOLLOWER_STOPS_SHARE_MODE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_AGENT_TOGGLE_SHARE_MODE}, 				//KEY_AGENT_TOGGLE_SHARE_MODE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_FOLLOWER_TOGGLE_SHARE_MODE}, 			//KEY_FOLLOWER_TOGGLE_SHARE_MODE
=======
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MASTER_SHARE_MODE_START}, 				//KEY_MASTER_SHARE_MODE_START
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MASTER_SHARE_MODE_STOP}, 				//KEY_MASTER_SHARE_MODE_STOP
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_FOLLOWER_SHARE_MODE_START}, 			//KEY_FOLLOWER_SHARE_MODE_START
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_FOLLOWER_SHARE_MODE_STOP}, 			//KEY_FOLLOWER_SHARE_MODE_STOP
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MASTER_SHARE_MODE_TOGGLE}, 			//KEY_MASTER_SHARE_MODE_TOGGLE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_FOLLOWER_SHARE_MODE_TOGGLE}, 			//KEY_FOLLOWER_SHARE_MODE_TOGGLE
>>>>>>> db20e11 (second commit)
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MIC_TO_SPK_3MIC_MAIN_MIC_ENABLE}, 		//KEY_MIC_TO_SPK_3MIC_MAIN_MIC_ENABLE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MIC_TO_SPK_3MIC_REF1_MIC_ENABLE}, 		//KEY_MIC_TO_SPK_3MIC_REF1_MIC_ENABLE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MIC_TO_SPK_3MIC_REF2_MIC_ENABLE}, 		//KEY_MIC_TO_SPK_3MIC_REF2_MIC_ENABLE
	{SYSTEM_KEY_EVENT,		SYSTEM_KEY_EVENT_KEY_MIC_TO_SPK_3MIC_DISABLE}, 				//KEY_MIC_TO_SPK_3MIC_DISABLE
};

/**************************************************************************************************
* Public Functions
**************************************************************************************************/
U16 APP_ChkKeyVld_CheckKeyValid(U16 keyEventCode)
{
	U8 keyEventIndex;
	//APP_PRINTF(COLOR_CHECK_KEY_VALID, PRINT_CHECK_KEY_VALID, "keycode[%x]",keyEventCode);
	if(APP_CHGBAT_IsKeyInvalidPwOnLowBat())
	{
		if(keyEventCode != KEY_POWER_OFF && keyEventCode != KEY_RESET)
		{
			DBG_LOG_APP_SYSTEM( "[APP_CKKey] Key Invalid: Power On Low Battery", 0);
			return KEY_INVALID;
		}
	}

	switch(keyEventCode)
	{
		case KEY_POWER_ON_THEN_ENTERDISCOVERABLE:
		case KEY_POWER_ON:
		case KEY_RESET_PAIRED_DEVICES:
		case KEY_RESET:
		case KEY_RESET_TO_FACTORY:
		case KEY_VOICE_PROMPT_TOGGLE:
		case KEY_VOICE_PROMPT_DISABLE:
		case KEY_VOICE_PROMPT_ENABLE:
		case KEY_VOICE_PROMPT_LANG_CHANGE:
		case KEY_VOICE_PROMPT_LANG_SELECT:
		case KEY_VOICE_PROMPT_LANG_CONFIRM:
		case KEY_TOGGLE_LED:
		case KEY_ENABLE_LED:
		case KEY_DISABLE_LED:
		case KEY_CANCEL_LED_INDICATION:
		case KEY_TOGGLE_VOLUME:
		case KEY_VOLUME_ORIENTATION_NORMAL:
		case KEY_VOLUME_ORIENTATION_INVERT:
		case KEY_BUZZER_MUTE_TOGGLE:
		case KEY_ENTER_TESTMODE:
		case KEY_MAX_DEVICE_ALLOWED_UP:
		case KEY_MAX_DEVICE_ALLOWED_DOWN:
		case KEY_MAX_DEVICE_ALLOWED_TOGGLE:
		case KEY_DEBUG_KEY_TOGGLE:
		case KEY_BUTTONLOCKTOGGLE:
		case KEY_POWER_OFF:
			break;

		default:
			if(!APP_PowerOff_IsPowerOn())
			{
				//APP_PRINTF(COLOR_CHECK_KEY_VALID, PRINT_CHECK_KEY_VALID, "Key Invalid: Not Power On");
				keyEventCode = KEY_INVALID;
			}
			break;
	}

	if(APP_Media_IsSubSinkQBufFull() || APP_Media_IsMediaEvtLock(keyEventCode))
	{
		DBG_LOG_APP_SYSTEM( "[APP_CKKey] Key Invalid: Q Full:%d, Media Event Lock:%d", 2, APP_Media_IsSubSinkQBufFull(), APP_Media_IsMediaEvtLock(keyEventCode));
		keyEventCode = KEY_INVALID;
	}

	if(keyEventCode == KEY_INVALID)
	{
		return keyEventCode;
	}

	keyEventIndex = APP_ChkKeyVld_GetKeyEventIndex(keyEventCode);
	switch(APP_ChkKeyVld_GetKeyEventGroup(keyEventCode))
	{
		case SYSTEM_KEY_EVENT:
			keyEventCode = APP_SystemKey_CheckKeyValid(keyEventIndex, keyEventCode);
			break;
		case AWSMCE_KEY_EVENT:
			keyEventCode = APP_AWSMCE_CheckValidKey(keyEventIndex, keyEventCode);
			break;
		case HFP_KEY_EVENT:
			#ifdef HFP_Profile
			keyEventCode = APP_HFP_CheckValidKey(keyEventIndex, keyEventCode);
			#else
			keyEventCode = KEY_INVALID;
			#endif
			break;
		case AVRCP_KEY_EVENT:
<<<<<<< HEAD
			#ifdef AVRCP_Profile
=======
			#ifdef AIR_AVRCP_PROFILE_ENABLE
>>>>>>> db20e11 (second commit)

			#else
			keyEventCode = KEY_INVALID;
			#endif
			break;
		case FM_KEY_EVENT:
			#ifdef FM_ENABLE
//			keyEventCode = MMI_FM_CheckValidKey(keyEventIndex, keyEventCode);
			#else
			keyEventCode = KEY_INVALID;
			#endif
			break;
		case LINE_IN_KEY_EVENT:
			#ifdef LINEIN_ENABLE
			keyEventCode = APP_LineIn_CheckValidKey(keyEventIndex, keyEventCode);
			#else
			keyEventCode = KEY_INVALID;
			#endif
			break;
		case TESTMODE_KEY_EVENT:
			break;

		case AMA_KEY_EVENT:
			#ifdef PROFILE_AMA_ENABLE
			keyEventCode = APP_AMA_CheckValidKey(keyEventIndex, keyEventCode);
			#else
			keyEventCode = KEY_INVALID;
			#endif
			break;

        case MP3_KEY_EVENT:
			#ifdef MP3_LOCAL_PLAYBACK_MMI_CTRL
			keyEventCode = APP_MP3_CheckValidKey(keyEventIndex, keyEventCode);
			#else
			keyEventCode = KEY_INVALID;
			#endif
            break;

	}
	return keyEventCode;
}

U8 APP_ChkKeyVld_GetKeyEventGroup(U16 keyEventCode)
{
	return gKeyEventMapTable[keyEventCode].keyEventGroup;
}

U8 APP_ChkKeyVld_GetKeyEventIndex(U16 keyEventCode)
{
	return gKeyEventMapTable[keyEventCode].keyEventIndex;
}

