/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */
 
 
//0x0501
EVENT_NAME(FOR_AE2)
EVENT_NAME(FOR_AE3)
EVENT_NAME(FOR_AE4)
EVENT_NAME(FOR_AE5)
EVENT_NAME(FOR_AE6)
EVENT_NAME(FOR_AE7)
EVENT_NAME(FOR_AE8)
EVENT_NAME(FOR_AE9)
EVENT_NAME(FOR_AE10)
EVENT_NAME(FOR_AE11)
EVENT_NAME(FOR_AE12)
EVENT_NAME(FOR_AE13)
EVENT_NAME(FOR_AE14)
EVENT_NAME(FOR_AE15)
EVENT_NAME(FOR_AE16)


//0x051x
EVENT_NAME(FOR_AE17)
EVENT_NAME(FOR_AE18)
EVENT_NAME(FOR_AE19)
EVENT_NAME(FOR_AE20)
EVENT_NAME(FOR_AE21)
EVENT_NAME(FOR_AE22)
EVENT_NAME(FOR_AE23)
EVENT_NAME(FOR_AE24)
EVENT_NAME(FOR_AE25)
EVENT_NAME(FOR_AE26)
EVENT_NAME(FOR_AE27)
EVENT_NAME(FOR_AE28)
EVENT_NAME(FOR_AE29)
EVENT_NAME(FOR_AE30)
EVENT_NAME(FOR_AE31)
EVENT_NAME(FOR_AE32)

//0x052x
EVENT_NAME(FOR_AE33)
EVENT_NAME(FOR_AE34)
EVENT_NAME(FOR_AE35)
EVENT_NAME(FOR_AE36)
EVENT_NAME(FOR_AE37)
EVENT_NAME(FOR_AE38)
EVENT_NAME(FOR_AE39)
EVENT_NAME(FOR_AE40)
EVENT_NAME(FOR_AE41)
EVENT_NAME(FOR_AE42)
EVENT_NAME(FOR_AE43)
EVENT_NAME(FOR_AE44)
EVENT_NAME(FOR_AE45)
EVENT_NAME(FOR_AE46)
EVENT_NAME(FOR_AE47)
EVENT_NAME(FOR_AE48)

//0x053x
EVENT_NAME(FOR_AE49)
EVENT_NAME(FOR_AE50)
EVENT_NAME(FOR_AE51)
EVENT_NAME(FOR_AE52)
EVENT_NAME(FOR_AE53)
EVENT_NAME(FOR_AE54)
EVENT_NAME(FOR_AE55)
EVENT_NAME(FOR_AE56)
EVENT_NAME(FOR_AE57)
EVENT_NAME(FOR_AE58)
EVENT_NAME(FOR_AE59)
EVENT_NAME(FOR_AE60)
EVENT_NAME(FOR_AE61)
EVENT_NAME(FOR_AE62)
EVENT_NAME(FOR_AE63)
EVENT_NAME(FOR_AE64)

//0x054x
EVENT_NAME(FOR_AE65)
EVENT_NAME(FOR_AE66)
EVENT_NAME(FOR_AE67)
EVENT_NAME(FOR_AE68)
EVENT_NAME(FOR_AE69)
EVENT_NAME(FOR_AE70)
EVENT_NAME(FOR_AE71)
EVENT_NAME(FOR_AE72)
EVENT_NAME(FOR_AE73)
EVENT_NAME(FOR_AE74)
EVENT_NAME(FOR_AE75)
EVENT_NAME(FOR_AE76)
EVENT_NAME(FOR_AE77)
EVENT_NAME(FOR_AE78)
EVENT_NAME(FOR_AE79)
EVENT_NAME(FOR_AE80)

//0x055x
EVENT_NAME(FOR_AE81)
EVENT_NAME(FOR_AE82)
EVENT_NAME(FOR_AE83)
EVENT_NAME(FOR_AE84)
EVENT_NAME(FOR_AE85)
EVENT_NAME(FOR_AE86)
EVENT_NAME(FOR_AE87)
EVENT_NAME(FOR_AE88)
EVENT_NAME(FOR_AE89)
EVENT_NAME(FOR_AE90)
EVENT_NAME(FOR_AE91)
EVENT_NAME(FOR_AE92)
EVENT_NAME(FOR_AE93)
EVENT_NAME(FOR_AE94)
EVENT_NAME(FOR_AE95)
EVENT_NAME(FOR_AE96)

//0x056x
EVENT_NAME(FOR_AE97)
EVENT_NAME(FOR_AE98)
EVENT_NAME(FOR_AE99)
EVENT_NAME(FOR_AE100)
EVENT_NAME(FOR_AE101)
EVENT_NAME(FOR_AE102)
EVENT_NAME(FOR_AE103)
EVENT_NAME(FOR_AE104)
EVENT_NAME(FOR_AE105)
EVENT_NAME(FOR_AE106)
EVENT_NAME(FOR_AE107)
EVENT_NAME(FOR_AE108)
EVENT_NAME(FOR_AE109)
EVENT_NAME(FOR_AE110)
EVENT_NAME(FOR_AE111)
EVENT_NAME(FOR_AE112)

//0x057x
EVENT_NAME(FOR_AE113)
EVENT_NAME(FOR_AE114)
EVENT_NAME(FOR_AE115)
EVENT_NAME(FOR_AE116)
EVENT_NAME(FOR_AE117)
EVENT_NAME(FOR_AE118)
EVENT_NAME(FOR_AE119)
EVENT_NAME(FOR_AE120)
EVENT_NAME(FOR_AE121)
EVENT_NAME(FOR_AE122)
EVENT_NAME(FOR_AE123)
EVENT_NAME(FOR_AE124)
EVENT_NAME(FOR_AE125)
EVENT_NAME(FOR_AE126)
EVENT_NAME(FOR_AE127)
EVENT_NAME(FOR_AE128)


//0x058x
EVENT_NAME(FOR_AE129)
EVENT_NAME(FOR_AE130)
EVENT_NAME(FOR_AE131)
EVENT_NAME(FOR_AE132)
EVENT_NAME(FOR_AE133)
EVENT_NAME(FOR_AE134)
EVENT_NAME(FOR_AE135)
EVENT_NAME(FOR_AE136)
EVENT_NAME(FOR_AE137)
EVENT_NAME(FOR_AE138)
EVENT_NAME(FOR_AE139)
EVENT_NAME(FOR_AE140)
EVENT_NAME(FOR_AE141)
EVENT_NAME(FOR_AE142)
EVENT_NAME(FOR_AE143)
EVENT_NAME(FOR_AE144)

//0x059x
EVENT_NAME(FOR_AE145)
EVENT_NAME(FOR_AE146)
EVENT_NAME(FOR_AE147)
EVENT_NAME(FOR_AE148)
EVENT_NAME(FOR_AE149)
EVENT_NAME(FOR_AE150)
EVENT_NAME(FOR_AE151)
EVENT_NAME(FOR_AE152)
EVENT_NAME(FOR_AE153)
EVENT_NAME(FOR_AE154)
EVENT_NAME(FOR_AE155)
EVENT_NAME(FOR_AE156)
EVENT_NAME(FOR_AE157)
EVENT_NAME(FOR_AE158)
EVENT_NAME(FOR_AE159)
EVENT_NAME(FOR_AE160)

//0x05Ax
EVENT_NAME(FOR_AE161)
EVENT_NAME(FOR_AE162)
EVENT_NAME(FOR_AE163)
EVENT_NAME(FOR_AE164)
EVENT_NAME(FOR_AE165)
EVENT_NAME(FOR_AE166)
EVENT_NAME(FOR_AE167)
EVENT_NAME(FOR_AE168)
EVENT_NAME(FOR_AE169)
EVENT_NAME(FOR_AE170)
EVENT_NAME(FOR_AE171)
EVENT_NAME(FOR_AE172)
EVENT_NAME(FOR_AE173)
EVENT_NAME(FOR_AE174)
EVENT_NAME(FOR_AE175)
EVENT_NAME(FOR_AE176)

//0x05Bx
EVENT_NAME(FOR_AE177)
EVENT_NAME(FOR_AE178)
EVENT_NAME(FOR_AE179)
EVENT_NAME(FOR_AE180)
EVENT_NAME(FOR_AE181)
EVENT_NAME(FOR_AE182)
EVENT_NAME(FOR_AE183)
EVENT_NAME(FOR_AE184)
EVENT_NAME(FOR_AE185)
EVENT_NAME(FOR_AE186)
EVENT_NAME(FOR_AE187)
EVENT_NAME(FOR_AE188)
EVENT_NAME(FOR_AE189)
EVENT_NAME(FOR_AE190)
EVENT_NAME(FOR_AE191)
EVENT_NAME(FOR_AE192)

//0x05Cx
EVENT_NAME(FOR_AE193)
EVENT_NAME(FOR_AE194)
EVENT_NAME(FOR_AE195)
EVENT_NAME(FOR_AE196)
EVENT_NAME(FOR_AE197)
EVENT_NAME(FOR_AE198)
EVENT_NAME(FOR_AE199)
EVENT_NAME(FOR_AE200)
EVENT_NAME(FOR_AE201)
EVENT_NAME(FOR_AE202)
EVENT_NAME(FOR_AE203)
EVENT_NAME(FOR_AE204)
EVENT_NAME(FOR_AE205)
EVENT_NAME(FOR_AE206)
EVENT_NAME(FOR_AE207)
EVENT_NAME(FOR_AE208)

//0x05Dx
EVENT_NAME(FOR_AE209)
EVENT_NAME(FOR_AE210)
EVENT_NAME(FOR_AE211)
EVENT_NAME(FOR_AE212)
EVENT_NAME(FOR_AE213)
EVENT_NAME(FOR_AE214)
EVENT_NAME(FOR_AE215)
EVENT_NAME(FOR_AE216)
EVENT_NAME(FOR_AE217)
EVENT_NAME(FOR_AE218)
EVENT_NAME(FOR_AE219)
EVENT_NAME(FOR_AE220)
EVENT_NAME(FOR_AE221)
EVENT_NAME(FOR_AE222)
EVENT_NAME(FOR_AE223)
EVENT_NAME(FOR_AE224)

//0x05Ex
EVENT_NAME(FOR_AE225)
EVENT_NAME(FOR_AE226)
EVENT_NAME(FOR_AE227)
EVENT_NAME(FOR_AE228)
EVENT_NAME(FOR_AE229)
EVENT_NAME(FOR_AE230)
EVENT_NAME(FOR_AE231)
EVENT_NAME(FOR_AE232)
EVENT_NAME(FOR_AE233)
EVENT_NAME(FOR_AE234)
EVENT_NAME(FOR_AE235)
EVENT_NAME(FOR_AE236)
EVENT_NAME(FOR_AE237)
EVENT_NAME(FOR_AE238)
EVENT_NAME(FOR_AE239)
EVENT_NAME(FOR_AE240)

//0x05Fx
EVENT_NAME(FOR_AE241)
EVENT_NAME(FOR_AE242)
EVENT_NAME(FOR_AE243)
EVENT_NAME(FOR_AE244)
EVENT_NAME(FOR_AE245)
EVENT_NAME(FOR_AE246)
EVENT_NAME(FOR_AE247)
EVENT_NAME(FOR_AE248)
EVENT_NAME(FOR_AE249)
EVENT_NAME(FOR_AE250)
EVENT_NAME(FOR_AE251)
EVENT_NAME(FOR_AE252)
EVENT_NAME(FOR_AE253)
EVENT_NAME(FOR_AE254)
EVENT_NAME(FOR_AE255)
EVENT_NAME(FOR_AE256)

