/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */
 
 
#include <stdio.h>
#include <stdlib.h>
#include "AudioDSP_StreamManager.h"

typedef char S8;
typedef unsigned char U8;
typedef short S16;
typedef unsigned short U16;
typedef int S32;
typedef unsigned int U32;

#define PACKED __attribute__((__packed__))

/**************************************************************************************************
* Definition
**************************************************************************************************/
#define VP_CODEC_CHI 1028
#define VP_CODEC_ENG 1033

#define NVKEY_ID_VP_EVENT_TABLE_CHI	0xF292
#define NVKEY_ID_VP_EVENT_TABLE_ENG	0xF293

#define VP_LANG_DEFAULT_CNT		2

/**************************************************************************************************
* Enumeration
**************************************************************************************************/
#define VP_EVT_DEFINE(name) VP_EVT_##name,
enum
{
	VP_EVT_DEFINE( ZERO )						//0x00
	VP_EVT_DEFINE( ONE )
	VP_EVT_DEFINE( TWO )
	VP_EVT_DEFINE( THREE )
	VP_EVT_DEFINE( FOUR )
	VP_EVT_DEFINE( FIVE )
	VP_EVT_DEFINE( SIX )
	VP_EVT_DEFINE( SEVEN )
	VP_EVT_DEFINE( EIGHT )
	VP_EVT_DEFINE( NINE )
	VP_EVT_DEFINE( VOICE_PROMPT_LANG_CHANGE )
	VP_EVT_DEFINE( VOICE_PROMPT_ON )
	VP_EVT_DEFINE( VOICE_PROMPT_OFF )
	VP_EVT_DEFINE( MULTI_POINT_MODE_ON )
	VP_EVT_DEFINE( MULTI_POINT_MODE_OFF )
	VP_EVT_DEFINE( MUTE_ON )
	VP_EVT_DEFINE( MUTE_OFF )					//0x10
	VP_EVT_DEFINE( POWER_ON )
	VP_EVT_DEFINE( POWER_OFF )
	VP_EVT_DEFINE( PAIRING )
	VP_EVT_DEFINE( PAIRING_SUCCESSFUL )
	VP_EVT_DEFINE( CONNECTED )
	VP_EVT_DEFINE( SECOND_DEVICE_CONNECTED )
	VP_EVT_DEFINE( DEVICE_DISCONNECTED )
	VP_EVT_DEFINE( INCOMING_CALL )
	VP_EVT_DEFINE( CALL_REJECTED )
	VP_EVT_DEFINE( CALL_CANCELLED )
	VP_EVT_DEFINE( CALL_ENDED )
	VP_EVT_DEFINE( RE_DIALING )
	VP_EVT_DEFINE( LOW_BATTERY )
	VP_EVT_DEFINE( BATTERY_IS_HIGH )
	VP_EVT_DEFINE( BATTERY_IS_MEDIAN )
	VP_EVT_DEFINE( BATTERY_IS_LOW )				//0x20
	VP_EVT_DEFINE( VOLUME_MAXIMUM )
	VP_EVT_DEFINE( PAUSE )
	VP_EVT_DEFINE( LINE_IN_MODE )
	VP_EVT_DEFINE( BLUETOOTH_MODE )
	VP_EVT_DEFINE( FM_MODE )
	VP_EVT_DEFINE( SEEK_UP )
	VP_EVT_DEFINE( SEEK_DOWN )
	VP_EVT_DEFINE( LEFT_CHANNEL )
	VP_EVT_DEFINE( RIGHT_CHANNEL )
	VP_EVT_DEFINE( WHAT_CAN_I_SAY )
	VP_EVT_DEFINE( CONNECTION_STATUS )
	VP_EVT_DEFINE( CHECK_BATTERY )
	VP_EVT_DEFINE( CANCEL )
	VP_EVT_DEFINE( VOICE_PROMPT_EXAMPLE )
	VP_EVT_DEFINE( TAKE_THE_CALL )
	VP_EVT_DEFINE( REJECT )						//0x30
	VP_EVT_DEFINE( REJECT_PHONE_CALL )
	VP_EVT_DEFINE( PAIRING_FOR_VC )
	VP_EVT_DEFINE( LAST_CALL_OUT )
	VP_EVT_DEFINE( VOICE_DIAL_FOR_VC )
	VP_EVT_DEFINE( VOICE_COMMAND_EXAMPE_SET0 )
	VP_EVT_DEFINE( VOICE_COMMAND_EXAMPE_SET1 )
	VP_EVT_DEFINE( VOICE_COMMAND_EXAMPE_SET2 )
	VP_EVT_DEFINE( MAKE_A_CALL )
	VP_EVT_DEFINE( CHECK_STATUS )
	VP_EVT_DEFINE( RING_BACK )
	VP_EVT_DEFINE( BEEP )
	VP_EVT_DEFINE( INCOMING_CALL_ENDED )
	VP_EVT_DEFINE( CALLER_ID )
	VP_EVT_DEFINE( NUMBER )
	VP_EVT_DEFINE( CALLER_ID_PREFIX )
	VP_EVT_DEFINE( CALLER_ID_SUFFIX )
	
	VP_EVENT_DEFAULT_CNT
};

/**************************************************************************************************
* Structure
**************************************************************************************************/
typedef struct
{
	U16 codec;
	U16 nvkeyId;
}PACKED VP_LANG_INFO_NVKEY_STRU;

typedef struct
{
	U8 langCnt;
	VP_LANG_INFO_NVKEY_STRU langInfo[VP_LANG_DEFAULT_CNT];
}PACKED VP_LANG_NVKEY_STRU;


typedef struct
{
	U8 id;
	U8 fileCnt;
}PACKED VP_EVENT_INFO_NVKEY_STRU;

typedef struct
{
	U8 eventNum;
	U8 eventInfo[1];
}PACKED VP_EVENT_LANG_NVKEY_STRU;

/**************************************************************************************************
* Structure Assign
**************************************************************************************************/
VP_LANG_NVKEY_STRU gVpLangDefault =
{
	VP_LANG_DEFAULT_CNT,
	{
		{VP_CODEC_CHI, NVKEY_ID_VP_EVENT_TABLE_CHI},
		{VP_CODEC_ENG, NVKEY_ID_VP_EVENT_TABLE_ENG},
	}
};

#define U16to2U8(x) (U8)x, (U8)(x >> 8)
U8 gVpEventDefault_CHI[] =
{
	VP_EVENT_DEFAULT_CNT,
//	id, fileCnt, fileId 1, fileId 2, ...
	VP_EVT_ZERO, 1, U16to2U8(68),
	VP_EVT_ONE, 1, U16to2U8(69),
	VP_EVT_TWO, 1, U16to2U8(70),
	VP_EVT_THREE, 1, U16to2U8(71),
	VP_EVT_FOUR, 1, U16to2U8(72),
	VP_EVT_FIVE, 1, U16to2U8(73),
	VP_EVT_SIX, 1, U16to2U8(74),
	VP_EVT_SEVEN, 1, U16to2U8(75),
	VP_EVT_EIGHT, 1, U16to2U8(76),
	VP_EVT_NINE, 1, U16to2U8(77),
	VP_EVT_VOICE_PROMPT_LANG_CHANGE, 1, U16to2U8(95),
	VP_EVT_VOICE_PROMPT_ON, 1, U16to2U8(125),
	VP_EVT_VOICE_PROMPT_OFF, 1, U16to2U8(124),
	VP_EVT_MULTI_POINT_MODE_ON, 1, U16to2U8(104),
	VP_EVT_MULTI_POINT_MODE_OFF, 1, U16to2U8(103),
	VP_EVT_MUTE_ON, 1, U16to2U8(108),
	VP_EVT_MUTE_OFF, 1, U16to2U8(107),
	VP_EVT_POWER_ON, 1, U16to2U8(114),
	VP_EVT_POWER_OFF, 1, U16to2U8(113),
	VP_EVT_PAIRING, 1, U16to2U8(96),
	VP_EVT_PAIRING_SUCCESSFUL, 1, U16to2U8(111),
	VP_EVT_CONNECTED, 1, U16to2U8(92),
	VP_EVT_SECOND_DEVICE_CONNECTED, 1, U16to2U8(118),
	VP_EVT_DEVICE_DISCONNECTED, 1, U16to2U8(93),
	VP_EVT_INCOMING_CALL, 1, U16to2U8(99),
	VP_EVT_CALL_REJECTED, 1, U16to2U8(86),
	VP_EVT_CALL_CANCELLED, 1, U16to2U8(83),
	VP_EVT_CALL_ENDED, 1, U16to2U8(84),
	VP_EVT_RE_DIALING, 1, U16to2U8(116),
	VP_EVT_LOW_BATTERY, 1, U16to2U8(102),
	VP_EVT_BATTERY_IS_HIGH, 1, U16to2U8(79),
	VP_EVT_BATTERY_IS_MEDIAN, 1, U16to2U8(81),
	VP_EVT_BATTERY_IS_LOW, 1, U16to2U8(80),
	VP_EVT_VOLUME_MAXIMUM, 1, U16to2U8(129),
	VP_EVT_PAUSE, 0,
	VP_EVT_LINE_IN_MODE, 1, U16to2U8(101),
	VP_EVT_BLUETOOTH_MODE, 1, U16to2U8(82),
	VP_EVT_FM_MODE, 1, U16to2U8(98),
	VP_EVT_SEEK_UP, 1, U16to2U8(120),
	VP_EVT_SEEK_DOWN, 1, U16to2U8(119),
	VP_EVT_LEFT_CHANNEL, 1, U16to2U8(100),
	VP_EVT_RIGHT_CHANNEL, 1, U16to2U8(117),
	VP_EVT_WHAT_CAN_I_SAY, 0,
	VP_EVT_CONNECTION_STATUS, 0,
	VP_EVT_CHECK_BATTERY, 0,
	VP_EVT_CANCEL, 0,
	VP_EVT_VOICE_PROMPT_EXAMPLE, 0,
	VP_EVT_TAKE_THE_CALL, 0,
	VP_EVT_REJECT, 0,
	VP_EVT_REJECT_PHONE_CALL, 0,
	VP_EVT_PAIRING_FOR_VC, 0,
	VP_EVT_LAST_CALL_OUT, 0,
	VP_EVT_VOICE_DIAL_FOR_VC, 0,
	VP_EVT_VOICE_COMMAND_EXAMPE_SET0, 0,
	VP_EVT_VOICE_COMMAND_EXAMPE_SET1, 0,
	VP_EVT_VOICE_COMMAND_EXAMPE_SET2, 0,
	VP_EVT_MAKE_A_CALL, 0,
	VP_EVT_CHECK_STATUS, 0,
	VP_EVT_RING_BACK, 0,
	VP_EVT_BEEP, 0,
	VP_EVT_INCOMING_CALL_ENDED, 1, U16to2U8(132),
	VP_EVT_CALLER_ID, 0,
	VP_EVT_NUMBER, 1, U16to2U8(109),
	VP_EVT_CALLER_ID_PREFIX, 1, U16to2U8(109),
	VP_EVT_CALLER_ID_SUFFIX, 0,
};

U8 gVpEventDefault_ENG[] =
{
	VP_EVENT_DEFAULT_CNT,
//	id, fileCnt, fileId 1, fileId 2, ...
	VP_EVT_ZERO, 1, U16to2U8(0x2000),
	VP_EVT_ONE, 1, U16to2U8(0x2001),
	VP_EVT_TWO, 1, U16to2U8(0x2002),
	VP_EVT_THREE, 1, U16to2U8(0x2003),
	VP_EVT_FOUR, 1, U16to2U8(0x2004),
	VP_EVT_FIVE, 1, U16to2U8(0x2005),
	VP_EVT_SIX, 1, U16to2U8(0x2006),
	VP_EVT_SEVEN, 1, U16to2U8(0x2007),
	VP_EVT_EIGHT, 1, U16to2U8(0x2008),
	VP_EVT_NINE, 1, U16to2U8(0x2009),
	VP_EVT_VOICE_PROMPT_LANG_CHANGE, 1, U16to2U8(0x201B),
	VP_EVT_VOICE_PROMPT_ON, 1, U16to2U8(0x2039),
	VP_EVT_VOICE_PROMPT_OFF, 1, U16to2U8(0x2038),
	VP_EVT_MULTI_POINT_MODE_ON, 1, U16to2U8(0x2024),
	VP_EVT_MULTI_POINT_MODE_OFF, 1, U16to2U8(0x2023),
	VP_EVT_MUTE_ON, 1, U16to2U8(0x2027),
	VP_EVT_MUTE_OFF, 1, U16to2U8(0x2026),
	VP_EVT_POWER_ON, 1, U16to2U8(0x202e),
	VP_EVT_POWER_OFF, 1, U16to2U8(0x202d),
	VP_EVT_PAIRING, 1, U16to2U8(0x2028),
	VP_EVT_PAIRING_SUCCESSFUL, 1, U16to2U8(0x202a),
	VP_EVT_CONNECTED, 1, U16to2U8(0x2018),
	VP_EVT_SECOND_DEVICE_CONNECTED, 1, U16to2U8(0x2032),
	VP_EVT_DEVICE_DISCONNECTED, 1, U16to2U8(0x2019),
	VP_EVT_INCOMING_CALL, 1, U16to2U8(0x201f),
	VP_EVT_CALL_REJECTED, 1, U16to2U8(0x2012),
	VP_EVT_CALL_CANCELLED, 1, U16to2U8(0x200f),
	VP_EVT_CALL_ENDED, 1, U16to2U8(0x2010),
	VP_EVT_RE_DIALING, 1, U16to2U8(0x2030),
	VP_EVT_LOW_BATTERY, 1, U16to2U8(0x2022),
	VP_EVT_BATTERY_IS_HIGH, 1, U16to2U8(0x200b),
	VP_EVT_BATTERY_IS_MEDIAN, 1, U16to2U8(0x200d),
	VP_EVT_BATTERY_IS_LOW, 1, U16to2U8(0x200c),
	VP_EVT_VOLUME_MAXIMUM, 1, U16to2U8(0x203D),
	VP_EVT_PAUSE, 0,
	VP_EVT_LINE_IN_MODE, 1, U16to2U8(0x2021),
	VP_EVT_BLUETOOTH_MODE, 1, U16to2U8(0x200e),
	VP_EVT_FM_MODE, 1, U16to2U8(0x201c),
	VP_EVT_SEEK_UP, 1, 0,
	VP_EVT_SEEK_DOWN, 1, 0,
	VP_EVT_LEFT_CHANNEL, 1, U16to2U8(0x2020),
	VP_EVT_RIGHT_CHANNEL, 1, U16to2U8(0x2031),
	VP_EVT_WHAT_CAN_I_SAY, 0,
	VP_EVT_CONNECTION_STATUS, 0,
	VP_EVT_CHECK_BATTERY, 0,
	VP_EVT_CANCEL, 0,
	VP_EVT_VOICE_PROMPT_EXAMPLE, 0,
	VP_EVT_TAKE_THE_CALL, 0,
	VP_EVT_REJECT, 0,
	VP_EVT_REJECT_PHONE_CALL, 0,
	VP_EVT_PAIRING_FOR_VC, 0,
	VP_EVT_LAST_CALL_OUT, 0,
	VP_EVT_VOICE_DIAL_FOR_VC, 0,
	VP_EVT_VOICE_COMMAND_EXAMPE_SET0, 0,
	VP_EVT_VOICE_COMMAND_EXAMPE_SET1, 0,
	VP_EVT_VOICE_COMMAND_EXAMPE_SET2, 0,
	VP_EVT_MAKE_A_CALL, 0,
	VP_EVT_CHECK_STATUS, 0,
	VP_EVT_RING_BACK, 0,
	VP_EVT_BEEP, 0,
	VP_EVT_INCOMING_CALL_ENDED, 0,
	VP_EVT_CALLER_ID, 0,
	VP_EVT_NUMBER, 0,
	VP_EVT_CALLER_ID_PREFIX, 0,
	VP_EVT_CALLER_ID_SUFFIX, 0,
};

/**************************************************************************************************
* Main Function Print
**************************************************************************************************/
int main()
{
	U16 i;
	
	DBG_LOG_APP_DSP_CONTROL("Language:\n", 0);
	for(i = 0; i < sizeof(VP_LANG_NVKEY_STRU); i++)
	{
		DBG_LOG_APP_DSP_CONTROL("%02X \n", 1, ((U8 *)&gVpLangDefault)[i]);
	}
	
	DBG_LOG_APP_DSP_CONTROL("Chinese event:\n",0);
	for(i = 0; i < sizeof(gVpEventDefault_CHI); i++)
	{
		DBG_LOG_APP_DSP_CONTROL("%02X \n", 1, ((U8 *)gVpEventDefault_CHI)[i]);
	}
	
	DBG_LOG_APP_DSP_CONTROL("English event:\n", 0);
	for(i = 0; i < sizeof(gVpEventDefault_ENG); i++)
	{
		DBG_LOG_APP_DSP_CONTROL("%02X \n", 1, ((U8 *)gVpEventDefault_ENG)[i]);
	}
	
	system("pause");
	return 0;
}

