/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */

#include "types.h"
#include "log.h"

log_create_module(LOG_GERNERAL, PRINT_LEVEL_INFO);
log_create_module(LOG_OS, PRINT_LEVEL_INFO);


/* example */
LOG_STRING_NEW char exampleLogString1[] = "This is Example Log String1 %s";
LOG_STRING_NEW char testString[2][MAX_LOG_STRING] ={
	"THIS IS TEST STRING1",
	"THIS IS TEST STRING2"
};

#if (!LABTEST)
//#if 0
/* DSP */

LOG_STRING_NEW char DSP_WarningString[][64] =
{
    "Invalid type",                                                 /*DSP_WARNING_RESERVED*/
    "Sink Buffer Empty. Type:$",                                    /*DSP_WARNING_SINK_EMPTY*/
    "Disable Streaming. Source:$, Sink:$",                          /*DSP_WARNING_STREAMING_DISABLE*/
    "Memory Flush. Task:$, Count:$.",                               /*DSP_WARNING_MEMORY_FLUSH*/
    "Feature Ptr Null. Source:$, Sink:$",                           /*DSP_WARNING_FEATURE_NULL*/
    "SCO Wait For DM2L setup, Direction:$",                         /*DSP_WARNING_SCO_WAIT_DM2L*/
    "SBC In Frame Mismatch.In:$, Parser:$, skip:$",                 /*DSP_WARNING_SBC_FRAME_MISMATCH*/
    "SBC In Frame Error",                                           /*DSP_WARNING_SBC_FRAME_ERROR*/
    "Modify in_size SourceRead:$, MallocSize:$",                    /*DSP_WARNING_CALLBACK_READSIZE_MODIFICATION*/
    "Feature Frame Size Mismatch, Feature:$, Size:$",               /*DSP_WARNING_FEATURE_FRAME_MISMATCH*/
    "Compensation Max. Source:$, Sink:$, Value:$",                  /*DSP_WARNING_DRIFT_COMPENSATION_MAXIMUM*/
    "Wait SRC Done",                                                /*DSP_WARNING_WAIT_SRC_DONE*/
    "Try to disable SRC Clock",                                     /*DSP_WARNING_TRY_TO_DISABLE_CLOCK*/
    "Sink zero padding wait too long audio:$, vp:$",                /*DSP_WARNING_ZEROPADDING_DPC_TIMEOUT*/
    "Update feature fail, Feature:$",                               /*DSP_WARNING_UPDATE_FEATURE_FAIL*/
    "Source Empty. Type:$",                                         /*DSP_WARNING_SOURCE_EMPTY*/
    "Resolution Mismatch. Codec out:$, Feature:$",                  /*DSP_WARNING_CALLBACK_RESOLUTION_MISMATCH*/
    "AMA Data Source Full",                                         /*DSP_WARNING_AMA_SOURCE_FULL*/
};


/* AMA Core */
LOG_STRING_NEW char AMA_CoreMediaControlString[][MAX_LOG_STRING] =
{
    "PLAY",
    "PAUSE",
    "NEXT",
    "PREVIOUS",
    "PALA_PAUSE"
};
LOG_STRING_NEW char AMA_CoreSpeechState[][MAX_LOG_STRING] =
{
    "IDLE",
    "LISTENING",
    "PROCESSING",
    "SPEAKING",
};
LOG_STRING_NEW char AMA_CoreCeString[][MAX_LOG_STRING] =
{
    "ce_response",
    "ce_provide_speech",
    "ce_start_speech",
    "ce_stop_speech",
    "ce_endpoint_speech",
    "ce_notify_speech_state",
    "ce_get_device_information",
    "ce_get_device_configuration",
    "ce_override_assistant",
    "ce_start_setup",
    "ce_complete_setup",
    "ce_notify_device_configuration",
    "ce_update_device_information",
    "ce_notify_device_information",
    "ce_upgrade_transport",
    "ce_switch_transport",
    "ce_forward_at_command",
    "ce_incoming_call",
    "ce_synchronize_settings",
    "ce_reset_connection",
    "ce_keep_alive",
    "ce_remove_device",
    "ce_issue_media_control",
    "ce_get_state",
    "ce_set_state",
    "ce_synchronize_state",
    "ce_get_central_information",
    "ce_command",
    "ce_unknow"
    "CE_UNKNOW_TAGS"
};
LOG_STRING_NEW char AMA_CoreRspString[][MAX_LOG_STRING] =
{
    "rsp_device_information",
    "rsp_state",
    "rsp_connection_details",
    "rsp_device_configuration",
    "rsp_central_information",
    "rsp_dialog",
    "rsp_speech_provider",
    "rsp_error_code"
    "RSP_UNKNOW_TAGS"
};

#endif

#if (!LABTEST)

/*APP System*/

LOG_STRING_NEW char success_log_string[] = "SUCCESS";
LOG_STRING_NEW char fail_log_string[] = "fail";


/* APP HFP*/
LOG_STRING_NEW char APP_HFPMsg[][MAX_LOG_STRING] =
{
	"HFP_START_SERVICE_CFM",
	"HFP_STOP_SERVICE_CFM",
	"HFP_CONNECT_IND",
	"HFP_DISCONNECT_CFM",
	"HFP_DISCONNECT_IND",
	"HFP_CONNECT_CFM",
	"HFP_AG_ERROR_CODE_IND",
	"HFP_AG_EXT_ERROR_IND",
	"HFP_SUSCRIBER_NUM_IND",
	"HFP_CALLER_NUM_IND",
	"HFP_CURRENT_CALL_LIST_IND",
	"HFP_INBAND_RINGTONE_IND",
	"HFP_RESPONSE_HOLD_IND",
	"HFP_RING_IND",
	"HFP_PLUS_VGS_IND",
	"HFP_PLUS_VGM_IND",
	"HFP_SERVICE_IND",
	"HFP_CALL_IND",
	"HFP_CALLSETUP_IND",
	"HFP_CALLHELD_IND",
	"HFP_SIGNAL_IND",
	"HFP_ROAM_IND",
	"HFP_BATCHG_IND",
	"HFP_APPLE_SIRI_IND",
	"HFP_UNKNOWN_RESULT_CODE_IND",
	"HFP_AT_ACCEPT_CALL_CFM",
	"HFP_AT_AG_ERROR_CODE_CFM",
	"HFP_AT_APL_EFM_CFM",
	"HSP_AT_BUTTON_PRESS_CFM",
	"HFP_AT_CALL_WAITING_CFM",
	"HFP_AT_CODEC_SELECT_CFM",
	"HFP_AT_INIT_SCO_CONN_CFM",
	"HFP_AT_NREC_CFM",
	"HFP_AT_REDIAL_CFM",
	"HFP_AT_TERMINATE_CALL_CFM",
	"HFP_AT_VGS_CFM",
	"HFP_AT_VGM_CFM",
	"HFP_AT_VOICE_DIAL_CFM",
	"HFP_AT_VENDOR_IND",
	"HFP_AT_VENDOR_TIMEOUT_IND",
	"HFP_AT_VENDOR_OK_IND",
	"HFP_AT_VENDOR_ERROR_IND",
};

LOG_STRING_NEW char APP_HFPScoLinkType[][MAX_LOG_STRING] =
{
	"SCO",
	"ACL",
	"eSCO",
	"SCO_ONLY_HV3"
};

LOG_STRING_NEW char APP_HFPScoHandle[][MAX_LOG_STRING] =
{
    "BT_SYNC_REGISTER_CFM",
    "BT_SYNC_UNREGISTER_CFM",
    "BT_SYNC_CONNECT_CFM",
    "BT_SYNC_CONNECT_IND",
    "BT_SYNC_DISCONNECT_CFM",
    "BT_SYNC_DISCONNECT_IND",
    "BT_SYNC_RENEGOTIATE_IND"
};

/*APP AVRCP*/
LOG_STRING_NEW char APP_AvrcpRegNotifyRspEvtID[][64] =
{
	"",
	"AVRCP_EVENT_ID_PLAYBACK_STATUS_CHANGED",
	"AVRCP_EVENT_ID_TRACK_CHANGED",
	"AVRCP_EVENT_ID_TRACK_REACHED_END",
	"AVRCP_EVENT_ID_TRACK_REACHED_START",
	"AVRCP_EVENT_ID_PLAYBACK_POS_CHANGED",
	"AVRCP_EVENT_ID_BATT_STATUS_CHANGED",
	"AVRCP_EVENT_ID_SYSTEM_STATUS_CHANGED",
	"AVRCP_EVENT_ID_PLAYER_APPLICATION_SETTING_CHANGED",
	"AVRCP_EVENT_ID_NOW_PLAYING_CONTENT_CHANGED",
	"AVRCP_EVENT_ID_AVAILABLE_PLAYERS_CHANGED",
	"AVRCP_EVENT_ID_ADDRESSED_PLAYER_CHANGED",
	"AVRCP_EVENT_ID_UIDS_CHANGED",
	"AVRCP_EVENT_ID_VOLUME_CHANGED"
};

LOG_STRING_NEW char APP_AvrcpIndID[][MAX_LOG_STRING] =
{
	//Initialization, Connection Confirm
	"AVRCP_START_SERVICE_CFM",
	"AVRCP_STOP_SERVICE_CFM",
	"AVRCP_CONNECT_CFM",
	"AVRCP_DISCONNECT_CFM",
	//Initialization, Connection Indication
	"AVRCP_CONNECT_IND",
	//Received Command Indication -- to MMI
	"AVRCP_GET_CMD_UNITINFO_IND",
	"AVRCP_GET_CMD_SUBUNITINFO_IND",
	"AVRCP_GET_CMD_GETCAPS_IND",
	"AVRCP_GET_CMD_GETELEMENTATTRIBUTES_IND",
	"AVRCP_GET_CMD_REGISTERNOTIFICATION_IND",
	//AVRCP_GET_CMD_REGISTERNOTIFICATION_VOL_IND,
	"AVRCP_GET_CMD_SETABSOLUTEVOL_IND",
	"AVRCP_GET_CMD_UNKNOWNVENDORDEPENDENT_IND",
	"AVRCP_GET_CMD_PASSTHROUGH_IND",
	"AVRCP_GET_CMD_PASSTHROUGH_VENDORUNIQUE_IND",
	//Response Information Indication
	"AVRCP_GET_APPLICATION_SETTING_IND",
	"AVRCP_GET_PLAY_STATUS_IND",
	"AVRCP_GET_REGISTER_NOTIFY_IND",
	"AVRCP_GET_PASS_THROUGH_IND",
	"AVRCP_GET_ELEMENT_ATTRIBUTE_IND",
	"AVRCP_GET_CABILITY_IND",
	//Get Response Confirm -- to MMI
	//Send Command
	"AVRCP_INTERNAL_SEND_CMD_UNITINFO",
	"AVRCP_INTERNAL_SEND_CMD_SUBUNITINFO",
	"AVRCP_INTERNAL_SEND_CMD_GETCAPS",
	"AVRCP_INTERNAL_SEND_CMD_GETELEMENTATTRIBUTES",
	"AVRCP_INTERNAL_SEND_CMD_REGISTERNOTIFICATION",
	"AVRCP_INTERNAL_SEND_CMD_SETABSOLUTEVOL",
	"AVRCP_INTERNAL_SEND_CMD_PASSTHROUGH",
	"AVRCP_INTERNAL_SEND_CMD_CONTNUERESPONSE",
	"AVRCP_INTERNAL_SEND_CMD_VENDORUNIQUE",
	"AVRCP_INTERNAL_SEND_CMD_GETPLAYSTATUS",
	"AVRCP_INTERNAL_SEND_CMD_LISTAPPATTRIBUTE",
	"AVRCP_INTERNAL_SEND_CMD_LISTAPPVALUE",
	"AVRCP_INTERNAL_SEND_CMD_GETAPPVALUE",
	"AVRCP_INTERNAL_SEND_CMD_SETAPPVALUE",
	"AVRCP_INTERNAL_SEND_CMD_GETAPPATTRIBUTETEXT",
	"AVRCP_INTERNAL_SEND_CMD_GETAPPVALUETEXT",
	//Send Response
	"AVRCP_INTERNAL_SEND_RSP_UNITINFO",
	"AVRCP_INTERNAL_SEND_RSP_SUBUNITINFO",
	"AVRCP_INTERNAL_SEND_RSP_GETCAPS",
	"AVRCP_INTERNAL_SEND_RSP_GETELEMENTATTRIBUTES",
	"AVRCP_INTERNAL_SEND_RSP_REGISTERNOTIFICATION_VOL",
	"AVRCP_INTERNAL_SEND_RSP_SETABSOLUTEVOL",
	"AVRCP_INTERNAL_SEND_RSP_VENDORDEPENDENTREJECT",
	"AVRCP_INTERNAL_SEND_RSP_PASSTHROUGH",
	"AVRCP_INTERNAL_SEND_RSP_GETPLAYSTATUS",
	"AVRCP_INTERNAL_SEND_RSP_LISTAPPATTRIBUTE",
	"AVRCP_INTERNAL_SEND_RSP_LISTAPPVALUE",
	"AVRCP_INTERNAL_SEND_RSP_GETCURRENTAPPVALUE",
	"AVRCP_INTERNAL_SEND_RSP_SETAPPVALUE",
	"AVRCP_INTERNAL_SEND_RSP_GETAPPATTRIBUTETEXT",
	"AVRCP_INTERNAL_SEND_RSP_GETAPPVALUETEXT",
	//Changed Response
	"AVRCP_INTERNAL_SEND_RSP_PLAYBACKSTATUSCHANGED",
	"AVRCP_INTERNAL_SEND_RSP_TRACKCHANGED",
	"AVRCP_INTERNAL_SEND_RSP_TRACKREACHEDEND",
	"AVRCP_INTERNAL_SEND_RSP_TRACKREACHEDSTART",
	"AVRCP_INTERNAL_SEND_RSP_PLAYBACKPOSCHANGED",
	"AVRCP_INTERNAL_SEND_RSP_SYSTEMSTATUSCHANGED",
	"AVRCP_INTERNAL_SEND_RSP_PLAYSTATUSCHANGED",
	"AVRCP_INTERNAL_SEND_RSP_PLAYERAPPSETTINGCHANGED",
	"AVRCP_INTERNAL_SEND_RSP_VOLCHANGED"
};

LOG_STRING_NEW char APP_AvrcpTimerID[][MAX_LOG_STRING] =
{
	"",
	"APPAVC_TIMER_SEND_GET_PLAY_STATUS_TO_PAUSE_MUSIC",
	"APPAVC_TIMER_SEND_PAUSE_MUSIC",
	"APPAVC_TIMER_QUERY_CURRENT_PLAY_STATUS",
	"APPAVC_TIMER_MONITOR_PLAY_STATUS",
	"APPAVC_TIMER_BACKUP_AND_PUSH_PLAY_STATUS",
	"APPAVC_TIMER_CHECK_STREAMING_STATE_LATER"
};


/*	AVRCP	*/
LOG_STRING_NEW char Avrcp_Opcode_String[][MAX_LOG_STRING] =
{
	"AVC_OPCODE_VENDOR_DEPENDENT",
	"AVC_OPCODE_UNIT_INFO",
	"AVC_OPCODE_SUBUNIT_INFO",
	"AVC_OPCODE_PASS_THROUGH",
	"AVC_UNKNOWN_OPCODE",
};

LOG_STRING_NEW char AVRCP_TX_RESULT_STR[][MAX_LOG_STRING] =
{
	"Success",
	"Fail",
};

LOG_STRING_NEW char AVRCP_TX_CMD_RSP_STR[][MAX_LOG_STRING] =
{
	"Get Capabilities",//0,
	"Get Element Attributes",
	"Register Notification",
	"Set AbsoluteVolume",
	"Pass Through",
	"Vendor Unique",//5
	"Get PlayStatus",
	"Get Player Application",
	"Set Player Application",
	"Continue Response",
	"UnitInfo",//10,
	"SubunitInfo",
	"Register Notification Volume Interim",
	"Unknown Vendor Dependent",
	"Volume Changed",
};

LOG_STRING_NEW char AVRCP_PDU_ID_STR[][MAX_LOG_STRING] =
{
	"AVRCP_PDU_ID_GET_CAPABILITIES",
	"AVRCP_PDU_ID_GET_ELEMENT_ATTRIBUTES",
	"AVRCP_PDU_ID_REGISTER_NOTIFICATION",
	"AVRCP_PDU_ID_SET_ABSOLUTE_VOLUME",
	"AVRCP_PDU_ID_UNKNOWN",
};

LOG_STRING_NEW char AVRCP_OPID_STR[][MAX_LOG_STRING] =
{
	"AVC_OPERATION_POWER",				//0x00
	"AVC_OPERATION_VOL_UP",
	"AVC_OPERATION_VOL_DOWN",
	"AVC_OPERATION_MUTE",
	"AVC_OPERATION_PLAY",
	"AVC_OPERATION_STOP",				//0x05
	"AVC_OPERATION_PAUSE",
	"AVC_OPERATION_RECORD",
	"AVC_OPERATION_REWIND",
	"AVC_OPERATION_FAST_FORWARD",
	"AVC_OPERATION_EJECT",				//0x0A
	"AVC_OPERATION_FORWARD",
	"AVC_OPERATION_BACKWARD",
	//Airoha
	"AVC_OPERATION_INTERNAL_REWIND_RELEASE",
	"AVC_OPERATION_INTERNAL_FAST_FORWARD_RELEASE",

	"AVC_OPERATION_VENDOR_UNIQUE",		//0x0F

	"AVC_OPERATION_KEY_PLAY",			//0x10
	"AVC_OPERATION_KEY_PAUSE",
	"AVC_OPERATION_FORCE_PLAY",
	"AVC_OPERATION_GET_REPEAT_MODE",
	"AVC_OPERATION_GET_SHUFFLE_MODE",
	"AVC_OPERATION_GET_PLAY_STATUS",
	"AVC_OPERATION_SET_REPEAT_MODE",	//0x16
	"AVC_OPERATION_SET_SHUFFLE_MODE",

	"AVC_OPERATION_UNKNOWN"
};

/*Profile HFP*/

LOG_STRING_NEW char HFP_TIMER_STR[][MAX_LOG_STRING] =
{
	"HFP_TIMER_SLC",
	"HFP_TIMER_ATCMD",
	"HFP_TIMER_BATXAPL",
	"HFP_TIMER_BATXEVENT",
	"HFP_TIMER_BATMONITOR",
	"HFP_TIMER_BVRA",
	"HFP_TIMER_START_SLC",
	"HFP UNKNOWN TIMER",
    "HFP_TIMER_NREC",
    "HFP_TIMER_APLSIRI"
};

LOG_STRING_NEW char HFP_SDP_CFM_STR[][MAX_LOG_STRING] =
{
	"BT_SDP_REGISTER_CFM",
	"BT_SDP_UNREGISTER_CFM",
	"BT_SDP_OPEN_SEARCH_CFM",
	"BT_SDP_CLOSE_SEARCH_CFM",
	"BT_SDP_SERVICE_SEARCH_CFM",
	"BT_SDP_ATTRIBUTE_SEARCH_CFM",
	"BT_SDP_SERVICE_SEARCH_ATTRIBUTE_CFM",
	"BT_SDP_SERVER_CONNECT_IND",
	"BT_SDP_SERVER_DISCONNECT_IND",
	"HFP SDP UNKNOWN CFM",
};

LOG_STRING_NEW char HFP_RFCOMM_STR[][MAX_LOG_STRING] =
{
	"MESSAGE_MORE_DATA",
	"MESSAGE_MORE_SPACE",
	"BT_RFCOMM_REGISTER_CFM",
	"BT_RFCOMM_UNREGISTER_CFM",
	"BT_RFCOMM_CLIENT_CONNECT_CFM",
	"BT_RFCOMM_SERVER_CONNECT_CFM",
	"BT_RFCOMM_CONNECT_IND",
	"BT_RFCOMM_LINE_STATUS_CFM",
	"BT_RFCOMM_DISCONNECT_IND",
	"BT_RFCOMM_DISCONNECT_CFM",
	"HFP RFCOMM UNKNOWN MSG",
};

LOG_STRING_NEW char HFP_SCO_CODEC_STR[][MAX_LOG_STRING] =
{
	"SCO_CODEC_NONE",
	"SCO_CODEC_CVSD",
	"SCO_CODEC_MSBC",
};

LOG_STRING_NEW char HFP_PROFILE_STATE_STR[][MAX_LOG_STRING] =
{
	"PROFILE_DISCONNECTED",//0
	"PROFILE_CONNECTING_SDP",
	"PROFILE_CONNECTING_PROTOCOL",
	"PROFILE_CONNECTED",
	"PROFILE_DISCONNECTING",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"PROFILE_STATE_START",
};

LOG_STRING_NEW char HFP_CMD_STATE_STR[][MAX_LOG_STRING] =
{
	"HFP_CMD_STATE_IDLE",					//0
	"HSP_CMD_STATE_SLC_ESTABLISH",
	"HFP_CMD_STATE_SLC_ESTABLISH",
	"HFP_CMD_STATE_ATA",
	"HFP_CMD_STATE_ATD_NUMBER",
	"HFP_CMD_STATE_AT_APLEFM_ENABLE",		//5
	"HFP_CMD_STATE_AT_APLEFM_DISABLE",
	"HFP_CMD_STATE_AT_APLSIRI",
	"HFP_CMD_STATE_AT_BAC",
	"HFP_CMD_STATE_AT_BCC",
	"HFP_CMD_STATE_AT_BCS",				//10
	"HFP_CMD_STATE_AT_BIA",
	"HFP_CMD_STATE_AT_BIEV_BAT_SEND",
	"HFP_CMD_STATE_AT_BIND",
	"HFP_CMD_STATE_AT_BIND_EQUAL_QUES",
	"HFP_CMD_STATE_AT_BINP",				//15
	"HFP_CMD_STATE_AT_BLDN",
	"HFP_CMD_STATE_AT_BRSF",
	"HFP_CMD_STATE_AT_BTRH_QUES",
	"HFP_CMD_STATE_AT_BTRH_ACCEPT",
	"HFP_CMD_STATE_AT_BTRH_REJECT",		//20
	"HFP_CMD_STATE_AT_BVRA_ENABLE",
	"HFP_CMD_STATE_AT_BVRA_DISABLE",
	"HFP_CMD_STATE_AT_CHLD_EQUAL_QUES",
	"HFP_CMD_STATE_AT_CHLD",
	"HFP_CMD_STATE_AT_CHUP",				//25
	"HFP_CMD_STATE_AT_CIND_EQUAL_QUES",
	"HFP_CMD_STATE_AT_CIND_QUES",
	"HSP_CMD_STATE_AT_CKPD200",
	"HFP_CMD_STATE_AT_CLCC",
	"HFP_CMD_STATE_AT_CMEE_ENABLE",		//30
	"HFP_CMD_STATE_AT_CMEE_DISABLE",
	"HFP_CMD_STATE_AT_CMER",
	"HFP_CMD_STATE_AT_CNUM",
	"HFP_CMD_STATE_AT_CNUM_QUES",
	"HFP_CMD_STATE_AT_CLIP_ENABLE",		//35
	"HFP_CMD_STATE_AT_CLIP_DISABLE",
	"HFP_CMD_STATE_AT_CCWA_ENABLE",
	"HFP_CMD_STATE_AT_CCWA_DISABLE",
	"HFP_CMD_STATE_AT_CSCS",
	"HFP_CMD_STATE_AT_COPS",				//40
	"HFP_CMD_STATE_AT_COPS_QUES",
	"HFP_CMD_STATE_AT_IPHONE_BAT_SEND",
	"HFP_CMD_STATE_AT_NREC_ENABLE",
	"HFP_CMD_STATE_AT_NREC_DISABLE",
	"HFP_CMD_STATE_AT_VGS",				//45
	"HFP_CMD_STATE_AT_VGM",
	"HFP_CMD_STATE_AT_VTS",
	"HFP_CMD_STATE_AT_XAPL",
	"HFP_CMD_STATE_AT_XEVENT_BAT_INQ",
	"HFP_CMD_STATE_AT_XEVENT_BAT_SEND",
};

LOG_STRING_NEW char HFP_RESULT_CODE_STR[][MAX_LOG_STRING] =
{
	"HFP_RESULT_CODE_RING",										//0
	"HFP_RESULT_CODE_PLUS_BRSF",
	"HFP_RESULT_CODE_PLUS_CIND",
	"HFP_RESULT_CODE_PLUS_CHLD",
	"HFP_RESULT_CODE_PLUS_VGM",
	"HFP_RESULT_CODE_PLUS_VGS",									//5
	"HFP_RESULT_CODE_OK",
	"HFP_RESULT_CODE_ERROR",
	"HFP_RESULT_CODE_CIEV",
	"HFP_RESULT_CODE_PLUS_BVRA",
	"HFP_RESULT_CODE_PLUS_COPS",									//10
	"HFP_RESULT_CODE_PLUS_BTRH",
	"HFP_RESULT_CODE_PLUS_BSIR",
	"HFP_RESULT_CODE_PLUS_CNUM",
	"HFP_RESULT_CODE_PLUS_CME",
	"HFP_RESULT_CODE_PLUS_CLCC",									//15
	"HFP_RESULT_CODE_PLUS_CLIP",
	"HFP_RESULT_CODE_PLUS_CCWA",
	"HFP_RESULT_CODE_PLUS_BINP",
	"HFP_RESULT_CODE_PLUS_XAPL",
	"HFP_RESULT_CODE_PLUS_BCS",									//20
	"HFP_RESULT_CODE_PLUS_BIND",
	"HFP_RESULT_CODE_PLUS_APLSIRI",
	"HFP_RESULT_CODE_NO_CARRIER",									//23
	"HFP_RESULT_CODE_BUSY",
	"HFP_RESULT_CODE_NO_ANSWER",
	"HFP_RESULT_CODE_DELAYED	",
	"HFP_RESULT_CODE_BLACKLISTED",
	"HFP_ERROR_RESULT_CODE_END",
};

LOG_STRING_NEW char HFP_PUSH_CMD_STR[][MAX_LOG_STRING] =
{
	"HFP_CMD_IDLE",
	"HFP_CMD_SEND",
	"HFP_CMD_POP_INTERNAL_CMD",
	"HFP_CMD_COUNT",

	"HFP_CMD_INTERNAL_POP_CMD",
	"HFP_CMD_INTERNAL_START",
	"HFP_CMD_INTERNAL_EN_CALL_WAITING_NOTIFICAITON",		//0x06
	"HFP_CMD_INTERNAL_SELECT_CHAR_SET_UTF8",				//0x07
	"HFP_CMD_INTERNAL_ENABLE_CLI_NOTIFICATION",				//0x08
	"HFP_CMD_INTERNAL_SET_AG_NREC_OFF",						//0x09
	"HFP_CMD_INTERNAL_ACTIVATE_INDICATOR",					//0x0A
	"HFP_CMD_INTERNAL_XAPL",								//0x0B
	"HFP_CMD_INTERNAL_XEVENT_BATTERY_INQUIRY",				//0x0C
	"HFP_CMD_INTERNAL_IPHONEACCEV",							//0x0D
	"HFP_CMD_INTERNAL_XEVENT_BATTERY_SEND",					//0x0E
	"HFP_CMD_INTERNAL_BIEV_SEND",							//0x0F
	"HFP_CMD_INTERNAL_SLC_VGS_CMD",							//0x10
	"HFP_CMD_INTERNAL_END",									//0x11
	"HFP UNKNOWN CMD"
};

LOG_STRING_NEW char PM_ConflictStateLogString[][MAX_LOG_STRING] =
{
	"IDLE",
	"SDP_CONN_NOT_ALLOW_WAIT",
	"SDP_CONN_EXIST_WAIT",
	"ACL_OPEN_WAIT",
};

LOG_STRING_NEW char PM_ConflictEventLogString[][MAX_LOG_STRING] =
{
	"SDP_CONN_NOT_ALLOW",
	"SDP_CONN_ALREADY_EXIST",
	"CONN_NOT_ALLOW_TIMER_EXPIRE",
	"CONN_EXIST_TIMER_EXPIRE",
	"ACL_OPEN",
	"ENCRIPTION_ON",
	"ACL_IDLE_TIMER_EXPIRE",
	"ACL_CLOSE",
	"ACTIVE_RECONNECT",
	"CLEAR_INFO",
};

/* Sound Level Component */
LOG_STRING_NEW char APP_VolComponentLogString[][MAX_LOG_STRING] =
{
	"COMPONENT_SCO_WB",
	"COMPONENT_SCO_NB",
	"COMPONENT_A2DP",
	"COMPONENT_LINEIN",
	"COMPONENT_VPRT",
	"COMPONENT_MIC_SCO",
	"COMPONENT_MP3",
	"COMPONENT_MIC_A2DP",
	"COMPONENT_AIROTHRU_SPK",
	"COMPONENT_AIROTHRU_MIC",
};

/* PEQ Component */
LOG_STRING_NEW char APP_PeqComponentLogString[][MAX_LOG_STRING] =
{
	"PEQ_A2DP",
	"PEQ_LINEIN",
	"PEQ_MP3"
};

/* PEQ Phase */
LOG_STRING_NEW char APP_PeqPhaseLogString[][MAX_LOG_STRING] =
{
	"DSP_PEQ_USER",
	"DSP_PEQ_SPEAKER",
};


/*Key Event*/
LOG_STRING_NEW char APP_KeyIndexLogString[][MAX_LOG_STRING] =
{
	"KEY1",
	"KEY2",
	"KEY3",
	"KEY4",
	"KEY5",
	"KEY6",
	"KEY7",
	"KEY8",
	"KEY9",
	"KEY10",
	"TOTAL_KEY_NUM",//10
	"KEYALL",
	"KEYNONE",
	"KEY_PWR",
	"KEY_COMB_34",//14
	"KEY_COMB_23",//15
	"KEY_COMB_13",//16
	"KEY_COMB_24",//17
	"KEY_COMB_14",//18
	"KEY_COMB_12",//19
	"KEY_COMB_123",//20
	"KEY_COMB_124",//21
	"KEY_COMB_134",//22
	"KEY_COMB_234",//23
	"KEY_COMB_1234"//24
};

LOG_STRING_NEW char APP_ActionLogString[][MAX_LOG_STRING] =
{
	"TAP",
	"PRESS",
	"PRESS_RELEASE",
	"LONGPRESS",
	"LONGPRESS_RELEASE",
	"DOUBLE",
	"TRIPLE",
	"LONGLONGPRESS",
	"LONGLONGPRESS_RELEASE",
	"EXTREMELY_LONGPRESS",
	"EXTREMELY_LONGPRESS_RELEASE",
	"REPEAT",
	"DOWN",
	"UP",
	"BUTTON_SEQUENCE1_TIMEOUT"
};

LOG_STRING_NEW char APP_KeyEventLogString[][MAX_LOG_STRING] =
{
	"INVALID",
	"RECONNECT_USER_INIT",
	"DISCOVERABLE",
	"NONDISCOVERABLE",
	"CONNECTED_TO_DISCOVERABLE",
	"CONNECTED_TO_CONNECTABLE",
	"NFC_DISCOVREABLE",
	"CONFIRMATION_ACCEPT",
	"CONFIRMATION_REJECT",
	"DEBUG_KEY_TOGGLE",
	"VOICEUP",
	"VOICEDN",
	"BUZZER_MUTE_TOGGLE",
	"TOGGLE_VOLUME",
	"VOLUME_ORIENTATION_NORMAL",
	"VOLUME_ORIENTATION_INVERT",
	"TOGGLE_LED",
	"ENABLE_LED",
	"DISABLE_LED",
	"CANCEL_LED_INDICATION",
	"MEDIA_TRIGGER_1",
	"MEDIA_TRIGGER_2",
	"POWER_ON_THEN_ENTERDISCOVERABLE",
	"POWER_ON",
	"POWER_OFF",
	"RESET",
	"RESET_PAIRED_DEVICES",
	"MAX_DEVICE_ALLOWED_UP",
	"MAX_DEVICE_ALLOWED_DOWN",
	"MAX_DEVICE_ALLOWED_TOGGLE",
	"RECONNECT_AFTER_POWER_ON",
	"VOICE_PROMPT_TOGGLE",
	"VOICE_PROMPT_ENABLE",
	"VOICE_PROMPT_DISABLE",
	"VOICE_PROMPT_LANG_CHANGE",
	"VOICE_PROMPT_LANG_SELECT",
	"VOICE_PROMPT_LANG_CONFIRM",
	"TEST_VOICE_PROMPT_PLAY",
	"TEST_VOICE_PROMPT_NEXT",
	"BUTTONLOCKON",
	"BUTTONLOCKOFF",
	"BUTTONLOCKTOGGLE",
	"VOICE_COMMAND_ENABLE",
	"MICUP",
	"MICDN",
	"MIC_MUTE_TOGGLE",
	"MIC_MUTE_ON",
	"MIC_MUTE_OFF",
	"AIR_ENTER_AIR_PAIRING",
	"AIR_EXIT_AIR_PAIRING",
	"AUDIO_TRANSFER",
	"SET_VOICE_RECOGNITION",
	"RDIAL",
	"DIALMEM",
	"DIALNUM",
	"CNLOUTGOING",
	"REJCALL",
	"REJCALL_SECOND_PHONE",
	"ONHOLD_CALL",
	"ACPCALL",
	"ENDCALL",
	"3WAYRELNUDUB",
	"3WAYRELNACP",
	"3WAYRELNACP_X",
	"3WAYHOLDNACP",
	"3WAYHOLDNACP_X",
	"3WAYADD",
	"3WAYCALLTRANSFER",
	"HSP_BUTTON_PRESSED",
	"DISABLE_NREC",
	"GETCALLNUM",
	"QUERY_CALL_LIST",
	"SEND_DTMF",
	"ATTACH_LAST_VOICE_TAG_RECORDED",
	"SEND_CLIP",
	"SET_VOICE_RECOGNITION_SECONDARY",
	"RDIAL_SECONDARY",
	"SET_VOICE_RECOGNITION_CANCEL",
	"SET_VOICE_RECOGNITION_SECONDARY_CANCEL",
	"SIRI_START_OR_CONTINUE",
	"SIRI_END",
	"SIRI_START_OR_CONTINUE_SECONDARY",
	"SIRI_END_SECONDARY",
	"AVRCP_PLAY",
	"AVRCP_STOP",
	"AVRCP_PAUSE",
	"AVRCP_RECORD",
	"AVRCP_REWIND_PUSH",
	"AVRCP_FAST_FORWARD_PUSH",
	"AVRCP_EJECT",
	"AVRCP_FORWARD",
	"AVRCP_BACKWARD",
	"AVRCP_REWIND_RELEASE",
	"AVRCP_FAST_FORWARD_RELEASE",
	"AVRCP_REPEAT_MODE_CHANGE",
	"AVRCP_SHUFFLE_MODE_CHANGE",
	"AVRCP_ACTIVE_TOGGLE",
	"PEQ_MODE_CHANGE",
	"FM_POWERON",
	"FM_POWEROFF",
	"SEEKUP",
	"SEEKDOWN",
	"TUNEUP",
	"TUNEDN",
	"FM_MUTETOGGLE",
	"ENTER_LINEIN_MODE",
	"EXIT_LINEIN_MODE",
	"LINEIN_MUTE_TOGGLE",
	"ENTER_TESTMODE",
	"SWITCH_TEST_MODE_CHANNEL",
	"SWITCH_TEST_MODE_POWER",
	"SWITCH_TEST_MODE_STATE",
	"SWITCH_TEST_MODE_TX_PACKET_TYPE",
	"SCO_SWITCH",
	"AIR_ENTER_AIR_SECURE_PAIRING",
	"MULTI_A2DP_PLAY_MODE_TOGGLE",
	"CHECK_STATUS_OF_CONNECTION",
	"WHAT_CAN_I_SAY",
	"LEFT_CHANNEL",
	"RIGHT_CHANNEL",
	"STEREO_CHANNEL",
	"VOICE_COMMAND_CANCEL",
	"VOICE_MAKE_A_CALL",
	"CHECK_STATUS",
	"CHANGE_SOUND_EFFECT",
	"CONTROL_DBB_ON_OFF",
	"CONTROL_MIC_A2DP_MODE",
	"SELFIE",
	"ENABLE_DUT_MODE_COMMAND",
	"MIC_L_ENABLE",
	"MIC_R_ENABLE",
	"MIC_TO_SPK_ENABLE",
	"MIC_TO_SPK_DISABLE",
	"ENABLE_EC_NR",
	"DISABLE_EC_NR",
	"2K_TONE_ENABLE",
	"2K_TONE_DISABLE",
	"SWITCH_STEREO_MONO",
	"SWITCH_SELFIE",
	"AIROTHRU",
	"ROLE_CHANGE",
	"MP3_POWERON",
	"MP3_POWEROFF",
	"MP3_PLAY",
	"MP3_STOP",
	"MP3_PAUSE",
	"MP3_FORWARD",
	"MP3_BACKWARD",
	"ANC_SWITCH",
	"RESET_TO_FACTORY",
	"ANC_ON",
	"ANC_OFF",
	"DSP_RESET",
	"MCSync_CONNECT",
	"MCSync_DISCONNECT",
	"MCSync_ENABLEDISCOVERABLE",
	"MCSync_DISABLEDISCOVERABLE",
	"MCSync_RHO",
	"REPORT_BATTERY_STATUS",
	"SPEECH_TOGGLE",
	"SPEECH_START", //160
	"SPEECH_STOP",//161
	"VAD_ON",
	"VAD_OFF",
	"GAME_MODE_ON",
	"GAME_MODE_OFF",
	"GAME_MODE_TOGGLE",
	"GVA_PRESS",
	"GVA_VOICE_QUERY",
	"GVA_NOTIFY",
	"GVA_CANCEL",
	"GVA_RELEASE",
	"XIAOAI_SPEECH_FUNC_2",
	"XIAOAI_SPEECH_START",
	"XIAOAI_SPEECH_FUNC_1",
	"SHARE_PAIRING_START",
	"SHARE_PAIRING_STOP",
<<<<<<< HEAD
	"AGENT_STARTS_SHARE_MODE",
	"AGENT_STOPS_SHARE_MODE",
	"FOLLOWER_STARTS_SHARE_MODE",
	"FOLLOWER_STOPS_SHARE_MODE",
	"AGENT_TOGGLE_SHARE_MODE",
	"FOLLOWER_TOGGLE_SHARE_MODE",	
=======
	"MASTER_SHARE_MODE_START",
	"MASTER_SHARE_MODE_STOP",
	"FOLLOWER_SHARE_MODE_START",
	"FOLLOWER_SHARE_MODE_STOP",
	"MASTER_SHARE_MODE_TOGGLE",
	"FOLLOWER_SHARE_MODE_TOGGLE",	
>>>>>>> db20e11 (second commit)
	"MIC_TO_SPK_3MIC_MAIN_MIC_ENABLE",
	"MIC_TO_SPK_3MIC_REF1_MIC_ENABLE",
	"MIC_TO_SPK_3MIC_REF2_MIC_ENABLE",
	"MIC_TO_SPK_3MIC_DISABLE",
	"TOTAL_NO"
};

/*State*/
LOG_STRING_NEW char APP_StateLogString[][MAX_LOG_STRING] =
{
	"OFF",
	"CONDISCABLE",
	"CONNECTABLE",
	"CONNECTED",
	"HFP_INCOMMING",
	"HFP_OUTGOING",
	"HFP_CALLACTIVE",
	"HFP_CALLACTIVE_WITHOUT_SCO",
	"HFP_CAIMG",
	"HFP_CAOGG",
	"HFP_CAMULTY",
	"FAKEON",
	"FAKEOFF",
	"DETACHING_LINK",
	"TEST_MODE",
	"FM",
	"LINE_IN",
	"UPDATING",
	"UPDATED_OK",
	"UPDATED_FAIL",
	"VOICE_PROMPT_LANG_SELECT",
	"TWS_PAIRING",
	"INQUIRY",
	"MP_STATE",
	"MP3",
	"STATE_RESERVED2",
	"STATE_RESERVED3",
	"STATE_RESERVED4",
	"STATE_RESERVED5",
	"STATE_RESERVED6",
	"STATE_RESERVED7",
	"TOTAL_STATE_NO"
};

/*Media Event*/
//Start from "MEDIA_EVT_KEY_BASE (0x0001)"
LOG_STRING_NEW char APP_MediaEvent1LogString[][MAX_LOG_STRING] =
{
	//0
	"",
	//0x0001
	"KEY_RECONNECT_USER_INIT",
	"KEY_DISCOVERABLE",
	"KEY_NONDISCOVERABLE",
	"KEY_CONNECTED_TO_DISCOVERABLE",
	"KEY_CONNECTED_TO_CONNECTABLE",
	"KEY_NFC_DISCOVREABLE",
	"KEY_CONFIRMATION_ACCEPT",
	"KEY_CONFIRMATION_REJECT",
	"KEY_DEBUG_KEY_TOGGLE",
	"KEY_VOICEUP",
	"KEY_VOICEDN",
	"KEY_BUZZER_MUTE_TOGGLE",
	"KEY_TOGGLE_VOLUME",
	"KEY_VOLUME_ORIENTATION_NORMAL",
	"KEY_VOLUME_ORIENTATION_INVERT",

	//0x001x
	"KEY_TOGGLE_LED",
	"KEY_ENABLE_LED",
	"KEY_DISABLE_LED",
	"KEY_CANCEL_LED_INDICATION",
	"KEY_MEDIA_TRIGGER_1",
	"KEY_MEDIA_TRIGGER_2",
	"KEY_POWER_ON_THEN_ENTERDISCOVERABLE",
	"KEY_POWER_ON",
	"KEY_POWER_OFF",
	"KEY_RESET",
	"KEY_RESET_PAIRED_DEVICES",
	"KEY_MAX_DEVICE_ALLOWED_UP",
	"KEY_MAX_DEVICE_ALLOWED_DOWN",
	"KEY_MAX_DEVICE_ALLOWED_TOGGLE",
	"KEY_RECONNECT_AFTER_POWER_ON",
	"KEY_VOICE_PROMPT_TOGGLE",

	//0x002x
	"KEY_VOICE_PROMPT_ENABLE",
	"KEY_VOICE_PROMPT_DISABLE",
	"KEY_VOICE_PROMPT_LANG_CHANGE",
	"KEY_VOICE_PROMPT_LANG_SELECT",
	"KEY_VOICE_PROMPT_LANG_CONFIRM",
	"KEY_TEST_VOICE_PROMPT_PLAY",
	"KEY_TEST_VOICE_PROMPT_NEXT",
	"KEY_BUTTONLOCKON",
	"KEY_BUTTONLOCKOFF",
	"KEY_BUTTONLOCKTOGGLE",
	"KEY_VOICE_COMMAND_ENABLE",
	"KEY_MICUP",
	"KEY_MICDN",
	"KEY_MIC_MUTE_TOGGLE",
	"KEY_MIC_MUTE_ON",
	"KEY_MIC_MUTE_OFF",

	//0x003x
	"KEY_AIR_ENTER_AIR_PAIRING",
	"KEY_AIR_EXIT_AIR_PAIRING",
	"KEY_AUDIO_TRANSFER",
	"KEY_SET_VOICE_RECOGNITION",
	"KEY_RDIAL",
	"KEY_DIALMEM",
	"KEY_DIALNUM",
	"KEY_CNLOUTGOING",
	"KEY_REJCALL",
	"KEY_REJCALL_SECOND_PHONE",
	"KEY_ONHOLD_CALL",
	"KEY_ACPCALL",
	"KEY_ENDCALL",
	"KEY_3WAYRELNUDUB",
	"KEY_3WAYRELNACP",
	"KEY_3WAYRELNACP_X",

	//0x004x
	"KEY_3WAYHOLDNACP",
	"KEY_3WAYHOLDNACP_X",
	"KEY_3WAYADD",
	"KEY_3WAYCALLTRANSFER",
	"KEY_HSP_BUTTON_PRESSED",
	"KEY_DISABLE_NREC",
	"KEY_GETCALLNUM",
	"KEY_QUERY_CALL_LIST",
	"KEY_SEND_DTMF",
	"KEY_ATTACH_LAST_VOICE_TAG_RECORDED",
	"KEY_SEND_CLIP",
	"KEY_RESERVED1",
	"KEY_RESERVED2",
	"KEY_SET_VOICE_RECOGNITION_CANCEL",
	"KEY_RESERVED3",
	"KEY_SIRI_START_OR_CONTINUE",

	//0x005x
	"KEY_SIRI_END",
	"KEY_RESERVED4",
	"KEY_RESERVED5",
	"KEY_AVRCP_PLAY",
	"KEY_AVRCP_STOP",
	"KEY_AVRCP_PAUSE",
	"KEY_AVRCP_RECORD",
	"KEY_AVRCP_REWIND_PUSH",
	"KEY_AVRCP_FAST_FORWARD_PUSH",
	"KEY_AVRCP_EJECT",
	"KEY_AVRCP_FORWARD",
	"KEY_AVRCP_BACKWARD",
	"KEY_AVRCP_REWIND_RELEASE",
	"KEY_AVRCP_FAST_FORWARD_RELEASE",
	"KEY_AVRCP_REPEAT_MODE_CHANGE",
	"KEY_AVRCP_SHUFFLE_MODE_CHANGE",

	//0x006x
	"KEY_AVRCP_ACTIVE_TOGGLE",
	"KEY_PEQ_MODE_CHANGE",
	"KEY_FM_POWERON",
	"KEY_FM_POWEROFF",
	"KEY_SEEKUP",
	"KEY_SEEKDOWN",
	"KEY_TUNEUP",
	"KEY_TUNEDN",
	"KEY_FM_MUTETOGGLE",
	"KEY_ENTER_LINEIN_MODE",
	"KEY_EXIT_LINEIN_MODE",
	"KEY_LINEIN_MUTE_TOGGLE",
	"KEY_ENTER_TESTMODE",
	"KEY_SWITCH_TEST_MODE_CHANNEL",
	"KEY_SWITCH_TEST_MODE_POWER",
	"KEY_SWITCH_TEST_MODE_STATE",

	//0x007x
	"KEY_SWITCH_TEST_MODE_TX_PACKET_TYPE",
	"KEY_SCO_SWITCH",
	"KEY_AIR_ENTER_AIR_SECURE_PAIRING",
	"KEY_MULTI_A2DP_PLAY_MODE_TOGGLE",
	"KEY_CHECK_STATUS_OF_CONNECTION",
	"KEY_WHAT_CAN_I_SAY",
	"KEY_LEFT_CHANNEL",
	"KEY_RIGHT_CHANNEL",
	"KEY_STEREO_CHANNEL",
	"KEY_VOICE_COMMAND_CANCEL",
	"KEY_VOICE_MAKE_A_CALL",
	"KEY_CHECK_STATUS",
	"KEY_CHANGE_SOUND_EFFECT",
	"KEY_CONTROL_DBB_ON_OFF",
	"KEY_CONTROL_MIC_A2DP_MODE",
	"KEY_SELFIE",

	//0x008x
	"KEY_ENABLE_DUT_MODE_COMMAND",
	"KEY_MIC_L_ENABLE",
	"KEY_MIC_R_ENABLE",
	"KEY_MIC_TO_SPK_ENABLE",
	"KEY_MIC_TO_SPK_DISABLE",
	"KEY_ENABLE_EC_NR",
	"KEY_DISABLE_EC_NR",
	"KEY_2K_TONE_ENABLE",
	"KEY_2K_TONE_DISABLE",
	"KEY_SWITCH_STEREO_MONO",
	"KEY_SWITCH_SELFIE",
	"KEY_AIROTHRU",
	"KEY_ROLE_CHANGE",
	"KEY_MP3_POWERON",
	"KEY_MP3_POWEROFF",
	"KEY_MP3_PLAY",

	//0x009x
	"KEY_MP3_STOP",
	"KEY_MP3_PAUSE",
	"KEY_MP3_FORWARD",
	"KEY_MP3_BACKWARD",
	"KEY_ANC_SWITCH",
	"KEY_RESET_TO_FACTORY",
	"KEY_ANC_ON",
	"KEY_ANC_OFF",
	"DSP_RESET",
	"AWSMCE_CONNECT",
	"AWSMCE_DISCONNECT",
	"AWSMCE_ENABLEDISCOVERABLE",
	"AWSMCE_DISABLEDISCOVERABLE",
	"AWSMCE_RHO",
	"REPORT_BATTERY_STATUS",
	"SPEECH_TOGGLE",

	//0x00Ax
	"SPEECH_START",
	"SPEECH_STOP",
	"VAD_ON",
	"VAD_OFF",
	"GAME_MODE_ON",
	"GAME_MODE_OFF",
	"GAME_MODE_TOGGLE",
	"GVA_PRESS",
	"GVA_VOICE_QUERY",
	"GVA_NOTIFY",
	"GVA_CANCEL",
	"GVA_RELEASE",
	"XIAOAI_SPEECH_TOGGLE",
	"XIAOAI_SPEECH_START",
	"XIAOAI_SPEECH_STOP",		
	"SHARE_PAIRING_START",

	//0x00Bx
	"SHARE_PAIRING_STOP",
	"AGENT_STARTS_SHARE_MODE",
	"AGENT_STOPS_SHARE_MODE",
	"FOLLOWER_STARTS_SHARE_MODE",
	"FOLLOWER_STOPS_SHARE_MODE",
	"AGENT_TOGGLE_SHARE_MODE",
	"FOLLOWER_TOGGLE_SHARE_MODE",
	"KEY_MIC_TO_SPK_3MIC_MAIN_MIC_ENABLE",
	"KEY_MIC_TO_SPK_3MIC_REF1_MIC_ENABLE",	
	"KEY_MIC_TO_SPK_3MIC_REF2_MIC_ENABLE",
	"KEY_MIC_TO_SPK_3MIC_DISABLE",
};

//Start from "MEDIA_EVT_SYSTEM_BASE (0x9000)"
LOG_STRING_NEW char APP_MediaEvent2LogString[][MAX_LOG_STRING] =
{
	//0x900X	Battery
	"BAT_LOW",
	"BAT_FULL",				//battery voltage is over full_voltage", i.e.", fake charge-complete signal
	"BAT_CHGCPL",			//charge complete
	"BAT_RECHG",			//recharge
	"BAT_CHGROUT",			//charger pull out
	"BAT_CHGRIN",			//charger plug in
	"BAT_CHGTO",			//charge TO
	"BAT_HW_CHGTO",			//hw detects charging TO
	"BATTERY_INTERVAL_0",
	"BATTERY_INTERVAL_1",
	"BATTERY_INTERVAL_2",
	"BATTERY_INTERVAL_3",
	"BAT_LOW_LED",
	"BAT_LOW_RING",
	"BAT_SECURE_TEMP",
	"BAT_RISKY_TEMP",
	//0x901X
	"BAT_OK",
	"BAT_DISCOUNT_TEMP",
	"POWER_ON",
	"POWER_ON_UNDER_CHECKPOINT1",
	"POWER_OFF",
	"POWER_OFF_UNDER_CHECKPOINT1",
	"POWER_OFF_IN_SHUTDOWN_LOW_BAT",
	"MUTE_REMINDER",
	"ENTER_TESTMODE_STATE",
	"OFF_STATE",
	"FG_LED_DISPLAY_OVER",
	"RESET_COMPLETE",
	"FM_VOLUME_REACH_MAX",
	"FM_VOLUME_REACH_MIN",
	"FM_NOT_BUSY",
	"LINEIN_VOLUME_REACH_MAX",
	//0x902X
	"LINEIN_VOLUME_REACH_MIN",
	"VOICE_PROMPT_LANG_CHANGE",
	"VOICE_PROMPT_LANG_SELECT",
	"VOICE_PROMPT_LANG_CONFIRM",
	"ENTER_LINE_IN_MODE",
	"EXIT_LINE_IN_MODE",
	"MUTE_ON",
	"MUTE_OFF",
	"FM_MUTE_ON",
	"FM_MUTE_OFF",
	"FM_ENABLE",
	"POWER_OFF_UNDER_CHECKPOINT2",
	"POWER_OFF_UNDER_CHECKPOINT3",
	"POWER_ON_UNDER_CHECKPOINT2",
	"POWER_ON_UNDER_CHECKPOINT3",
	"VOICE_COMMAND_FAIL",
	//0x903X
	"VOICE_COMMAND_MULTILAYER_TRIGGER",
	"RESERVED1",
	"MIC_UPDN",
	"CALLER_ID", //0x9033
};

//Start from "MEDIA_EVT_CONNECTION_BASE (0xA000)"
LOG_STRING_NEW char APP_MediaEvent3LogString[][MAX_LOG_STRING] =
{
	//0xA00X		Indication Events
	"SLC_CONNECTED",
	"2_SLC_CONNECTED",
	"3_SLC_CONNECTED",
	"4_SLC_CONNECTED",
	"SLC_DISCONNECTED",
	"PAIRING_SUCCESSFUL",
	"PAIRING_FAIL",
	"LINK_LOSS",
	"END_OF_CALL",
	"RINGTONE",
	"RECONNECT_FAILED",  //0xA0
	"NETWORK_NOT_PRESENT",
	"NETWORK_PRESENT",
	"PINCODE_REQUEST",
	"CONFIRMATION_REQUEST",
	"CALL_CONNECTED",
	//0xA01X
	"AUDIO_LINK_OPEN",
	"AUDIO_LINK_CLOSE",
	"CONNECTABLE_TIMEOUT",
	"HFP_ERROR_RECEIVED",
	"REFRESH_ENCRYPTION",
	"ENTER_CTX_TEST_MODE",
	"ENTER_DISCOVERABLE",
	"EXIT_DISCOVERABLE",
	"ENTER_INCOMING",
	"EXIT_INCOMING",
	"PHONE_IS_TOO_FAR_1",
	"PHONE_IS_TOO_FAR_2",
	"RINGTONE_2",
	"VOLUME_REACH_MAX",
	"VOLUME_REACH_MIN",
	"REDIAL_SUCCESSFUL_EVT",
	//0xA02X
	"A2DP_VOLUME_REACH_MAX",
	"A2DP_VOLUME_REACH_MIN",
	"MISSED_CALL_REMINDER1",
	"MISSED_CALL_REMINDER2",
	"A2DP_ENABLE",
	"A2DP_DISABLE",
	"VOICE_DIAL_ENABLE",
	"REDIAL_ENABLE",
	"RINGTONE_IN_CALL",
	"RINGTONE2_IN_CALL",
	"TWS_ENTER_PAIRING",
	"TWS_EXIT_PAIRING",
	"TWS_DURING_PAIRING",
	"TWS_LEFT_CHANNEL",
	"TWS_RIGHT_CHANNEL",
	"TWS_RELAY_ONLY",
	//0xA03X
	"TWS_FOLLOWER",
	"SIRI_STARTING",
	"SIRI_CONTINUE",
	"SIRI_END",
	"KEY_FIND_MY_ACCESSORY",
	"TWS_DISCONNECTED",
	"AG_CNLOUTGOING",
	"INCOMING_CALL_ENDED",
	"ANC_ON",
	"ANC_OFF",
	"MP3_POWERON",
	"SPECIAL_CONNECTED",
	"SPECIAL_DISCONNECTED",
	"PLAYING_BEEP_SYNC",
	"LEAKAGE_DETECTION",
	"GVA_MIC_OPEN",
	/*0xA04X*/
	"GVA_MIC_CLOSE",    
	"GVA_MIC_NOT_CONNECTED",	
	"ANC_CAL_SZ",
	"PRESSURE_SENSOR",
	"FORCE_TOUCH_PRESS", 
	"FORCE_TOUCH_RELEASE",
	"XIAOAI_EVT0", 
	"XIAOAI_EVT1", 
	"XIAOAI_EVT2",
	"XIAOAI_EVT3",	
};

LOG_STRING_NEW char APP_MediaEvent4LogString[][MAX_LOG_STRING] =
{
	"TWS_EXIT_MCSYNC_SHARE_PAIRING",	
	"SHARE_MODE_START",	
	"SHARE_MODE_STOP",	
	"SHARE_MODE_CONTINUE",	
	"SHARE_MODE_FOLLOWER",	
	"SHARE_MODE_SHORT_PATTERN",

	//reserve for UART cmd to play voice prompt
	"UART_CMD_RESERVE", //0xA038
};

LOG_STRING_NEW char APP_VPLogString[][MAX_LOG_STRING] =
{
	"ZERO",
	"ONE",
	"TWO",
	"THREE",
	"FOUR",
	"FIVE",
	"SIX",
	"SEVEN",
	"EIGHT",
	"NINE",
	"VOICE_PROMPT_LANG_CHANGE",
	"VOICE_PROMPT_ON",
	"VOICE_PROMPT_OFF",
	"MULTI_POINT_MODE_ON",
	"MULTI_POINT_MODE_OFF",
	"MUTE_ON",
	"MUTE_OFF",
	"POWER_ON",
	"POWER_OFF",
	"PAIRING",
	"PAIRING_SUCCESSFUL",
	"CONNECTED",
	"SECOND_DEVICE_CONNECTED",
	"DEVICE_DISCONNECTED",
	"INCOMING_CALL",
	"CALL_REJECTED",
	"CALL_CANCELLED",
	"CALL_ENDED",
	"RE_DIALING",
	"LOW_BATTERY",
	"BATTERY_IS_HIGH",
	"BATTERY_IS_MEDIAN",
	"BATTERY_IS_LOW",
	"VOLUME_MAXIMUM",
	"PAUSE",
	"LINE_IN_MODE",
	"BLUETOOTH_MODE",
	"FM_MODE",
	"SEEK_UP",
	"SEEK_DOWN",
	"LEFT_CHANNEL",
	"RIGHT_CHANNEL",
	"WHAT_CAN_I_SAY",
	"CONNECTION_STATUS",
	"CHECK_BATTERY",
	"CANCEL",
	"VOICE_PROMPT_EXAMPLE",
	"TAKE_THE_CALL",
	"REJECT",
	"REJECT_PHONE_CALL",
	"PAIRING_FOR_VC",
	"LAST_CALL_OUT",
	"VOICE_DIAL_FOR_VC",
	"VOICE_COMMAND_EXAMPE_SET0",
	"VOICE_COMMAND_EXAMPE_SET1",
	"VOICE_COMMAND_EXAMPE_SET2",
	"MAKE_A_CALL",
	"CHECK_STATUS",
	"RING_BACK",
	"BEEP",
	"INCOMING_CALL_ENDED",
	"CALLER_ID",
	"NUMBER",
	"CALLER_ID_PREFIX",
	"CALLER_ID_SUFFIX",
	"VOLUME_MINIMUM",
};

LOG_STRING_NEW char APP_RTLogString[][MAX_LOG_STRING] =
{
	"SHORT_1_NOTE_1",
	"SHORT_1_NOTE_2",
	"SHORT_1_NOTE_3",
	"SHORT_1_NOTE_4",
	"SHORT_2_NOTE",
	"MEDIAN_1_NOTE",
	"LONG_1_NOTE_HIGH",
	"LONG_1_NOTE_LOW",
	"VERYLONG_1_NOTE_HIGH",
	"VERYLONG_1_NOTE_LOW",
	"RISING_2_NOTE",
	"RISING_4_NOTE",
	"FALLING_2_NOTE",
	"FALLING_4_NOTE",
	"LONG_RING_A",
	"LONG_RING_B",
	"LONG_RING_C",
	"LEAKAGE_DETECTION",
	"USER_DEFINED_A"
};

LOG_STRING_NEW char APP_VPRTLogString[][MAX_LOG_STRING] =
{
	"VP",
	"RT"
};

LOG_STRING_NEW char APP_ProfileLogString[][MAX_LOG_STRING] =
{
    //APP Profile Descriptor
    "",//0x0
    "HEADSET",//SCN_HEADSET,
    "HANDSFREE",//SCN_HANDSFREE,
    "SERIAL_PORT",//SCN_SERIAL_PORT,
    "LCIF",//SCN_LCIF,
    "IAP2",//SCN_IAP2,
    "SONGPAL_ANDROID",// = SCN_SONGPAL_ANDROID,
    "SONGPAL_IAP2",// = SCN_SONGPAL_IAP2,
    "OBJECT_PUSH",// = SCN_OBJECT_PUSH,
    "SIM_ACCESS",// = SCN_SIM_ACCESS,
    "PHONEBOOK_ACCESS",// = SCN_PHONEBOOK_ACCESS,
    "MESSAGE_ACCESS",// = SCN_MESSAGE_ACCESS,
    "MESSAGE_NOTIFICATION",// = SCN_MESSAGE_NOTIFICATION,
    "AIR_APP",// = SCN_AIR_APP,
    "TRSPX",//0x0E
    "",//0x0F
    "",//0x10
    "",//0x11
    "",//0x12
    "",//0x13
    "",//0x14
    "",//0x15
    "",//0x16
    "",//0x17
    "",//0x18
    "",//0x19
    "",//0x1A
    "",//0x1B
    "",//0x1C
    "",//0x1D
    "",//0x1E
    "",//0x1F
    "",//0x20
    "SDAP",//0x21,
    "A2DP",//0x22,
    "AVRCP",//0x23,
#ifdef HID_Profile
    "HID",// = 0x24,
#else
    "",//0x24
#endif
    "MCSync",//0x25
    "",//0x26
    "",//0x27
    "",//0x28
    "",//0x29
    "",//0x2A
    "",//0x2B
    "",//0x2C
    "",//0x2D
    "",//0x2E
    "",//0x2F
    //SDAP Service Record
    "PNP",// = 0x30,
    "A2DP_SOURCE",//0x31,
    "A2DP_SINK",//0x32,
    "AVRCP_TG",//0x33,
    "AVRCP_CT",//0x34,
    "MPS",//0x35
    "AMA",//0x36
    "GVA_CTL",//0x37
    "GVA_AUDIO",//0x38
<<<<<<< HEAD
=======
    "GFP",// 0x39
	"ATT_EDR",//0x3A
>>>>>>> db20e11 (second commit)
};


LOG_STRING_NEW char APP_BatStatusLogString[][MAX_LOG_STRING] =
{
	"BAT_WELL",	//CHARGER_OUT
	"BAT_LOW",	//CHARGER_OUT
	"BAT_CHARGER_IN",
	"BAT_CHARGER_RECHARGE",
	"BAT_CHARGING_FULL"
};

LOG_STRING_NEW char APP_CallHoldActiveLogString[][MAX_LOG_STRING] =
{
	"No call in Hold",
	"1 Active, others Hold",
	"All Hold"
};

LOG_STRING_NEW char APP_CallActiveLogString[][MAX_LOG_STRING] =
{
	"Call no Active",
	"Call Active,"
};

LOG_STRING_NEW char APP_CallSetupLogString[][MAX_LOG_STRING] =
{
	"CALLSETUP_NO_CALSETUP",
	"CALLSETUP_INCOMMING",
	"CALLSETUP_OUTGOING",
	"CALLSETUP_REMOTE_ALERTED",
};

LOG_STRING_NEW char APP_VoiceCommandLogString[][MAX_LOG_STRING] =
{
	"Stop_by_user",
	"Trigger_Bits:",
	"action_index",
	"event_bits",
	"Database_open_failed",
	"Database_address",  //5
	"Database_size",
	"MODE:",
	"DefaultIdentificationMode",
	"Top_state:",
	"EMPTY:", //10
	"Trigger_state_not_match",
	"Get_invalid_VC_dababase",
	"Media_event_actionIndex:",
	"table_index:",
	"VoiceCommand_Results:", //15
	"vc_Identification_Mode",
	"Get_Invalid_results",
	"Default_Mode",
	"EMPTY",
	"keyTriggerEvent", //20
	"NoVoiceCommandIdentified"
};

/* Audio Type */
LOG_STRING_NEW char APP_AudioTypeLogString[][MAX_LOG_STRING] =
{
	"AUDIO_NONE",
	"AUDIO_SCO",
	"AUDIO_A2DP",
	"AUDIO_ADDA",
	"AUDIO_VP",
	"AUDIO_RT",
	"AUDIO_MP3",
	"AUDIO_ANCPASSTHRU",
	"AUDIO_LINEIN",
	"AUDIO_AMA",
    "AUDIO_VAD",
    "AUDIO_ENCODER",
	"AUDIO_XIAOAI",
	"AUDIO_STREAM_NO",
	"AUDIO_SUSPEND",
	"AUDIO_CLOSE",
    "AUDIO_FAKE_EVT",
    "AUDIO_ANCPASSTHRU_SUSPEND",
    "AUDIO_SCO_DISC",
};


/* BT LIB String */

LOG_STRING_NEW char Rfcomm_Session_state_String[][MAX_LOG_STRING] =
{
    "RFCOMM_IDLE",
    "RFCOMM_L2CAP_CONNECTING",
    "RFCOMM_L2CAP_INCOMMING",
    "RFCOMM_L2CAP_ESTABLISHED",
    "RFCOMM_SESSION_CONNECTING",
    "RFCOMM_SESSION_ESTABLISHED",
    "RFCOMM_SESSION_DISC0_SENT_WAIT_UA",
    "RFCOMM_SESSION_JUST_CLOSED",
    "RFCOMM_L2CAP_DISCONNECTING",
    "RFCOMM_L2CAP_CONNECTING_FAIL",
    "RFCOMM_SESSION_CONNECTING_TIMEOUT",
    "RFCOMM_SESSION_CONNECTING_FAIL"
};

LOG_STRING_NEW char Rfcomm_Dlci_state_String[][MAX_LOG_STRING] =
{
    "DLC_NOT_ESTABLISHED",
    "DLC_ESTABLISHING_TIMEOUT",
    "DLC_ESTABLISHING_FAIL",
    "DLC_PN_RSP_SENT_WAIT_SABM",
    "DLC_PASSIVE_ESTABLISHED",
    "DLC_PN_SENT_WAIT_RSP",
    "DLC_PN_DONE",
    "DLC_SABM_SENT_WAIT_UA",
    "DLC_ACTIVE_ESTABLISHED",
    "DLC_MSC_SENT_WAIT_RSP",
    "DLC_MSC_ONEWAY_OK",
    "DLC_READY_FOR_DATA_COM",
    "DLC_DISC_SENT_WAIT_UA"
};

LOG_STRING_NEW char app_audio_bist_cp_mode_log_string[][MAX_LOG_STRING] =
{
    "MODE_NONE",
    "MODE_SILENCE",
    "MODE_ADDA_L",
    "MODE_ADDA_R",
    "MODE_I2S_MOSI",
    "MODE_I2S_MISO",
    "MODE_SPDIF_LOOPBACK"
};


LOG_STRING_NEW char Connect_String[] = "Connect";
LOG_STRING_NEW char Disconnect_String[] = "Signal Disconnect";
LOG_STRING_NEW char MediaConnect_String[] = "Media Connect";
LOG_STRING_NEW char Register_String[] = "Register";
LOG_STRING_NEW char UnRegister_String[] = "UnRegister";
LOG_STRING_NEW char NoApp_String[] = "No App";
LOG_STRING_NEW char NoResource_String[] = "No Resource";
LOG_STRING_NEW char Success_String[] = "Success";
LOG_STRING_NEW char Conflict_String[] = "Conflict";
LOG_STRING_NEW char AppReject_String[] = "App Reject";
LOG_STRING_NEW char Unknown_ID_String[] = "Unknown ID";
LOG_STRING_NEW char Accept_ID_String[] = "Accept";

LOG_STRING_NEW char AVDTP_SignalIDString[][MAX_LOG_STRING] ={
	"Unsupport",
	"Discover",
	"Get Capabilities",
	"Set Configuration",
	"Get Configuration",
	"Reconfigure",
	"Open",
	"Start",
	"Close",
	"Suspend",
	"Abort",
	"Security Control",
	"Get All Capabilities",
	"Delay Report",
};

LOG_STRING_NEW char NTC_LevelChargerString[][MAX_LOG_STRING] =
{
    "LEVEL_RISK_LOW",
    "LEVEL_ABNORMAL_LOW",
    "LEVEL_NORMAL",
    "LEVEL_ABNORMAL_HIGH",
    "LEVEL_RISK_HIGH",
};

LOG_STRING_NEW char NTC_LevelUNChargerString[][MAX_LOG_STRING] =
{
    "LEVEL_SECURE_LOW",
    "LEVEL_NORMAL_LOW",
    "LEVEL_NORMAL",
    "LEVEL_NORMAL_HIGH",
    "LEVEL_SECURE_HIGH",
};

/* AWS MCE*/
LOG_STRING_NEW char MCSync_IFType_String[][MAX_LOG_STRING] =
{
	"IF_TYPE_NONE",
	"IF_TYPE_A2DP",
	"IF_TYPE_SCO",
	"IF_TYPE_APP",
	"IF_TYPE_REPORT_RESET",
	"IF_TYPE_ROLE_HANDOVER",
	"IF_TYPE_PARTNER_SELECTION",
	"IF_TYPE_MIC_SELECTION",
	"IF_TYPE_RACE",
    "IF_TYPE_FOLLOWER_PKT",
};

LOG_STRING_NEW char MCSync_IF_AppOpcode_String[][MAX_LOG_STRING] =
{
	"MCSYNC_APP_SYNC_AIROKEY_NOISE",
	"MCSYNC_APP_SYNC_DEVICE_NAME",
	"MCSYNC_APP_SYNC_AIROHA_KEY",
	"MCSYNC_APP_SYNC_AIROKEY_SETTING",
	"MCSYNC_APP_SYNC_VPRT",
	"MCSYNC_APP_SYNC_STOP_VPRT",
	"MCSYNC_APP_SYNC_VPRT_PLAY_LATER",
	"MCSYNC_APP_SYNC_CALLER_ID",
	"MCSYNC_APP_SYNC_PEQ_REALTIME",
	"MCSYNC_APP_SYNC_DSP",
	"MCSYNC_APP_SYNC_POWEROFF",
	"MCSYNC_APP_SYNC_GENERAL_DATA",
	"MCSYNC_APP_SYNC_IN_EAR_DETECTION_STATUS",
    "MCSYNC_APP_SYNC_LEAKAGE_DETECT_INFO",
    "MCSYNC_APP_XIAOAI",
    "MCSYNC_APP_SYNC_SHARE_MODE_INFO",
    "MCSYNC_APP_SYNC_OTHER_AGENT_BDA",
    "MCSYNC_APP_SYNC_FOLLOWER_CONN",
    "MCSYNC_APP_SYNC_RETRANSMIT_FOLLOWER_DATA",
    "MCSYNC_APP_SYNC_NOTICE_FOLLOWER_LEAVE",
    "MCSYNC_APP_SYNC_RETRIGGER_FOLLOWER_A2DP",
    "MCSYNC_APP_SYNC_BATTERY",
    "MCSYNC_OPCODE_MODULE_SEND_DATA",
	"MCSYNC_APP_OPCODE_UNKNOW",
};

LOG_STRING_NEW char MCSync_RHO_STATUS_String[][MAX_LOG_STRING] =
{
	"Not Allowed",
	"Not Cared",
	"Needed",
};

LOG_STRING_NEW char MCSync_RHO_REASON_String[][MAX_LOG_STRING] =
{
	"Battery",
	"RSSI",
};

LOG_STRING_NEW char APP_RHO_MODULE_String[][MAX_LOG_STRING] =
{
	"Ctl Data",
	"Audio DSP",
	"Link Info",
	"Test Mode",
	"Race Cmd",
	"Power Off",
	"Pairing",
	"System",
	"Sniff",
	"Qos",
	"PEQ",
	"HFP",
	"Connection",
	"Aws Mce",
	"AVRCP",
	"A2DP" ,
	"AIRAPP"
};

LOG_STRING_NEW char APP_McsReconn_State_String[][MAX_LOG_STRING] =
{
	"MCS_RECONN_STATE_IDLE",
	"MCS_RECONN_STATE_WAIT_TO_PARTNER",
	"MCS_RECONN_STATE_WAIT_TO_AGENT",
	"MCS_RECONN_STATE_PARTNER_RECONNECTING",
	"MCS_RECONN_STATE_AGENT_RECONNECTING",
	"MCS_RECONN_STATE_AGENT_IDLE",
	"MCS_RECONN_STATE_AGENT_WAIT_RECONNECT_FAILED",
	"MCS_RECONN_STATE_CANCELING",
};

LOG_STRING_NEW char APP_McsReconn_Action_String[][MAX_LOG_STRING] =
{
	"MCS_RECONN_ACTION_SET_TO_PARTNER",
	"MCS_RECONN_ACTION_SET_TO_AGENT",
	"MCS_RECONN_ACTION_RECONNECT",
};

LOG_STRING_NEW char APP_McsReconn_Event_String[][MAX_LOG_STRING] =
{
	"MCS_RECONN_EVENT_SET_PARTNER_SUCCESSFUL",
	"MCS_RECONN_EVENT_SET_PARTNER_FAILED",
	"MCS_RECONN_EVENT_SET_AGENT_SUCCESSFUL",
	"MCS_RECONN_EVENT_SET_AGENT_FAILED",
	"MCS_RECONN_EVENT_RECONNECT_TIMEOUT",
	"MCS_RECONN_EVENT_RECONNECT_FAILED",
	"MCS_RECONN_EVENT_RECONNECT_FAILED_ALREADY_EXIST",
	"MCS_RECONN_EVENT_RECONNECT_FAILED_CONN_ACCEPT_TO",
	"MCS_RECONN_EVENT_AGENT_WITH_PARTNER",
	"MCS_RECONN_EVENT_AGENT_WITH_AG",
	"MCS_RECONN_EVENT_CANCEL_MODE",
	"MCS_RECONN_EVENT_RECONNECT_FAIL_LMP_RESP_TIMEOUT",
};

LOG_STRING_NEW char APP_McsReconn_TimerId_String[][MAX_LOG_STRING] =
{
	"ID_RECONNECT_TIMEOUT",
	"ID_RECONNECT_NOTIFY",
	"ID_ACTION_HANDLER",
	"ID_STATE_HANDLER",
	"ID_ENTER_SUPER_RECONNECT",
};

/*Lib Charger*/

/*Smart Charger Case*/
LOG_STRING_NEW char APP_SmartCase_DrvEvt_String[][MAX_LOG_STRING] =
{
	"",
	"[BT ON] Pattern",
	"[BT OFF] Pattern",
	"[Chg-CPL] Pattern",
	"[Chg-OUT] Pattern",
	"[RESERVE-0] Pattern",
	"[RESERVE-1] Pattern",
	"[RESERVE-2] Pattern",
	"[RESERVE-3] Pattern",
	"[RESERVE-4] Pattern",
	"[Chg-In] Interrupt",
	"[Chg-CPL] Interrupt",
	"[Re-Chg] Interrupt",
	"[Charger Key(V2)] Pattern",
	"[USER 1(V2)] Pattern",
	"[USER 2(V2)] Pattern",
	"[USER 3(V2)] Pattern",
};

LOG_STRING_NEW char LibDrv_SmartCase_StateString[][MAX_LOG_STRING] =
{
	"STATE_CASE_OFF",
	"STATE_OUT_OF_CASE",
	"STATE_LID_CLOSE",
	"STATE_LID_OPEN",
};

LOG_STRING_NEW char LibDrv_Charger_StateString[][MAX_LOG_STRING] =
{
	"STATE_CHARGER_OUT",
	"STATE_CHARGING",
	"STATE_CHARGER_CPL",
};

/* App Smart Case*/
LOG_STRING_NEW char APP_McSyncLinkString[][MAX_LOG_STRING] =
{
	"MCSYNC_LINK_SAWS_DISCONNECTED",
	"MCSYNC_LINK_SAWS_CONNECTING",
	"MCSYNC_LINK_SAWS_DISCONNECTING",
	"MCSYNC_LINK_SAWS_READY/MCSYNC_LINK_DISCONNECTED",
	"MCSYNC_LINK_CONNECTING",
	"MCSYNC_LINK_CONNECTED",
	"MCSYNC_LINK_DISCONNECTING",
};

LOG_STRING_NEW char APP_LinkConnString[][MAX_LOG_STRING]=
{
	"LINK_DISCONNECTED",
	"LINK_CONNECTING",
	"LINK_CONNECTED",
	"LINK_DISCONNECTING",
};

LOG_STRING_NEW char a2dp_codec_log_string[][MAX_LOG_STRING] =
{
    "DUMMY",
    "SBC_SNK",
    "AAC_SNK",
    "SBC_SRC",
    "CELT_SNK",
};

LOG_STRING_NEW char a2dp_vendor_codec_log_string[] = "Vendor Codec";

LOG_STRING_NEW char xiaoai_mcsync_cb_string[][MAX_LOG_STRING] =
{
	"mcsync_begin",			//XIAOAI_OTA_SEND_BEGIN
	"mcsync_data",			//XIAOAI_OTA_SEND_DATA
	"mcsync_apply",			//XIAOAI_OTA_SEND_APPLY
	"mcsync_reboot",		//XIAOAI_OTA_SEND_REBOOT
	"send_sha256",			//XIAOAI_OTA_SEND_FS_SHA256
	"begin_reply",			//XIAOAI_OTA_SEND_BEGIN_REPLY
	"mcsync_data_reply",	//XIAOAI_OTA_SEND_DATA_REPLY
	"apply_reply",			//XIAOAI_OTA_SEND_APPLY_REPLY
};
#endif
/*LOG_STRING char DBG_HANG_01_String[] = "[HALT DBG:1]";
LOG_STRING char DBG_HANG_02_String[] = "[HALT DBG:2]";
LOG_STRING char DBG_HANG_03_String[] = "[HALT DBG:3]";
LOG_STRING char DBG_HANG_04_String[] = "[HALT DBG:4]";
LOG_STRING char DBG_HANG_05_String[] = "[HALT DBG:5]";
LOG_STRING char DBG_HANG_06_String[] = "[HALT DBG:6]";
LOG_STRING char DBG_HANG_07_String[] = "[HALT DBG:7 %d]";
LOG_STRING char DBG_HANG_08_String[] = "[HALT DBG:8]";
LOG_STRING char DBG_HANG_09_String[] = "[HALT DBG:9]";
LOG_STRING char DBG_HANG_10_String[] = "[HALT DBG:10 %d]";
LOG_STRING char DBG_HANG_11_String[] = "[HALT DBG:11 %d]";
LOG_STRING char DBG_HANG_12_String[] = "[HALT DBG:12 %d]";
LOG_STRING char DBG_HANG_13_String[] = "[HALT DBG:13]";
LOG_STRING char DBG_HANG_14_String[] = "[HALT DBG:14]";*/


