/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */
 
 
// 0x0001
EVENT_NAME(RECONNECT_USER_INIT)
EVENT_NAME(DISCOVERABLE)
EVENT_NAME(NONDISCOVERABLE)
EVENT_NAME(CONNECTED_TO_DISCOVERABLE)
EVENT_NAME(CONNECTED_TO_CONNECTABLE)
EVENT_NAME(NFC_DISCOVREABLE)
EVENT_NAME(CONFIRMATION_ACCEPT)
EVENT_NAME(CONFIRMATION_REJECT)
EVENT_NAME(DEBUG_KEY_TOGGLE)
EVENT_NAME(VOICEUP)
EVENT_NAME(VOICEDN)
EVENT_NAME(BUZZER_MUTE_TOGGLE)
EVENT_NAME(TOGGLE_VOLUME)
EVENT_NAME(VOLUME_ORIENTATION_NORMAL)
EVENT_NAME(VOLUME_ORIENTATION_INVERT)


//0x001x
EVENT_NAME(TOGGLE_LED)
EVENT_NAME(ENABLE_LED)
EVENT_NAME(DISABLE_LED)
EVENT_NAME(CANCEL_LED_INDICATION)
EVENT_NAME(MEDIA_TRIGGER_1)
EVENT_NAME(MEDIA_TRIGGER_2)
EVENT_NAME(POWER_ON_THEN_ENTERDISCOVERABLE)
EVENT_NAME(POWER_ON)
EVENT_NAME(POWER_OFF)
EVENT_NAME(RESET)
EVENT_NAME(RESET_PAIRED_DEVICES)
EVENT_NAME(MAX_DEVICE_ALLOWED_UP)
EVENT_NAME(MAX_DEVICE_ALLOWED_DOWN)
EVENT_NAME(MAX_DEVICE_ALLOWED_TOGGLE)
EVENT_NAME(RECONNECT_AFTER_POWER_ON)
EVENT_NAME(VOICE_PROMPT_TOGGLE)

//0x002x
EVENT_NAME(VOICE_PROMPT_ENABLE)
EVENT_NAME(VOICE_PROMPT_DISABLE)
EVENT_NAME(VOICE_PROMPT_LANG_CHANGE)
EVENT_NAME(VOICE_PROMPT_LANG_SELECT)
EVENT_NAME(VOICE_PROMPT_LANG_CONFIRM)
EVENT_NAME(TEST_VOICE_PROMPT_PLAY)
EVENT_NAME(TEST_VOICE_PROMPT_NEXT)
EVENT_NAME(BUTTONLOCKON)
EVENT_NAME(BUTTONLOCKOFF)
EVENT_NAME(BUTTONLOCKTOGGLE)
EVENT_NAME(VOICE_COMMAND_ENABLE)
EVENT_NAME(MICUP)
EVENT_NAME(MICDN)
EVENT_NAME(MIC_MUTE_TOGGLE)
EVENT_NAME(MIC_MUTE_ON)
EVENT_NAME(MIC_MUTE_OFF)

//0x003x
EVENT_NAME(AIR_ENTER_AIR_PAIRING)
EVENT_NAME(AIR_EXIT_AIR_PAIRING)
EVENT_NAME(AUDIO_TRANSFER)
EVENT_NAME(SET_VOICE_RECOGNITION)
EVENT_NAME(RDIAL)
EVENT_NAME(DIALMEM)
EVENT_NAME(DIALNUM)
EVENT_NAME(CNLOUTGOING)
EVENT_NAME(REJCALL)
EVENT_NAME(REJCALL_SECOND_PHONE)
EVENT_NAME(ONHOLD_CALL)
EVENT_NAME(ACPCALL)
EVENT_NAME(ENDCALL)
EVENT_NAME(3WAYRELNUDUB)
EVENT_NAME(3WAYRELNACP)
EVENT_NAME(3WAYRELNACP_X)

//0x004x
EVENT_NAME(3WAYHOLDNACP)
EVENT_NAME(3WAYHOLDNACP_X)
EVENT_NAME(3WAYADD)
EVENT_NAME(3WAYCALLTRANSFER)
EVENT_NAME(HSP_BUTTON_PRESSED)
EVENT_NAME(DISABLE_NREC)
EVENT_NAME(GETCALLNUM)
EVENT_NAME(QUERY_CALL_LIST)
EVENT_NAME(SEND_DTMF)
EVENT_NAME(ATTACH_LAST_VOICE_TAG_RECORDED)
EVENT_NAME(SEND_CLIP)
EVENT_NAME(RESERVED1)
EVENT_NAME(RESERVED2)
EVENT_NAME(SET_VOICE_RECOGNITION_CANCEL)
EVENT_NAME(RESERVED3)
EVENT_NAME(SIRI_START_OR_CONTINUE)

//0x005x
EVENT_NAME(SIRI_END)
EVENT_NAME(RESERVED4)
EVENT_NAME(RESERVED5)
EVENT_NAME(AVRCP_PLAY)
EVENT_NAME(AVRCP_STOP)
EVENT_NAME(AVRCP_PAUSE)
EVENT_NAME(AVRCP_RECORD)
EVENT_NAME(AVRCP_REWIND_PUSH)
EVENT_NAME(AVRCP_FAST_FORWARD_PUSH)
EVENT_NAME(AVRCP_EJECT)
EVENT_NAME(AVRCP_FORWARD)
EVENT_NAME(AVRCP_BACKWARD)
EVENT_NAME(AVRCP_REWIND_RELEASE)
EVENT_NAME(AVRCP_FAST_FORWARD_RELEASE)
EVENT_NAME(AVRCP_REPEAT_MODE_CHANGE)
EVENT_NAME(AVRCP_SHUFFLE_MODE_CHANGE)

//0x006x
EVENT_NAME(AVRCP_ACTIVE_TOGGLE)
EVENT_NAME(PEQ_GROUP_CHANGE)
EVENT_NAME(FM_POWERON)
EVENT_NAME(FM_POWEROFF)
EVENT_NAME(SEEKUP)
EVENT_NAME(SEEKDOWN)
EVENT_NAME(TUNEUP)
EVENT_NAME(TUNEDN)
EVENT_NAME(FM_MUTETOGGLE)
EVENT_NAME(ENTER_LINEIN_MODE)
EVENT_NAME(EXIT_LINEIN_MODE)
EVENT_NAME(LINEIN_MUTE_TOGGLE)
EVENT_NAME(ENTER_TESTMODE)
EVENT_NAME(SWITCH_TEST_MODE_CHANNEL)
EVENT_NAME(SWITCH_TEST_MODE_POWER)
EVENT_NAME(SWITCH_TEST_MODE_STATE)

//0x007x
EVENT_NAME(SWITCH_TEST_MODE_TX_PACKET_TYPE)
EVENT_NAME(SCO_SWITCH)
EVENT_NAME(AIR_ENTER_AIR_SECURE_PAIRING)
EVENT_NAME(MULTI_A2DP_PLAY_MODE_TOGGLE)
EVENT_NAME(CHECK_STATUS_OF_CONNECTION)
EVENT_NAME(WHAT_CAN_I_SAY)
EVENT_NAME(LEFT_CHANNEL)
EVENT_NAME(RIGHT_CHANNEL)
EVENT_NAME(STEREO_CHANNEL)
EVENT_NAME(VOICE_COMMAND_CANCEL)
EVENT_NAME(VOICE_MAKE_A_CALL)
EVENT_NAME(CHECK_STATUS)
EVENT_NAME(CHANGE_SOUND_EFFECT)
EVENT_NAME(CONTROL_DBB_ON_OFF)
EVENT_NAME(CONTROL_MIC_A2DP_MODE)
EVENT_NAME(SELFIE)


//0x008x
EVENT_NAME(ENABLE_DUT_MODE_COMMAND)
EVENT_NAME(MIC_L_ENABLE)
EVENT_NAME(MIC_R_ENABLE)
EVENT_NAME(MIC_TO_SPK_ENABLE)
EVENT_NAME(MIC_TO_SPK_DISABLE)
EVENT_NAME(ENABLE_EC_NR)
EVENT_NAME(DISABLE_EC_NR)
EVENT_NAME(2K_TONE_ENABLE)
EVENT_NAME(2K_TONE_DISABLE)
EVENT_NAME(SWITCH_STEREO_MONO)
EVENT_NAME(SWITCH_SELFIE)
EVENT_NAME(AIROTHRU)
EVENT_NAME(ROLE_CHANGE)
EVENT_NAME(MP3_POWERON)
EVENT_NAME(MP3_POWEROFF)
EVENT_NAME(MP3_PLAY)

//0x009x
EVENT_NAME(MP3_STOP)
EVENT_NAME(MP3_PAUSE)
EVENT_NAME(MP3_FORWARD)
EVENT_NAME(MP3_BACKWARD)
EVENT_NAME(ANC_SWITCH)
EVENT_NAME(RESET_TO_FACTORY)
EVENT_NAME(ANC_ON)
EVENT_NAME(ANC_OFF)
EVENT_NAME(DSP_RESET)
EVENT_NAME(AWSMCE_CONNECT)
EVENT_NAME(AWSMCE_DISCONNECT)
EVENT_NAME(AWSMCE_ENABLEDISCOVERABLE)
EVENT_NAME(AWSMCE_DISABLEDISCOVERABLE)
EVENT_NAME(AWSMCE_RHO)
EVENT_NAME(REPORT_BATTERY_STATUS)
EVENT_NAME(SPEECH_TOGGLE)

//0x00Ax
EVENT_NAME(SPEECH_START)
EVENT_NAME(SPEECH_STOP)
EVENT_NAME(VAD_ON)
EVENT_NAME(VAD_OFF)
EVENT_NAME(GAME_MODE_ON)
EVENT_NAME(GAME_MODE_OFF)
EVENT_NAME(GAME_MODE_TOGGLE)
EVENT_NAME(GVA_PRESS)
EVENT_NAME(GVA_VOICE_QUERY)
EVENT_NAME(GVA_NOTIFY)
EVENT_NAME(GVA_CANCEL)
EVENT_NAME(GVA_RELEASE)
EVENT_NAME(XIAOAI_FUNC_2)
EVENT_NAME(XIAOAI_SPEECH_START)
EVENT_NAME(XIAOAI_FUNC_1)
EVENT_NAME(SHARE_PAIRING_START)

//0x00Bx
EVENT_NAME(SHARE_PAIRING_STOP)
EVENT_NAME(AGENT_STARTS_SHARE_MODE)
EVENT_NAME(AGENT_STOPS_SHARE_MODE)
EVENT_NAME(FOLLOWER_STARTS_SHARE_MODE)
EVENT_NAME(FOLLOWER_STOPS_SHARE_MODE)
EVENT_NAME(AGENT_TOGGLE_SHARE_MODE)
EVENT_NAME(FOLLOWER_TOGGLE_SHARE_MODE)
EVENT_NAME(MIC_TO_SPK_3MIC_MAIN_MIC_ENABLE)
EVENT_NAME(MIC_TO_SPK_3MIC_REF1_MIC_ENABLE)	
EVENT_NAME(MIC_TO_SPK_3MIC_REF2_MIC_ENABLE)
EVENT_NAME(MIC_TO_SPK_3MIC_DISABLE)

