/* Copyright Statement:
 *
 * (C) 2017  Airoha Technology Corp. All rights reserved.
 *
 * This software/firmware and related documentation ("Airoha Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to Airoha Technology Corp. ("Airoha") and/or its licensors.
 * Without the prior written permission of Airoha and/or its licensors,
 * any reproduction, modification, use or disclosure of Airoha Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) Airoha Software
 * if you have agreed to and been bound by the applicable license agreement with
 * Airoha ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of Airoha Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT AIROHA SOFTWARE RECEIVED FROM AIROHA AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES AIROHA PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH AIROHA SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN AIROHA SOFTWARE. AIROHA SHALL ALSO NOT BE RESPONSIBLE FOR ANY AIROHA
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND AIROHA'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO AIROHA SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT AIROHA'S OPTION, TO REVISE OR REPLACE AIROHA SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * AIROHA FOR SUCH AIROHA SOFTWARE AT ISSUE.
 */
  
 #ifndef __BTMODULE_LOG_TABLE_MODULE_H__
 #define __BTMODULE_LOG_TABLE_MODULE_H__

#define PACKED __attribute__((packed))
 
/*************************************************************************************************
Module log Module 
 **************************************************************************************************/

enum
{
	//app layer
	MODULE_LOG_MODULE_APP_LAYER_BEGIN 		= 0x00,
	MODULE_LOG_MODULE_APP_A2DP,
	MODULE_LOG_MODULE_APP_DSP_CONTROL,
	MODULE_LOG_MODULE_APP_NVKEY,
	MODULE_LOG_MODULE_APP_AIRAPP,
	MODULE_LOG_MODULE_APP_DSP_MUSIC_EFFECT, //0X05
	MODULE_LOG_MODULE_APP_NVRAM,
	MODULE_LOG_MODULE_APP_AIRMODULE,
	MODULE_LOG_MODULE_APP_FCD,
	MODULE_LOG_MODULE_APP_PEQ,
	MODULE_LOG_MODULE_APP_AMA, //0X0A
	MODULE_LOG_MODULE_APP_HFP,
	MODULE_LOG_MODULE_APP_QOS,
	MODULE_LOG_MODULE_APP_AUDIO_DRIVER,
	MODULE_LOG_MODULE_APP_LED_CONTROL,
	MODULE_LOG_MODULE_APP_REAL_TIME,
	MODULE_LOG_MODULE_APP_AVRCP, //0x10
	MODULE_LOG_MODULE_APP_LINEIN,
	MODULE_LOG_MODULE_APP_SNIFF,
	MODULE_LOG_MODULE_APP_CONNECTION,
	MODULE_LOG_MODULE_APP_MCSYNC,
	MODULE_LOG_MODULE_APP_STATE, //0x15
	MODULE_LOG_MODULE_APP_CUSTOMER,
	MODULE_LOG_MODULE_APP_MCSYNCRHO,
	MODULE_LOG_MODULE_APP_TEST_MODE,
	MODULE_LOG_MODULE_APP_VOICE_COMMAND,
	MODULE_LOG_MODULE_APP_VPRT_CONTROL, //0x1A
	MODULE_LOG_MODULE_APP_CAPTOUCH,
	MODULE_LOG_MODULE_APP_CHARGER_BATTERY,
	MODULE_LOG_MODULE_APP_EVENT_KEY,
	MODULE_LOG_MODULE_APP_IN_EAR_DETECTION,
	MODULE_LOG_MODULE_APP_KEY,
	MODULE_LOG_MODULE_APP_MEDIA, //0x20
	MODULE_LOG_MODULE_APP_PAIRING,
	MODULE_LOG_MODULE_APP_RACECMD, 
	MODULE_LOG_MODULE_APP_VOLUME_CONTROL, //0x23
	MODULE_LOG_MODULE_APP_POWER, 
	MODULE_LOG_MODULE_APP_LAYER_END 		= 0x3F,

	//Profile layer
	MODULE_LOG_MODULE_PROFILE_LAYER_BEGIN 	= 0x40,
	MODULE_LOG_MODULE_PROFILE_AVRCP,
	MODULE_LOG_MODULE_PROFILE_DEVICE_ID,
	MODULE_LOG_MODULE_PROFILE_GATT_BATTERY_SERVER,
	MODULE_LOG_MODULE_PROFILE_GATT_GAP_SERVER,
	MODULE_LOG_MODULE_PROFILE_HFP,		//0x45
	MODULE_LOG_MODULE_PROFILE_HID,
	MODULE_LOG_MODULE_PROFILE_MCSYNC,
	MODULE_LOG_MODULE_PROFILE_MANAGEMENT,
	MODULE_LOG_MODULE_PROFILE_SPP,
	MODULE_LOG_MODULE_PROFILE_LAYER_END 	= 0x6F,

	//protocol layer
	MODULE_LOG_MODULE_PROTOCOL_LAYER_BEGIN = 0x70,
	MODULE_LOG_MODULE_PROTOCOL_LAYER_END 	= 0x9F,

	//middle layer
	MODULE_LOG_MODULE_MIDDLE_LAYER_BEGIN 	= 0xA0,
	MODULE_LOG_MODULE_MIDDLE_LAYER_END		= 0xCF,

	//system layer
	MODULE_LOG_MODULE_SYSTEM_BEGIN 	    = 0xD0,
	MODULE_LOG_MODULE_SYSTEM_CRASH      = 0xD1,
	MODULE_LOG_MODULE_SYSTEM_END		= 0xEF,
};

/*************************************************************************************************
Structure
 **************************************************************************************************/


 
 #endif //__BTMODULE_LOG_TABLE_MODULE_H__

